/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKMapAnnotationTrackingCameraController : VKAnnotationTrackingCameraController  {
}


- (double)_zoomLevelForCameraPosition:(struct VKPoint { double x1; double x2; double x3; })arg1;
- (double)_minTrackingCameraDistance;
- (void)_rotateToHeadingAnimated:(bool)arg1 duration:(double)arg2;
- (void)_goToAnnotationAnimated:(bool)arg1 duration:(double)arg2 isInitial:(bool)arg3;

@end
