/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@class VKPolylineOverlayPainter, NSMapTable, VKPolylineOverlay;

@interface VKPolylineGroupOverlayPainter : VKOverlayPainter <VKPolylineGroupOverlayObserver> {
    VKPolylineOverlay *_selectedPolyline;
    NSMapTable *_polylinesToPainters;
    BOOL _showTraffic;
}

@property(readonly) VKPolylineOverlayPainter * selectedPolylinePainter;
@property BOOL showTraffic;


- (id)selectedPolylinePainter;
- (void)_addPainterForOverlay:(id)arg1;
- (void)polylineGroup:(id)arg1 didSelectPolyline:(id)arg2;
- (void)polylineGroup:(id)arg1 didRemovePolyline:(id)arg2;
- (void)polylineGroup:(id)arg1 didAddPolyline:(id)arg2;
- (void)setShowTraffic:(BOOL)arg1;
- (BOOL)showTraffic;
- (id)initWithOverlay:(id)arg1;
- (void)drawDebug:(id)arg1 tiles:(id)arg2;
- (void)drawWithContext:(id)arg1 tiles:(id)arg2;
- (void)layoutWithContext:(id)arg1 tiles:(id)arg2 keysInView:(id)arg3;
- (void)setContainerModel:(id)arg1;
- (void)stylesheetDidChange;
- (void)dealloc;

@end
