/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@class NSString;

@interface PKPaymentApplication : NSObject <NSSecureCoding> {
    bool_supportsContactlessPayment;
    bool_supportsInAppPayment;
    NSString *_dpanIdentifier;
    NSString *_dpanSuffix;
    NSString *_applicationIdentifier;
    NSString *_secureElementIdentifier;
    long long _state;
    long long _paymentNetworkIdentifier;
}

@property(setter=setDPANIdentifier:,copy) NSString * dpanIdentifier;
@property(setter=setDPANSuffix:,copy) NSString * dpanSuffix;
@property(copy) NSString * applicationIdentifier;
@property(copy) NSString * secureElementIdentifier;
@property long long state;
@property(readonly) NSString * stateAsString;
@property bool supportsContactlessPayment;
@property bool supportsInAppPayment;
@property long long paymentNetworkIdentifier;

+ (bool)supportsSecureCoding;

- (void)setPaymentNetworkIdentifier:(long long)arg1;
- (long long)paymentNetworkIdentifier;
- (void)setSupportsInAppPayment:(bool)arg1;
- (bool)supportsInAppPayment;
- (void)setSupportsContactlessPayment:(bool)arg1;
- (bool)supportsContactlessPayment;
- (void)setDPANSuffix:(id)arg1;
- (void)setDPANIdentifier:(id)arg1;
- (id)stateAsString;
- (bool)isEqualToPaymentApplication:(id)arg1;
- (id)initWithPaymentApplicationDictionary:(id)arg1;
- (void)setSecureElementIdentifier:(id)arg1;
- (id)dpanSuffix;
- (id)dpanIdentifier;
- (id)secureElementIdentifier;
- (void)setApplicationIdentifier:(id)arg1;
- (id)applicationIdentifier;
- (bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)setState:(long long)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (long long)state;
- (void)dealloc;
- (id)description;

@end
