/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@class PKImage;

@interface PKPassLogoImageSet : PKPassImageSet  {
    PKImage *_logoImage;
    PKImage *_backgroundImage;
    PKImage *_stripImage;
    PKImage *_bankLogoImage;
    PKImage *_networkLogoImage;
    PKImage *_cobrandLogoImage;
    PKImage *_cardBackgroundImage;
    PKImage *_cardBackgroundCombinedImage;
}

@property(retain) PKImage * logoImage;
@property(retain) PKImage * backgroundImage;
@property(retain) PKImage * stripImage;
@property(retain) PKImage * bankLogoImage;
@property(retain) PKImage * networkLogoImage;
@property(retain) PKImage * cobrandLogoImage;
@property(retain) PKImage * cardBackgroundImage;
@property(retain) PKImage * cardBackgroundCombinedImage;

+ (long long)imageSetType;
+ (bool)supportsSecureCoding;
+ (bool)shouldCache;

- (id)cobrandLogoImage;
- (id)networkLogoImage;
- (id)bankLogoImage;
- (void)setCardBackgroundImage:(id)arg1;
- (void)setCobrandLogoImage:(id)arg1;
- (void)setNetworkLogoImage:(id)arg1;
- (void)setBankLogoImage:(id)arg1;
- (id)cardBackgroundCombinedImage;
- (void)setCardBackgroundCombinedImage:(id)arg1;
- (void)setStripImage:(id)arg1;
- (void)setLogoImage:(id)arg1;
- (id)initWithDisplayProfile:(id)arg1 fileURL:(id)arg2 screenScale:(double)arg3 suffix:(id)arg4;
- (id)stripImage;
- (id)logoImage;
- (void)preheatImages;
- (bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (void)setBackgroundImage:(id)arg1;
- (id)backgroundImage;
- (id)cardBackgroundImage;

@end
