/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/usr/lib/system/libdispatch.dylib
 */

@interface OS_dispatch_semaphore : OS_dispatch_object <OS_dispatch_semaphore> {
}

+ (void)load;


@end
