/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/ToneKit.framework/ToneKit
 */

@interface TKPickerTableViewCell : UITableViewCell  {
}


- (void)setSectionLocation:(int)arg1 animated:(bool)arg2;

@end
