/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/BluetoothManager.framework/BluetoothManager
 */

@class NSObject<OS_xpc_object>;

@interface RemoteDeviceManager : NSObject  {
    NSObject<OS_xpc_object> *_connection;
}


- (void)sendMessage:(const char *)arg1 args:(id)arg2;
- (void)disconnectDevice:(id)arg1;
- (id)init;
- (void)dealloc;

@end
