/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

@interface SUClientDispatch : NSObject  {
}

+ (BOOL)wasLaunchedFromLibrary;
+ (struct __CFArray { }*)assetTypes;
+ (BOOL)composeReviewWithViewController:(id)arg1 animated:(BOOL)arg2;
+ (BOOL)sendActionForDialog:(id)arg1 button:(id)arg2;
+ (id)newScriptInterface;
+ (id)imagePool;
+ (BOOL)enterAccountFlowWithViewController:(id)arg1 animated:(BOOL)arg2;
+ (id)overlayConfigurationForStorePage:(id)arg1;
+ (BOOL)matchesClientApplication:(id)arg1;
+ (id)exitStoreButtonTitle;
+ (BOOL)isTabBarControllerLoaded;
+ (void)composeEmailWithSubject:(id)arg1 body:(id)arg2;
+ (void)dismissOverlayBackgroundViewController;
+ (BOOL)presentOverlayBackgroundViewController:(id)arg1;
+ (id)overlayBackgroundViewController;
+ (id)clientInterface;
+ (BOOL)openClientURL:(id)arg1;
+ (id)scriptExecutionContext;
+ (id)imageCache;
+ (id)tabBarController;


@end
