/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

@class NSString, SUScriptViewController;

@interface SUScriptSection : SUScriptObject  {
    NSString *_badgeValue;
    NSString *_identifier;
    bool_transient;
    SUScriptViewController *_viewController;
}

@property(retain) NSString * badgeValue;
@property(readonly) NSString * identifier;
@property(readonly) bool transient;
@property(readonly) SUScriptViewController * viewController;

+ (id)webScriptNameForKeyName:(id)arg1;
+ (id)webScriptNameForSelector:(SEL)arg1;
+ (void)initialize;

- (bool)transient;
- (id)initWithNativeSection:(id)arg1;
- (void)setBadgeValue:(id)arg1 animated:(bool)arg2 blink:(bool)arg3;
- (id)_className;
- (id)scriptAttributeKeys;
- (id)identifier;
- (id)attributeKeys;
- (void)dealloc;
- (id)badgeValue;
- (void)setBadgeValue:(id)arg1;
- (id)viewController;

@end
