/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

@class NSString;

@interface SUScriptAccountPageViewController : SUScriptStorePageViewController  {
}

@property(retain) NSString * style;
@property(readonly) NSString * styleNameDefault;
@property(readonly) NSString * styleNameSignUp;
@property(readonly) NSString * styleNameViewAccount;

+ (id)webScriptNameForKeyName:(id)arg1;
+ (void)initialize;

- (id)styleNameDefault;
- (id)styleNameViewAccount;
- (id)styleNameSignUp;
- (id)newNativeViewController;
- (id)_className;
- (id)scriptAttributeKeys;
- (id)attributeKeys;
- (void)setStyle:(id)arg1;
- (id)style;

@end
