/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/iTunesStoreUI.framework/iTunesStoreUI
 */

@class UILabel, NSString;

@interface SUTextContentView : UITextContentView  {
    UILabel *_placeholderLabel;
}

@property(retain) NSString * placeholder;


- (void)setBackgroundColor:(id)arg1;
- (bool)resignFirstResponder;
- (bool)becomeFirstResponder;
- (void)dealloc;
- (id)placeholder;
- (void)setPlaceholder:(id)arg1;
- (void)keyboardInputChangedSelection:(id)arg1;
- (void)setText:(id)arg1;
- (void)layoutSubviews;

@end
