/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/GameKit.framework/Frameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@class GKPlayer, NSString, GKChallengeInternal, NSOrderedSet, NSDate, GKGame;

@interface GKChallenge : NSObject <NSCoding, NSSecureCoding> {
    GKChallengeInternal *_internal;
    NSOrderedSet *_compatibleBundleIDs;
}

@property(readonly) NSString * issuingPlayerID;
@property(readonly) NSString * receivingPlayerID;
@property(readonly) int state;
@property(readonly) NSDate * issueDate;
@property(readonly) NSDate * completionDate;
@property(readonly) NSString * message;
@property(retain) GKChallengeInternal * internal;
@property(readonly) NSString * challengeID;
@property(readonly) NSString * bundleID;
@property(readonly) NSOrderedSet * compatibleBundleIDs;
@property(readonly) GKGame * game;
@property(readonly) GKPlayer * issuingPlayer;
@property(readonly) GKPlayer * receivingPlayer;
@property(readonly) BOOL detailsLoaded;

+ (id)challengeForGame:(id)arg1 andPlayer:(id)arg2 withAchievement:(id)arg3;
+ (id)challengeForGame:(id)arg1 andPlayer:(id)arg2 withScore:(id)arg3;
+ (void)loadReceivedChallengesWithCompletionHandler:(id)arg1;
+ (void)loadChallengesForReceivingPlayer:(id)arg1 withCompletionHandler:(id)arg2;
+ (void)getCountOfChallenges:(id)arg1;
+ (void)loadChallengesForGame:(id)arg1 receivingPlayer:(id)arg2 withCompletionHandler:(id)arg3;
+ (id)challengeForInternalRepresentation:(id)arg1;
+ (id)stringForState:(int)arg1;
+ (BOOL)instancesRespondToSelector:(SEL)arg1;
+ (id)instanceMethodSignatureForSelector:(SEL)arg1;
+ (BOOL)supportsSecureCoding;

- (void)loadDetailsWithCompletionHandler:(id)arg1;
- (BOOL)detailsLoaded;
- (void)issueToPlayers:(id)arg1 message:(id)arg2;
- (id)compatibleBundleIDs;
- (id)infoTextForIssuingPlayer:(id)arg1;
- (void)loadUIDetailsWithHandler:(id)arg1;
- (BOOL)hasLoadedUIDetails;
- (void)decline;
- (id)receivingPlayer;
- (id)issuingPlayer;
- (id)game;
- (void)setInternal:(id)arg1;
- (id)internal;
- (id)initWithInternalRepresentation:(id)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (void)dealloc;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (id)valueForUndefinedKey:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)detailFromText;
- (id)detailGoalText;
- (id)listGoalText;
- (id)listTitleText;
- (id)iconURLString;
- (id)iconSource;
- (void)loadImageWithSource:(id)arg1 URLString:(id)arg2 withHandler:(id)arg3;
- (id)smallIconURLString;
- (id)smallIconSource;
- (id)alertGoalText;
- (void)loadBannerImageWithHandler:(id)arg1;
- (id)composeGoalText;
- (void)loadImageWithCompletionHandler:(id)arg1;

@end
