/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/CloudKitDaemon.framework/CloudKitDaemon
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSArray;

@interface CKWaiterWrapper : NSObject  {
    id _waiter;
    NSArray *_zoneIDs;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _completionHandler;

}

@property(retain) id waiter;
@property(retain) NSArray * zoneIDs;
@property(copy) id completionHandler;


- (void)setWaiter:(id)arg1;
- (id)waiter;
- (void)setZoneIDs:(id)arg1;
- (id)zoneIDs;
- (id)CKPropertiesDescription;
- (void).cxx_destruct;
- (id)description;
- (void)setCompletionHandler:(id)arg1;
- (id)completionHandler;

@end
