/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@class _NSUndoObject;

@interface _NSUndoObject : NSObject  {
    _NSUndoObject *next;
    _NSUndoObject *previous;
    id _target;
}


- (id)init;
- (void)invoke;
- (id)initWithTarget:(id)arg1;
- (bool)isBeginMark;
- (bool)isEndMark;
- (id)target;

@end
