/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSISRestrictedToZeroMarkerVariable : NSISVariable  {
}


- (bool)shouldBeMinimized;
- (id)markedConstraint;
- (int)valueRestriction;

@end
