/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/ToneLibrary.framework/ToneLibrary
 */

@class TLAccessQueue, NSMutableDictionary;

@interface TLAlertController : NSObject  {
    NSMutableDictionary *_alertsBySoundIDs;
    TLAccessQueue *_alertsBySoundIDsAccessQueue;
}

@property(readonly) BOOL _hasVibratorCapability;
@property(setter=_setAlertsBySoundIDs:,retain) NSMutableDictionary * _alertsBySoundIDs;
@property(setter=_setAlertsBySoundIDsAccessQueue:,retain) TLAccessQueue * _alertsBySoundIDsAccessQueue;

+ (id)sharedAlertController;

- (void)_systemSoundDidFinishPlaying:(unsigned long)arg1;
- (BOOL)stopAllAlerts;
- (unsigned long)_soundIDForAlert:(id)arg1;
- (BOOL)_stopAllAlerts;
- (void)_setAlertsBySoundIDs:(id)arg1;
- (void)_removeSoundID:(unsigned long)arg1 shouldStopSound:(BOOL)arg2 fireCompletionHandler:(BOOL)arg3;
- (id)_alertsBySoundIDs;
- (id)_alertsBySoundIDsAccessQueue;
- (void)_setAlertsBySoundIDsAccessQueue:(id)arg1;
- (void)_stopAlert:(id)arg1;
- (BOOL)_playAlert:(id)arg1 completionHandler:(id)arg2 targetQueue:(id)arg3;
- (BOOL)_hasVibratorCapability;
- (id)init;
- (void)dealloc;

@end
