/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/PhotoEditSupport.framework/PhotoEditSupport
 */

@class UIImage, CIImage;

@interface BLImage : NSObject <NSCopying> {
    UIImage *_UIImage;
    struct CGImage { } *_CGImage;
    CIImage *_CIImage;
    int _storageType;
    struct CGSize { 
        double width; 
        double height; 
    } _size;
    bool_isPlaceholder;
    int _askedImageType;
    int _obtainedImageType;
}

@property(readonly) int storageType;
@property(readonly) struct CGSize { double x1; double x2; } size;
@property(readonly) long long imageOrientation;
@property(readonly) double scale;
@property int askedImageType;
@property int obtainedImageType;
@property bool isPlaceholder;
@property(readonly) unsigned long long memoryUsage;

+ (id)abbreviatedDescriptionWithImageType:(int)arg1;
+ (id)descriptionWithImageType:(int)arg1;
+ (id)imageWithImage:(id)arg1;

- (void)setObtainedImageType:(int)arg1;
- (int)obtainedImageType;
- (void)setAskedImageType:(int)arg1;
- (int)askedImageType;
- (int)storageType;
- (unsigned long long)memoryUsage;
- (id)initWithFileAtURL:(id)arg1;
- (void)setIsPlaceholder:(bool)arg1;
- (bool)isPlaceholder;
- (id)init;
- (void)dealloc;
- (id)description;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (struct CGSize { double x1; double x2; })size;
- (double)scale;
- (id)UIImage;
- (id)CIImage;
- (long long)imageOrientation;
- (struct CGImage { }*)CGImage;

@end
