/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@class UILabel;

@interface FontSizeSliderCell : PSSliderTableCell  {
    UILabel *_smallSizeLabel;
    UILabel *_largeSizeLabel;
    UILabel *_veryLargeSizeLabel;
}


- (id)newControl;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;
- (void)dealloc;
- (void)layoutSubviews;

@end
