/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@class <KeychainSyncPasscodeFieldDelegate>, NSString, PSPasscodeField;

@interface PasscodeFieldCell : PSTableCell <UIKeyInput, PSPasscodeFieldDelegate> {
    PSPasscodeField *_passcodeField;
    bool_convertsNumeralsToASCII;
    bool_denyFirstResponder;
    <KeychainSyncPasscodeFieldDelegate> *_delegate;
}

@property <KeychainSyncPasscodeFieldDelegate> * delegate;
@property bool convertsNumeralsToASCII;
@property bool denyFirstResponder;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;
@property long long autocapitalizationType;
@property long long autocorrectionType;
@property long long spellCheckingType;
@property long long keyboardType;
@property long long keyboardAppearance;
@property long long returnKeyType;
@property bool enablesReturnKeyAutomatically;
@property(getter=isSecureTextEntry) bool secureTextEntry;


- (void)setDenyFirstResponder:(bool)arg1;
- (id)passcodeText;
- (void)setPasscodeText:(id)arg1;
- (void)_setSecureTextEntry:(bool)arg1;
- (bool)convertsNumeralsToASCII;
- (bool)denyFirstResponder;
- (void)setConvertsNumeralsToASCII:(bool)arg1;
- (void)passcodeField:(id)arg1 enteredPasscode:(id)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;
- (bool)becomeFirstResponder;
- (void)insertText:(id)arg1;
- (long long)keyboardType;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)dealloc;
- (void)deleteBackward;
- (bool)hasText;
- (void)layoutSubviews;

@end
