/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@class PSSpecifier, PrefsUILinkLabel;

@interface ProblemReportingController : PSListController  {
    PrefsUILinkLabel *_aboutDiagnosticsLinkLabel;
    PSSpecifier *_diagnosticDataGroupSpecifier;
    PSSpecifier *_filesystemMetadataSnapshotSpecifier;
    PSSpecifier *_appActivitySpecifier;
    PSSpecifier *_spinnerSpecifier;
}

@property(readonly) PSSpecifier * spinnerSpecifier;
@property(readonly) PSSpecifier * filesystemMetadataSnapshotSpecifier;
@property(readonly) PSSpecifier * appActivitySpecifier;

+ (bool)isProblemReportingEnabled;

- (id)spinnerSpecifier;
- (void)showAboutDiagnosticsSheet;
- (void)setProblemReportingEnabled:(bool)arg1;
- (bool)shouldEnableProblemReportingForCheckedSpecifier;
- (id)filesystemMetadataSnapshotSpecifier;
- (id)shouldShareAppActivityWithAppDevelopers;
- (void)setShouldShareAppActivityWithAppDevelopers:(id)arg1 specifier:(id)arg2;
- (void)snapshot:(id)arg1;
- (id)appActivitySpecifier;
- (void)diagnosticsDonePressed:(id)arg1;
- (id)specifiers;
- (void)dealloc;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;

@end
