/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSString, NSBundle, UIImage;

@interface PSLazyImagePromise : NSObject  {
    NSString *_imagePath;
    NSString *_imageName;
    NSBundle *_imageBundle;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _loadBlock;

    UIImage *_image;
    bool_imageLoaded;
}

@property(readonly) UIImage * image;
@property(getter=isImageLoaded,readonly) bool imageLoaded;

+ (id)imagePromiseWithLoadBlock:(id)arg1;
+ (id)imagePromiseWithImagePath:(id)arg1;
+ (id)imagePromiseWithImageNamed:(id)arg1 inBundle:(id)arg2;

- (bool)isImageLoaded;
- (void)loadImage;
- (id)image;
- (void)dealloc;

@end
