/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface PSWeakReference : NSObject <NSCopying> {
    id _location;
}

+ (id)weakReferenceWithObject:(id)arg1;

- (id)forwardingTargetForSelector:(SEL)arg1;
- (id)initWithObject:(id)arg1;
- (id)object;
- (bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
