/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/CertInfo.framework/CertInfo
 */

@class NSString, UIImage, UILabel, _CertInfoActionButton, _CertInfoGradientLabel;

@interface _CertInfoTrustSummaryHeaderCell : UITableViewCell  {
    UIImage *_certificateImage;
    UIImage *_notTrustedGradient;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    _CertInfoActionButton *_actionButton;
    _CertInfoGradientLabel *_trustedLabel;
    bool_trusted;
}

@property(readonly) _CertInfoActionButton * actionButton;
@property(readonly) double rowHeight;
@property(copy) NSString * trustTitle;
@property(copy) NSString * trustSubtitle;
@property(getter=isTrusted) bool trusted;


- (void)_layoutSubviewsWithActionButtonSize:(struct CGSize { double x1; double x2; })arg1;
- (id)actionButton;
- (void)setTrusted:(bool)arg1;
- (bool)isTrusted;
- (void)setActionButtonTitle:(id)arg1 destructive:(bool)arg2 animated:(bool)arg3;
- (id)_subtitleLabel;
- (id)_trustedLabel;
- (void)setTrustSubtitle:(id)arg1;
- (id)trustSubtitle;
- (void)setTrustTitle:(id)arg1;
- (id)trustTitle;
- (void)setExpired:(bool)arg1;
- (void).cxx_destruct;
- (id)_titleLabel;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (double)rowHeight;
- (void)layoutSubviews;

@end
