/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreMotion.framework/CoreMotion
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@interface CLNotifierData : NSObject  {
    void *_data;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _destructor;

}

@property void* data;
@property(copy) id destructor;


- (id)destructor;
- (void)setDestructor:(id)arg1;
- (id)initWithData:(void*)arg1 destructor:(id)arg2;
- (void*)data;
- (void)dealloc;
- (void).cxx_destruct;
- (void)setData:(void*)arg1;

@end
