/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
 */

@interface _CUIThemeFacetCacheKey : NSObject  {
    struct _renditionkeytoken { 
        unsigned short identifier; 
        unsigned short value; 
    } keyList[16];
    long long themeIndex;
    unsigned long long hashPrecalc;
}


- (id)initWithKeyList:(const struct _renditionkeytoken { unsigned short x1; unsigned short x2; }*)arg1 themeIndex:(long long)arg2;
- (unsigned long long)hash64;
- (bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
