/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
 */

@interface CUICommonAssetStorage : NSObject  {
    struct _carheader { unsigned int x1; unsigned int x2; unsigned int x3; unsigned int x4; unsigned int x5; BOOL x6[128]; BOOL x7[256]; unsigned char x8[16]; unsigned int x9; unsigned int x10; unsigned int x11; unsigned int x12; } *_header;
    struct _renditionkeyfmt { unsigned int x1; unsigned int x2; unsigned int x3; unsigned int x4[0]; } *_keyfmt;
    void *_imagedb;
    void *_colordb;
    void *_fontdb;
    void *_fontsizedb;
    void *_zcglyphdb;
    void *_zcbezeldb;
    void *_facetKeysdb;
    void *_elementDebugInfoDB;
    void *_partDebugInfoDB;
    BOOL _swap;
}

+ (void)initialize;

- (id)uuid;
- (id)displayNameForPartID:(int)arg1;
- (id)constantNameForPartID:(int)arg1;
- (id)displayNameForElementID:(int)arg1;
- (id)constantNameForElementID:(int)arg1;
- (id)_displayNameForIdentifier:(unsigned int)arg1 fromDebugTree:(void*)arg2;
- (id)_constantNameForIdentifier:(unsigned int)arg1 fromDebugTree:(void*)arg2;
- (id)_dataForIdentifier:(unsigned int)arg1 fromDebugTree:(void*)arg2;
- (float)fontSizeForFontSizeType:(id)arg1;
- (BOOL)getBaselineOffset:(float*)arg1 forFontType:(id)arg2;
- (BOOL)getFontName:(id*)arg1 baselineOffset:(float*)arg2 forFontType:(id)arg3;
- (BOOL)hasColorForName:(const char *)arg1;
- (BOOL)getColor:(struct _colordef { unsigned int x1; unsigned int x2; struct _rgbquad { unsigned int x_3_1_1 : 8; unsigned int x_3_1_2 : 8; unsigned int x_3_1_3 : 8; unsigned int x_3_1_4 : 8; } x3; }*)arg1 forName:(const char *)arg2;
- (id)zeroCodeBezelList;
- (id)allRenditionNames;
- (const struct _renditionkeytoken { unsigned short x1; unsigned short x2; }*)renditionKeyForName:(const char *)arg1 hotSpot:(struct CGPoint { float x1; float x2; }*)arg2;
- (id)allAssetKeys;
- (id)assetForKey:(id)arg1;
- (BOOL)assetExistsForKey:(id)arg1;
- (unsigned int)associatedChecksum;
- (unsigned int)renditionCount;
- (const char *)versionString;
- (id)keyFormatData;
- (int)keySemantics;
- (long)storageTimestamp;
- (unsigned int)schemaVersion;
- (unsigned int)coreuiVersion;
- (unsigned int)storageVersion;
- (const struct FontValue { BOOL x1[128]; float x2; }*)fontValueForFontType:(id)arg1;
- (id)_zeroCodeListFromTree:(const void*)arg1;
- (void)_swapZeroCodeInformation:(struct { unsigned int x1; unsigned int x2; }*)arg1;
- (struct _renditionkeytoken { unsigned short x1; unsigned short x2; })_swapRenditionKeyToken:(struct _renditionkeytoken { unsigned short x1; unsigned short x2; })arg1;
- (void)_swapRenditionKeyArray:(unsigned short*)arg1;
- (BOOL)swapped;
- (id)assetForKey:(const void*)arg1 withLength:(unsigned long)arg2;
- (int)maximumRenditionKeyTokenCount;
- (const struct _renditionkeyfmt { unsigned int x1; unsigned int x2; unsigned int x3; unsigned int x4[0]; }*)keyFormat;
- (long)_storagefileTimestamp;
- (void)_swapKeyFormat;
- (void)_bringHeaderInfoUpToDate;
- (void)_swapHeader;
- (void)_initDefaultHeader;
- (id)initWithPath:(id)arg1 forWriting:(BOOL)arg2;
- (id)zeroCodeGlyphList;
- (BOOL)usesCUISystemThemeRenditionKey;
- (unsigned int)colorSpaceID;
- (void)finalize;
- (void)dealloc;
- (id)initWithPath:(id)arg1;

@end
