/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
 */

@class CUIPSDGradient;

@interface CUIPSDGradientLayer : CUIPSDLayer  {
    CUIPSDGradient *_gradient;
}

@property(readonly) CUIPSDGradient * gradient;


- (id)initWithGradient:(id)arg1;
- (id)gradient;
- (void)dealloc;

@end
