/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@class ACAccount;

@interface AAEmailVettingRequest : AARequest  {
    ACAccount *_account;
}

@property(retain) ACAccount * account;


- (id)initWithURLString:(id)arg1 account:(id)arg2;
- (id)urlRequest;
- (id)initWithAccount:(id)arg1;
- (id)account;
- (void)setAccount:(id)arg1;
- (void).cxx_destruct;

@end
