/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@class NSString, NSDictionary;

@interface AAURLConfiguration : NSObject  {
    NSDictionary *_urlDictionary;
}

@property(readonly) NSString * accountCreationURL;
@property(readonly) NSString * updateAccountURL;
@property(readonly) NSString * registerURL;
@property(readonly) NSString * validateURL;
@property(readonly) NSString * accountCreationUIURL;
@property(readonly) NSString * updateAccountUIURL;
@property(readonly) NSString * signInURL;
@property(readonly) NSString * fetchAccountSettingsURL;
@property(readonly) NSString * authenticateURL;
@property(readonly) NSString * addEmailURL;
@property(readonly) NSString * initiateValidateEmailURL;
@property(readonly) NSString * completeValidateEmailURL;
@property(readonly) NSString * mobileMeOfferAlertURL;
@property(readonly) NSString * signingSessionCertURL;
@property(readonly) NSString * signingSessionURL;
@property(readonly) NSString * emailLookupURL;
@property(readonly) NSString * genericTermsURL;
@property(readonly) NSString * ckAppLoginURL;
@property(readonly) NSString * ckAppLoginCheckURL;
@property(readonly) NSString * fmipAuthenticate;
@property(readonly) NSString * iForgotUIURL;
@property(readonly) NSString * existingAppleIDTermsUIURL;
@property(readonly) NSString * finishProvisioningURL;
@property(readonly) NSString * syncMachineURL;
@property(readonly) NSString * loginDelegatesURL;

+ (id)urlConfiguration;
+ (void)reset;

- (id)iForgotUIURL;
- (id)syncMachineURL;
- (id)finishProvisioningURL;
- (id)ckAppLoginCheckURL;
- (id)validateURL;
- (id)registerURL;
- (id)updateAccountURL;
- (id)accountCreationURL;
- (id)fmipAuthenticate;
- (id)emailLookupURL;
- (id)mobileMeOfferAlertURL;
- (id)completeValidateEmailURL;
- (id)initiateValidateEmailURL;
- (id)fetchAccountSettingsURL;
- (id)signInURL;
- (id)addEmailURL;
- (id)updateAccountUIURL;
- (id)accountCreationUIURL;
- (id)ckAppLoginURL;
- (id)genericTermsURL;
- (id)loginDelegatesURL;
- (id)existingAppleIDTermsUIURL;
- (id)authenticateURL;
- (id)signingSessionURL;
- (id)signingSessionCertURL;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end
