/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
 */

@class NSString;

@interface ATVHighSecurityAccountVerifyCode : ATVHighSecurityAccountSendCode  {
    NSString *_hsaCode;
}

+ (Class)responseClass;

- (id)initWithAccount:(id)arg1 device:(id)arg2 hsaCode:(id)arg3;
- (id)urlString;
- (id)urlRequest;
- (void).cxx_destruct;

@end
