/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/MessageUI.framework/MessageUI
 */

@interface _MFFontToFontDescriptorTransformer : _MFValueTransformer  {
}


- (id)transformValue:(id)arg1 inverse:(BOOL)arg2;

@end
