/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/MessageUI.framework/MessageUI
 */

@interface _MFMailRecipientTextField : MFComposeTextField  {
}

+ (id)_initializeSafeCategoryFromValidationManager;
+ (void)_initializeSafeCategory;

- (id)customOverlayContainer;
- (void)paste:(id)arg1;
- (id)_previousKeyResponder;
- (void)_handleKeyUIEvent:(id)arg1;
- (id)accessibilityLabel;

@end
