/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/MessageUI.framework/MessageUI
 */

@class NSLock, NSArray;

@interface _MFMailAccountProxySource : NSObject  {
    NSLock *_lock;
    NSArray *_accountProxies;
    bool_registeredForNotifications;
    int _notifyToken;
}

+ (id)defaultInstance;

- (id)accountProxiesOriginatingBundleID:(id)arg1 sourceAccountManagement:(int)arg2;
- (void)_resetAccountsChanged:(bool)arg1;
- (void)_registerForNotifications_nts;
- (void)_deregisterForNotifications_nts;
- (id)init;
- (void)dealloc;
- (void)_applicationDidEnterBackground:(id)arg1;

@end
