/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/MessageUI.framework/MessageUI
 */

@class NSString;

@interface MFCalendarComposeRecipient : MFComposeRecipient  {
    NSString *_calAttendeeName;
    id _participant;
}

@property(retain) id participant;


- (void)setCalAttendeeName:(id)arg1;
- (id)initWithComposeRecipient:(id)arg1;
- (id)participant;
- (void)setParticipant:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (void)dealloc;
- (id)displayString;

@end
