/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/MessageUI.framework/MessageUI
 */

@class UIActivityIndicatorView, UIFont, UIView, UILabel, NSString, MFModernAtomIconView, MFModernAtomBackgroundView, UIColor;

@interface MFModernAtomView : UIDefaultKeyboardInput <MFModernAtomViewResembling> {
    MFModernAtomIconView *_badgeIconView;
    MFModernAtomIconView *_accessoryIconView;
    UIColor *_effectiveTintColor;
    unsigned long long _disabledPresentationOptions;
    UIView *_baselineView;
    MFModernAtomBackgroundView *_background;
    UIView *_compositingView;
    UIView *_titleLabelFillView;
    UILabel *_label;
    UIActivityIndicatorView *_activityIndicator;
    double _scalingFactor;
    bool_isPrimaryAddressAtom;
    bool_separatorHidden;
    bool_separatorIsLeftAligned;
    bool_selected;
    UIFont *_titleFont;
    unsigned long long _presentationOptions;
}

@property(copy) NSString * title;
@property(readonly) UILabel * titleLabel;
@property(getter=isSelected) bool selected;
@property(readonly) unsigned long long effectivePresentationOptions;
@property(readonly) UIColor * effectiveTintColor;
@property(readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } selectionFrame;
@property(readonly) MFModernAtomBackgroundView * backgroundView;
@property(readonly) MFModernAtomIconView * badgeIconView;
@property(readonly) MFModernAtomIconView * accessoryIconView;
@property(readonly) UIActivityIndicatorView * activityIndicator;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;
@property bool isPrimaryAddressAtom;
@property bool hidesVIPIndicator;
@property bool separatorHidden;
@property bool separatorIsLeftAligned;
@property double scale;
@property int separatorStyle;
@property unsigned long long presentationOptions;
@property(readonly) struct CGPoint { double x1; double x2; } baselinePoint;
@property(readonly) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } edgeInsets;
@property(retain) UIFont * titleFont;

+ (struct CGPoint { double x1; double x2; })defaultBaselinePoint;
+ (id)_badgeImagesForPresentationOptions:(unsigned long long)arg1 iconOrder:(const unsigned long long*)arg2 orderingLength:(unsigned long long)arg3 tintColor:(id)arg4 large:(bool)arg5 variant:(int)arg6;
+ (id)_SMSTintColor;
+ (id)_failureTintColor;
+ (id)_defaultLabelAttributesWithFont:(id)arg1;
+ (id)primaryAtomFont;
+ (id)_defaultLabelAttributes;
+ (id)_defaultTintColor;
+ (double)horizontalPadding;
+ (id)defaultFont;
+ (double)defaultHeight;

- (id)badgeIconView;
- (id)accessoryIconView;
- (unsigned long long)effectivePresentationOptions;
- (void)clearPresentationOption:(unsigned long long)arg1;
- (void)appendPresentationOption:(unsigned long long)arg1;
- (void)setPresentationOptions:(unsigned long long)arg1;
- (void)setSeparatorIsLeftAligned:(bool)arg1;
- (bool)separatorIsLeftAligned;
- (void)setSeparatorHidden:(bool)arg1;
- (void)setHidesVIPIndicator:(bool)arg1;
- (bool)hidesVIPIndicator;
- (void)setIsPrimaryAddressAtom:(bool)arg1;
- (void)performBuildInAnimationFromTextColor:(id)arg1 withDuration:(double)arg2;
- (double)preferredWidth;
- (double)_leftInset;
- (double)_rightInset;
- (bool)separatorHidden;
- (void)_updateFontIfNecessary;
- (double)_rightPadding;
- (double)_leftPadding;
- (double)preferredWidthWithSizeConstraints:(struct CGSize { double x1; double x2; })arg1;
- (void)_setPresentationOption:(unsigned long long)arg1 enabled:(bool)arg2;
- (void)_updateCompositingFilters;
- (void)setSelected:(bool)arg1 animated:(bool)arg2 style:(unsigned long long)arg3;
- (void)_updateActivityIndicator;
- (bool)isPrimaryAddressAtom;
- (int)_preferredIconVariant;
- (unsigned long long)presentationOptions;
- (void)_setEffectiveTintColor:(id)arg1;
- (id)effectiveTintColor;
- (void)setTitleFont:(id)arg1;
- (void)_invalidatePresentationOptions;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 presentationOptions:(unsigned long long)arg2 separatorStyle:(int)arg3;
- (void)setTitle:(id)arg1;
- (id)title;
- (void)setScale:(double)arg1;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })edgeInsets;
- (void)dealloc;
- (id)description;
- (double)scale;
- (id)activityIndicator;
- (id)titleFont;
- (struct CGPoint { double x1; double x2; })baselinePoint;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })selectionFrame;
- (id)viewForBaselineLayout;
- (int)separatorStyle;
- (id)backgroundView;
- (void)setSelected:(bool)arg1;
- (bool)isSelected;
- (void)setSelected:(bool)arg1 animated:(bool)arg2;
- (void)setSeparatorStyle:(int)arg1;
- (id)titleLabel;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;
- (void)tintColorDidChange;
- (void)layoutSubviews;

@end
