/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSObject<OS_dispatch_queue>, BBServerConnection;

@interface BBSettingsGateway : NSObject <BBSettingsGatewayRemoteInterface, BBXPCConnectionDelegate, XPCProxyTarget> {

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _overrideStatusChangeHandler;


  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _activeOverrideTypesChangedHandler;

    BBServerConnection *_connection;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (void)initialize;

- (void)getBehaviorOverridesEnabledWithCompletion:(id)arg1;
- (void)getBehaviorOverridesEffectiveWhileUnlockedWithCompletion:(id)arg1;
- (void)setBehaviorOverridesEffectiveWhileUnlocked:(BOOL)arg1;
- (void)setSectionInfo:(id)arg1 forSectionID:(id)arg2;
- (void)setOrderedSectionIDs:(id)arg1;
- (void)setSectionOrderRule:(int)arg1;
- (void)getPrivilegedSenderAddressBookGroupRecordIDAndNameWithCompletion:(id)arg1;
- (void)setSectionInfo:(id)arg1 forSectionID:(id)arg2 inCategory:(int)arg3;
- (void)setOrderedSectionIDs:(id)arg1 forCategory:(int)arg2;
- (void)activeBehaviorOverrideTypesChanged:(unsigned int)arg1;
- (void)behaviorOverrideStatusChanged:(int)arg1;
- (void)getPrivilegedSenderTypesWithCompletion:(id)arg1;
- (void)getSectionOrderRuleWithCompletion:(id)arg1;
- (void)connection:(id)arg1 connectionStateDidChange:(BOOL)arg2;
- (void)getSectionInfoForCategory:(int)arg1 withCompletion:(id)arg2;
- (void)getSectionInfoWithCompletion:(id)arg1;
- (void)getBehaviorOverridesWithCompletion:(id)arg1;
- (void)setBehaviorOverrideStatusChangeHandler:(id)arg1;
- (void)setActiveBehaviorOverrideTypesChangeHandler:(id)arg1;
- (void)setPrivilegedSenderAddressBookGroupRecordID:(int)arg1 name:(id)arg2;
- (void)setPrivilegedSenderTypes:(unsigned int)arg1;
- (void)setBehaviorOverridesEnabled:(BOOL)arg1;
- (void)setBehaviorOverrideStatus:(int)arg1;
- (void)setBehaviorOverrides:(id)arg1;
- (id)proxy:(id)arg1 detailedSignatureForSelector:(SEL)arg2;
- (id)init;
- (void)invalidate;
- (void)dealloc;
- (id)initWithQueue:(id)arg1;

@end
