/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/Photos.framework/Photos
 */

@class NSString, NSManagedObjectID;

@interface PHObjectDeleteRequest : NSObject <PHDeleteChangeRequest> {
    NSString *_uuid;
    NSManagedObjectID *_objectID;
    bool_entitled;
    NSString *_clientName;
}

@property(readonly) NSString * managedEntityName;
@property(readonly) NSString * uuid;
@property(readonly) NSManagedObjectID * objectID;
@property(getter=isEntitled,readonly) bool entitled;
@property(readonly) NSString * clientName;

+ (id)deleteRequestForObject:(id)arg1;

- (id)initForNewObject;
- (void)encodeToXPCDict:(id)arg1;
- (id)initWithXPCDict:(id)arg1 entitled:(bool)arg2 clientName:(id)arg3 clientBundleID:(id)arg4;
- (id)initWithUUID:(id)arg1 objectID:(id)arg2;
- (bool)isEntitled;
- (void)deleteManagedObject:(id)arg1 photoLibrary:(id)arg2;
- (bool)validateForDeleteManagedObject:(id)arg1 error:(id*)arg2;
- (id)managedEntityName;
- (id)objectID;
- (id)uuid;
- (id)clientName;
- (id)init;
- (void).cxx_destruct;

@end
