/* Generated by RuntimeBrowser.
 */

@protocol _MKInfoCardController <NSObject>

@required

+ (double)headerHeightInMinimalMode;

- (double)currentHeaderMinimalModeInterpolationFactor;
- (void)hideTitle:(bool)arg1;
- (<UIScrollViewDelegate> *)scrollViewDelegate;
- (void)setCurrentHeaderMinimalModeInterpolationFactor:(double)arg1;
- (void)setScrollViewDelegate:(id <UIScrollViewDelegate>)arg1;

@end
