/* Generated by RuntimeBrowser.
 */

@protocol PXPeopleProgressDatasource <NSObject>

@required

- (void)asyncPeopleScanningProgress:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, double, unsigned long long, void*
- (bool)featureUnlockUserDefault;
- (unsigned long long)homeMembersCount;
- (void)loadQueryData;
- (unsigned long long)pendingAssetCount;
- (unsigned long long)plusMembersCount;
- (unsigned long long)processedAssetCount;
- (void)setFeatureUnlockUserDefault:(bool)arg1;
- (double)syncPeopleScanningProgress;
- (unsigned long long)totalAssetCount;
- (unsigned long long)verifiedCount;

@end
