/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/TelephonyUtilities.framework/TelephonyUtilities
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class TUCall;

@interface TUAVConferenceConnection : NSObject  {
    bool_receivedDidStart;
    int _socketDescriptor;
    TUCall *_call;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _didStartHandler;


  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _didStopHandler;

}

@property(readonly) int socketDescriptor;
@property(getter=isMuted) bool muted;
@property(retain) TUCall * call;
@property(copy) id didStartHandler;
@property(copy) id didStopHandler;
@property bool receivedDidStart;

+ (id)conferenceConnectionWithCall:(id)arg1;

- (id)call;
- (void)setMuted:(bool)arg1;
- (int)socketDescriptor;
- (void)setReceivedDidStart:(bool)arg1;
- (void)setCall:(id)arg1;
- (id)didStopHandler;
- (bool)receivedDidStart;
- (id)didStartHandler;
- (void)setDidStopHandler:(id)arg1;
- (void)setDidStartHandler:(id)arg1;
- (bool)isMuted;
- (void)dealloc;
- (id)description;

@end
