/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/CloudDocs.framework/CloudDocs
 */

@class NSArray, NSNumber, NSURL;

@interface BRQueryStitch : NSObject  {
    NSArray *_queries;
    NSNumber *_objid;
    BOOL _kind;
    NSURL *_fromURL;
    NSURL *_url;
}

@property(retain) NSURL * fromURL;
@property(retain) NSArray * queries;


- (id)queries;
- (void)setFromURL:(id)arg1;
- (id)fromURL;
- (void)setQueries:(id)arg1;
- (id)initWithURL:(id)arg1 objid:(id)arg2 kind:(BOOL)arg3;
- (void)_deletionDone;
- (void)_renameDone;
- (void)_creationDone;
- (void)done;
- (void)dealloc;
- (id)description;

@end
