/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities
 */

@class NSMutableArray;

@interface AXSettingsObjectDestructionHelper : NSObject  {
    void *_listenerAddress;
    NSMutableArray *_selectorKeys;
}


- (void)addSelectorKey:(SEL)arg1;
- (id)initWithListenerAddress:(void*)arg1;
- (void)dealloc;

@end
