/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSString;

@interface AXSpringBoardActionHandlerHolder : NSObject  {

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _handler;

    int _type;
    NSString *_identifier;
}

@property(copy) id handler;
@property int type;
@property(copy) NSString * identifier;


- (void)setType:(int)arg1;
- (void)setHandler:(id)arg1;
- (void)dealloc;
- (void)setIdentifier:(id)arg1;
- (id)identifier;
- (id)handler;
- (int)type;

@end
