/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSString;

@interface DAUserNotificationInfo : NSObject  {

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _handler;

    NSString *_groupIdentifier;
}

@property(copy) NSString * groupIdentifier;


- (void)setHandler:(id)arg1;
- (void)dealloc;
- (id)handler;
- (void)setGroupIdentifier:(id)arg1;
- (id)groupIdentifier;

@end
