/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class <DADataclassLockWatcher>;

@interface DAWaiterWrapper : NSObject  {
    <DADataclassLockWatcher> *_waiter;
    long long _dataclasses;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _completionHandler;

    int _waiterNum;
}

@property(retain) <DADataclassLockWatcher> * waiter;
@property(copy) id completionHandler;
@property long long dataclasses;
@property(readonly) int waiterNum;


- (int)waiterNum;
- (void)setDataclasses:(long long)arg1;
- (long long)dataclasses;
- (void)setWaiter:(id)arg1;
- (id)waiter;
- (id)init;
- (void).cxx_destruct;
- (id)description;
- (void)setCompletionHandler:(id)arg1;
- (id)completionHandler;

@end
