/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@class NSString;

@interface MPFeedbackCommand : MPRemoteCommand  {
    NSString *_localizedShortTitle;
    bool_active;
    NSString *_localizedTitle;
}

@property(getter=isActive) bool active;
@property(copy) NSString * localizedTitle;


- (void)setLocalizedTitle:(id)arg1;
- (void)setLocalizedShortTitle:(id)arg1;
- (id)localizedShortTitle;
- (id)_mediaRemoteCommandInfoOptions;
- (id)keyPathsForValuesTriggeringCommandsChanged;
- (bool)isActive;
- (void).cxx_destruct;
- (void)setActive:(bool)arg1;
- (id)localizedTitle;

@end
