/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@class AVPlayerItemAccessLogEvent, NSDate, NSString;

@interface MPMovieAccessLogEvent : NSObject <NSCopying> {
    AVPlayerItemAccessLogEvent *_event;
}

@property(readonly) unsigned int numberOfSegmentsDownloaded;
@property(readonly) NSDate * playbackStartDate;
@property(readonly) NSString * URI;
@property(readonly) NSString * serverAddress;
@property(readonly) unsigned int numberOfServerAddressChanges;
@property(readonly) NSString * playbackSessionID;
@property(readonly) double playbackStartOffset;
@property(readonly) double segmentsDownloadedDuration;
@property(readonly) double durationWatched;
@property(readonly) int numberOfStalls;
@property(readonly) long long numberOfBytesTransferred;
@property(readonly) double observedBitrate;
@property(readonly) double indicatedBitrate;
@property(readonly) int numberOfDroppedVideoFrames;


- (int)numberOfDroppedVideoFrames;
- (double)indicatedBitrate;
- (double)observedBitrate;
- (long long)numberOfBytesTransferred;
- (int)numberOfStalls;
- (double)durationWatched;
- (double)segmentsDownloadedDuration;
- (double)playbackStartOffset;
- (id)playbackSessionID;
- (unsigned int)numberOfServerAddressChanges;
- (id)serverAddress;
- (id)URI;
- (id)playbackStartDate;
- (id)_initWithAVItemAccessLogEvent:(id)arg1;
- (unsigned int)numberOfSegmentsDownloaded;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
