/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Swift/libswiftCore.dylib
 */

@interface _TtCs19_NSContiguousString : _TtCs20_SwiftNativeNSString {
    void _core;
}

- (unsigned short*)_fastCharacterContents;
- (unsigned short)characterAtIndex:(long long)arg1;
- (id)copy;
- (void)getCharacters:(unsigned short*)arg1 range:(struct { long long x1; long long x2; })arg2;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (long long)length;
- (id)substringFromIndex:(long long)arg1;
- (id)substringToIndex:(long long)arg1;
- (id)substringWithRange:(struct { long long x1; long long x2; })arg1;

@end
