/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PersistentConnection.framework/PersistentConnection
 */

@interface PCPersistentIdentifiers : NSObject  {
}

+ (int)pidFromMatchingIdentifer:(id)arg1;
+ (id)processNameAndPidIdentifier;
+ (id)_processNamePrefix;
+ (id)processNamePidAndStringIdentifier:(id)arg1;
+ (unsigned long long)hostUniqueIdentifier;


@end
