/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

@interface ML3AllCompoundPredicate : ML3CompoundPredicate  {
}

+ (id)predicateByMergingContainmentPredicatesAllCompoundPredicate:(id)arg1;
+ (id)predicateByFlatteningAllCompoundPredicate:(id)arg1;

- (id)compoundOperatorJoiner;
- (id)predicateOptimizedForEntityClass:(Class)arg1;

@end
