/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@interface ML3DatabaseFunctionBlock : ML3DatabaseFunction  {

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _block;

}

@property(copy) id block;


- (BOOL)registerWithConnection:(id)arg1;
- (void)setBlock:(id)arg1;
- (void).cxx_destruct;
- (id)block;

@end
