/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
 */

@class NSData, NSString, NSArray, MLMovieProperties, NSMutableDictionary, NSDictionary, MLContentRating;

@interface MLTrackImport : NSObject <NSCopying> {
    NSData *_artworkData;
    NSString *_assetFilePath;
    NSArray *_chapters;
    NSMutableDictionary *_properties;
    bool_shouldAddToPurchasedPlaylist;
    bool_assignArtworkCacheIDFromAlbum;
}

@property(copy) NSData * artworkData;
@property(copy) NSString * assetFilePath;
@property(copy) NSArray * chapters;
@property(copy) MLContentRating * contentRating;
@property unsigned int mediaType;
@property(copy) MLMovieProperties * movieProperties;
@property bool shouldAddToPurchasedPlaylist;
@property bool assignArtworkCacheIDFromAlbum;
@property(copy,readonly) NSDictionary * entityProperties;

+ (void)initialize;

- (void)setArtworkData:(id)arg1;
- (void)setContentRating:(id)arg1;
- (id)contentRating;
- (void)setShouldAddToPurchasedPlaylist:(bool)arg1;
- (bool)shouldAddToPurchasedPlaylist;
- (id)chapters;
- (void)setAssignArtworkCacheIDFromAlbum:(bool)arg1;
- (bool)assignArtworkCacheIDFromAlbum;
- (void)setAssetFilePath:(id)arg1;
- (id)assetFilePath;
- (id)artworkData;
- (void)normalizeEntityProperties;
- (id)copyEntityProperties;
- (void)setMovieProperties:(id)arg1;
- (id)movieProperties;
- (id)entityProperties;
- (id)valueForEntityProperty:(id)arg1;
- (void)_addSortStrings;
- (void)setValue:(id)arg1 forEntityProperty:(id)arg2;
- (void)setChapters:(id)arg1;
- (void)setMediaType:(unsigned int)arg1;
- (unsigned int)mediaType;
- (id)init;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
