/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@class NSData, NSString;

@interface CKEncryptedData : NSObject <CKRecordValue, NSCopying, NSSecureCoding> {
    NSData *_data;
    NSData *_encryptedData;
}

@property(copy) NSData * data;
@property(copy) NSData * encryptedData;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;

+ (bool)supportsSecureCoding;

- (void)setEncryptedData:(id)arg1;
- (id)initWithEncryptedData:(id)arg1;
- (id)encryptedData;
- (id)CKPropertiesDescription;
- (id)init;
- (bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)data;
- (id)initWithData:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void).cxx_destruct;
- (id)description;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)setData:(id)arg1;
- (id)_prettyDictionaryRepresentation;

@end
