/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/CloudKit.framework/CloudKit
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSMutableArray, CKCommentCursor, CKCommentQuery;

@interface CKFetchShareCommentsOperation : CKOperation  {
    CKCommentQuery *_query;
    CKCommentCursor *_cursor;
    unsigned long long _resultsLimit;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _fetchShareCommentsCompletionBlock;

    NSMutableArray *_resultComments;
    CKCommentCursor *_nextCursor;
}

@property(copy) CKCommentQuery * query;
@property(copy) CKCommentCursor * cursor;
@property unsigned long long resultsLimit;
@property(copy) id fetchShareCommentsCompletionBlock;
@property(retain) NSMutableArray * resultComments;
@property(retain) CKCommentCursor * nextCursor;


- (id)initWithCursor:(id)arg1;
- (id)nextCursor;
- (id)fetchShareCommentsCompletionBlock;
- (void)_handleCompletionCallback:(id)arg1;
- (void)setNextCursor:(id)arg1;
- (void)setResultComments:(id)arg1;
- (id)resultComments;
- (void)setFetchShareCommentsCompletionBlock:(id)arg1;
- (id)initWithShareCommentQuery:(id)arg1;
- (void)setResultsLimit:(unsigned long long)arg1;
- (unsigned long long)resultsLimit;
- (void)_handleProgressCallback:(id)arg1;
- (void)performCKOperation;
- (bool)CKOperationShouldRun:(id*)arg1;
- (void)_finishOnCallbackQueueWithError:(id)arg1;
- (void)fillOutOperationInfo:(id)arg1;
- (id)cursor;
- (id)query;
- (void).cxx_destruct;
- (void)setCursor:(id)arg1;
- (void)setQuery:(id)arg1;

@end
