/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@class NSArray, CKShareID;

@interface CKLikeItemsOperationInfo : CKOperationInfo  {
    NSArray *_itemIDsToLike;
    NSArray *_itemIDsToUnlike;
    CKShareID *_shareID;
}

@property(retain) NSArray * itemIDsToLike;
@property(retain) NSArray * itemIDsToUnlike;
@property(retain) CKShareID * shareID;

+ (bool)supportsSecureCoding;

- (id)itemIDsToUnlike;
- (id)itemIDsToLike;
- (void)setItemIDsToUnlike:(id)arg1;
- (void)setItemIDsToLike:(id)arg1;
- (void)setShareID:(id)arg1;
- (id)shareID;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void).cxx_destruct;

@end
