/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@class NSString;

@interface CKOperationInfo : NSObject <NSSecureCoding> {
    bool_allowsCellularAccess;
    NSString *_operationID;
    NSString *_parentSectionID;
    long long _usesBackgroundSessionOverride;
    long long _qualityOfService;
    NSString *_sourceApplicationBundleIdentifier;
    NSString *_sourceApplicationSecondaryIdentifier;
    id _parentOperation;
}

@property(retain) NSString * operationID;
@property(retain) NSString * parentSectionID;
@property long long usesBackgroundSessionOverride;
@property bool allowsCellularAccess;
@property long long qualityOfService;
@property(retain) NSString * sourceApplicationBundleIdentifier;
@property(retain) NSString * sourceApplicationSecondaryIdentifier;
@property id parentOperation;

+ (bool)supportsSecureCoding;

- (void)setParentSectionID:(id)arg1;
- (id)sourceApplicationSecondaryIdentifier;
- (void)setUsesBackgroundSessionOverride:(long long)arg1;
- (long long)usesBackgroundSessionOverride;
- (void)setOperationID:(id)arg1;
- (id)parentSectionID;
- (void)setSourceApplicationSecondaryIdentifier:(id)arg1;
- (id)operationID;
- (id)parentOperation;
- (void)setParentOperation:(id)arg1;
- (id)init;
- (id)sourceApplicationBundleIdentifier;
- (void)setSourceApplicationBundleIdentifier:(id)arg1;
- (void)setAllowsCellularAccess:(bool)arg1;
- (bool)allowsCellularAccess;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void).cxx_destruct;
- (void)setQualityOfService:(long long)arg1;
- (long long)qualityOfService;

@end
