/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/CloudKit.framework/CloudKit
 */

@class NSArray, NSDictionary;

@interface CKPublishAssetsOperationInfo : CKDatabaseOperationInfo <NSSecureCoding> {
    NSArray *_recordIDs;
    NSDictionary *_fileNamesByAssetFieldNames;
    unsigned long long _requestedTTL;
    unsigned long long _URLOptions;
}

@property(retain) NSArray * recordIDs;
@property(retain) NSDictionary * fileNamesByAssetFieldNames;
@property unsigned long long requestedTTL;
@property unsigned long long URLOptions;

+ (bool)supportsSecureCoding;

- (void)setURLOptions:(unsigned long long)arg1;
- (unsigned long long)URLOptions;
- (void)setRequestedTTL:(unsigned long long)arg1;
- (unsigned long long)requestedTTL;
- (void)setFileNamesByAssetFieldNames:(id)arg1;
- (id)fileNamesByAssetFieldNames;
- (void)setRecordIDs:(id)arg1;
- (id)recordIDs;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void).cxx_destruct;

@end
