/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/CloudPhotoLibrary.framework/CloudPhotoLibrary
 */

@class NSString, CPLPlatformObject, NSObject<OS_dispatch_queue>, NSMutableArray;

@interface CPLEngineResourceDownloadQueue : CPLEngineStorage <CPLAbstractObject> {
    NSObject<OS_dispatch_queue> *_downloadQueue;
    NSMutableArray *_highPriorityTasksQueue;
    NSMutableArray *_highPriorityActiveTasks;
    NSMutableArray *_lowPriorityTasksQueue;
    NSMutableArray *_lowPriorityActiveTasks;
    NSMutableArray *_backgroundActiveTasks;
    unsigned long long _totalClientRequests;
    unsigned long long _totalClientRequestErrors;
    unsigned long long _totalPutInBackground;
    bool_shouldRequestABackgroundDownloadSyncPhase;
}

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;
@property(readonly) CPLPlatformObject * platformObject;


- (id)dequeueBackgroundDownloadTaskForResourceType:(unsigned long long)arg1 withCompletionHandler:(id)arg2;
- (id)downloadTaskForLocalResource:(id)arg1 clientBundleID:(id)arg2 highPriority:(bool)arg3 didStartHandler:(id)arg4 progressHandler:(id)arg5 completionHandler:(id)arg6;
- (unsigned long long)countOfQueuedDownloadTasks;
- (id)enumeratorForDownloadedResources;
- (bool)resetDequeuedBackgroundDownloadTasksWithError:(id*)arg1;
- (bool)reenqueueBackgroundDownloadTaskForResource:(id)arg1 taskIdentifier:(unsigned long long)arg2 bumpRetryCount:(bool)arg3 didDiscard:(bool*)arg4 error:(id*)arg5;
- (bool)markBackgroundDownloadTaskForResourceAsSuceeded:(id)arg1 taskIdentifier:(unsigned long long)arg2 error:(id*)arg3;
- (void)_processQueuedDownloadTasks;
- (bool)_hasActiveForegroundTasks;
- (void)_reallyDispatchDownloadTask:(id)arg1;
- (void)_finishDownloadTask:(id)arg1 error:(id)arg2;
- (bool)_cancelDownloadTask:(id)arg1;
- (void)_enqueueDownloadTask:(id)arg1;
- (bool)removeBackgroundDownloadTaskForResource:(id)arg1 taskIdentifier:(unsigned long long)arg2 error:(id*)arg3;
- (bool)dequeueNextBackgroundDownloadTask:(id*)arg1 resourceType:(unsigned long long)arg2 taskIdentifier:(unsigned long long*)arg3 error:(id*)arg4;
- (bool)enqueueBackgroundDownloadTaskForResource:(id)arg1 taskIdentifier:(unsigned long long)arg2 error:(id*)arg3;
- (id)_realDownloadTaskForCloudResource:(id)arg1 clientBundleID:(id)arg2 didStartHandler:(id)arg3 progressHandler:(id)arg4 completionHandler:(id)arg5;
- (id)_resourceStorageCopyTaskForResource:(id)arg1 clientBundleID:(id)arg2 didStartHandler:(id)arg3 progressHandler:(id)arg4 completionHandler:(id)arg5;
- (void)_downloadTaskDidSucceed:(id)arg1 completionHandler:(id)arg2;
- (void)_downloadTaskDidFail:(id)arg1 withError:(id)arg2 completionHandler:(id)arg3;
- (id)_downloadTaskForLocalResource:(id)arg1 clientBundleID:(id)arg2 highPriority:(bool)arg3 background:(bool)arg4 backgroundTaskIdentifier:(unsigned long long)arg5 didStartHandler:(id)arg6 progressHandler:(id)arg7 completionHandler:(id)arg8;
- (id)_failedTaskWithCompletionHandler:(id)arg1 error:(id)arg2;
- (bool)removeAllBackgroundDownloadTasksForItemWithIdentifier:(id)arg1 error:(id*)arg2;
- (bool)resetWithError:(id*)arg1;
- (id)initWithEngineStore:(id)arg1 name:(id)arg2;
- (void).cxx_destruct;

@end
