/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class <PLCameraEffectsRendererDelegate>, PLEffectsGridView, PLVideoPreviewView, NSObject<OS_dispatch_queue>, CIContext, PLEffectsFullsizeView, EAGLContext;

@interface PLCameraEffectsRenderer : NSObject  {
    EAGLContext *_eaglContext;
    CIContext *_ciContext;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    BOOL _isShowingGrid;
    BOOL _gridTransitionInFlight;
    BOOL _gridTransitionIsAnimated;
    <PLCameraEffectsRendererDelegate> *_delegate;
    double _lastReportedFrameDropTime;
    unsigned int _totalFramesSinceLastReportedFrameDrop;
    unsigned int _droppedFramesSinceLastReportedFrameDrop;
    BOOL __atomicPreviewStartedNotificationNeeded;
    BOOL _atomicMirrorFilterRendering;
    BOOL _atomicBlackAndWhite;
    BOOL __previewLayerEnabled;
    BOOL __inBackground;
    PLEffectsFullsizeView *__renderEffectsFullsizeView;
    PLEffectsGridView *__renderGridView;
    PLVideoPreviewView *_atomicVideoPreviewView;
    unsigned int _atomicFilterIndex;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id __atomicPreviewStartedBlock;

}

@property(retain) PLVideoPreviewView * videoPreviewView;
@property unsigned int filterIndex;
@property(getter=isShowingGrid) BOOL showGrid;
@property BOOL mirrorFilterRendering;
@property(getter=isBlackAndWhite) BOOL blackAndWhite;
@property <PLCameraEffectsRendererDelegate> * delegate;
@property(retain) PLVideoPreviewView * atomicVideoPreviewView;
@property unsigned int atomicFilterIndex;
@property(setter=_setRenderEffectsFullsizeView:,retain) PLEffectsFullsizeView * _renderEffectsFullsizeView;
@property(setter=_setRenderGridView:,retain) PLEffectsGridView * _renderGridView;
@property(setter=_setPreviewStartedBlock:,copy) id _previewStartedBlock;
@property(setter=_setPreviewStartedNotificationNeeded:) BOOL _previewStartedNotificationNeeded;
@property(setter=_setPreviewLayerEnabled:) BOOL _previewLayerEnabled;
@property(getter=_isInBackground,setter=_setInBackground:) BOOL _inBackground;


- (BOOL)_previewLayerEnabled;
- (BOOL)mirrorFilterRendering;
- (void)setShowGrid:(BOOL)arg1;
- (void)_notifyOfRenderIfNecessary;
- (void)didDropSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg1;
- (void)renderWithSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg1;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })_zoomedFrameForRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1 fromFullFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg2 toZoomFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg3;
- (void)_animateLayer:(id)arg1 startFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg2 endFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg3 viewTransform:(struct CGAffineTransform { float x1; float x2; float x3; float x4; float x5; float x6; })arg4 animationDuration:(double)arg5 animationTimingFunction:(id)arg6 animationDelegate:(id)arg7;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })_frameToZoomFromFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1 toFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg2 withinFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg3;
- (void)_animateGridLayerZoomToGrid:(BOOL)arg1;
- (void)_animateToGrid:(BOOL)arg1 layer:(id)arg2 fadeOutLayer:(id)arg3 startFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg4 endFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg5 completion:(id)arg6;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })_gridFrameForCurrentFilters;
- (id)_animatedLayerForView:(id)arg1;
- (void)_transitionFromGrid:(id)arg1;
- (void)_transitionToGrid:(id)arg1;
- (void)_setGridTransitionIsInFlight:(BOOL)arg1;
- (BOOL)_gridTransitionInFlight;
- (id)_previewStartedBlock;
- (void)_handlePreviewStartedFiltered:(BOOL)arg1;
- (BOOL)_previewStartedNotificationNeeded;
- (void)_setPreviewStartedNotificationNeeded:(BOOL)arg1;
- (void)_reportStatsForFrameDrops;
- (void)_updateStatsForFrameWasDropped:(BOOL)arg1;
- (void)_renderWithSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg1;
- (void)_setRenderGridView:(id)arg1;
- (void)_setRenderEffectsFullsizeView:(id)arg1;
- (id)_setupEffectsFullsizeView;
- (id)_setupEffectsGridView;
- (void)setAtomicVideoPreviewView:(id)arg1;
- (void)_destroyEffectsGridView;
- (void)_destroyEffectsFullsizeView;
- (id)atomicVideoPreviewView;
- (void)_runOnMainThreadImmediatelyIfPossibleWithBlock:(id)arg1;
- (void)_setPreviewStartedBlock:(id)arg1;
- (void)_forceResetToFilteredRendering:(BOOL)arg1;
- (void)_updateFilterIndexOnEffectsFullsizeView;
- (void)setAtomicFilterIndex:(unsigned int)arg1;
- (unsigned int)atomicFilterIndex;
- (void)_setupEffectsView:(id)arg1;
- (id)_renderGridView;
- (id)_renderEffectsFullsizeView;
- (BOOL)_isInBackground;
- (void)_tearDownEffectsView:(id)arg1;
- (void)_previewStarted:(id)arg1;
- (void)_setVideoDataOutputEnabled:(BOOL)arg1;
- (void)_setPreviewLayerEnabled:(BOOL)arg1;
- (void)_createContextIfNecessary;
- (void)_setInBackground:(BOOL)arg1;
- (void)setFilterIndex:(unsigned int)arg1;
- (unsigned int)filterIndex;
- (BOOL)isBlackAndWhite;
- (void)setShowGrid:(BOOL)arg1 animated:(BOOL)arg2;
- (BOOL)isShowingGrid;
- (id)videoPreviewView;
- (void)setVideoPreviewView:(id)arg1;
- (void)setFilterIndex:(unsigned int)arg1 forceStateChange:(BOOL)arg2 renderNotifyBlock:(id)arg3;
- (void)setMirrorFilterRendering:(BOOL)arg1;
- (void)_deviceStarted:(id)arg1;
- (id)initWithDispatchQueue:(id)arg1;
- (void)setBlackAndWhite:(BOOL)arg1;
- (id)init;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (id)delegate;
- (void)_applicationWillEnterForeground:(id)arg1;
- (void)_applicationDidEnterBackground:(id)arg1;
- (void)_applicationWillResignActive:(id)arg1;

@end
