/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

@interface PLImageScrollView : UIScrollView  {
    BOOL _adjustZoomScaleAfterRotation;
}

@property BOOL adjustZoomScaleAfterRotation;


- (BOOL)adjustZoomScaleAfterRotation;
- (void)setAdjustZoomScaleAfterRotation:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)setFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)willAnimateRotationToInterfaceOrientation:(id)arg1;
- (void)_centerContentIfNecessary;

@end
