/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

@class PLImageLoadingQueue, PLImageCache, NSMutableDictionary;

@interface PLLibraryImageDataProvider : NSObject  {
    PLImageCache *_imageCache;
    PLImageLoadingQueue *_imageLoadingQueue;
    NSMutableDictionary *_imageSources;
}


- (void)invalidateCachedImagesForAsset:(id)arg1 format:(int)arg2;
- (void)invalidateCachedImagesForAsset:(id)arg1;
- (void)cancelLoadForAsset:(id)arg1 format:(int)arg2;
- (void)cancelLoadForAsset:(id)arg1;
- (id)loadImageSynchronously:(bool)arg1 forAsset:(id)arg2 format:(int)arg3 priority:(int)arg4 completion:(id)arg5;
- (id)_imageSourceForFormat:(int)arg1;
- (void)resumeLoading;
- (void)pauseLoading;
- (id)init;
- (void)dealloc;

@end
