/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/PhotoLibrary.framework/PhotoLibrary
 */

@class UILabel, UIButton, UIView;

@interface PLPhotoPostCommentCell : UITableViewCell  {
    UILabel *_contentLabel;
    UIButton *_addCommentButton;
    UIView *_styledSeparatorView;
}

@property(retain,readonly) UIButton * addCommentButton;
@property(retain,readonly) UILabel * contentLabel;
@property(retain,readonly) UIView * styledSeparatorView;

+ (double)heightForWidth:(double)arg1;

- (id)contentLabel;
- (id)styledSeparatorView;
- (void)setupContent;
- (id)addCommentButton;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;

@end
