/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@class LSApplicationWorkspace;

@interface GKApplicationWorkspace : NSObject  {
    LSApplicationWorkspace *_lsWorkspace;
}

@property(retain) LSApplicationWorkspace * lsWorkspace;

+ (id)defaultWorkspace;

- (id)lsWorkspace;
- (void)openICloudSettings;
- (id)applicationProxyForBundleID:(id)arg1;
- (void)setLsWorkspace:(id)arg1;
- (id)initWithWorkspace:(id)arg1;
- (void)openSettings;
- (bool)applicationIsInstalled:(id)arg1;
- (void)dealloc;

@end
