/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
 */

@class NSArray;

@interface GKLeaderboardScorePlayersRequest : GKLeaderboardScoreRequest  {
    NSArray *_playerInternals;
}

@property(copy) NSArray * playerInternals;

+ (bool)supportsSecureCoding;

- (id)playerInternals;
- (void)setPlayerInternals:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;

@end
