/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/FTServices.framework/FTServices
 */

@class NSData, NSString, NSMutableArray;

@interface FTIDSMessage : IDSBaseMessage <NSCopying> {
    NSData *_pushCert;
    struct __SecKey { } *_identityKey;
    NSData *_identityCert;
    struct __SecKey { } *_identityPublicKey;
    struct __SecKey { } *_pushKey;
    struct __SecKey { } *_pushPublicKey;
    NSData *_pushToken;
    NSString *_selfURI;
    NSMutableArray *_certDataArray;
    NSMutableArray *_publicKeyArray;
    NSMutableArray *_privateKeyArray;
    NSMutableArray *_userIDArray;
}

@property struct __SecKey { }* pushPrivateKey;
@property struct __SecKey { }* pushPublicKey;
@property(copy) NSData * pushCertificate;
@property(copy) NSData * pushToken;
@property(copy) NSString * selfURI;
@property(copy) NSMutableArray * certDataArray;
@property(copy) NSMutableArray * publicKeyArray;
@property(copy) NSMutableArray * privateKeyArray;
@property(copy) NSMutableArray * userIDArray;
@property struct __SecKey { }* identityPrivateKey;
@property struct __SecKey { }* identityPublicKey;
@property(copy) NSData * IDCertificate;


- (id)pushToken;
- (bool)wantsIDSServer;
- (bool)wantsBinaryPush;
- (void)addAuthUserID:(id)arg1 certificate:(id)arg2 privateKey:(struct __SecKey { }*)arg3 publicKey:(struct __SecKey { }*)arg4;
- (void)setUserIDArray:(id)arg1;
- (void)setCertDataArray:(id)arg1;
- (void)setPrivateKeyArray:(id)arg1;
- (void)setPublicKeyArray:(id)arg1;
- (void)setIdentityPublicKey:(struct __SecKey { }*)arg1;
- (void)setIdentityPrivateKey:(struct __SecKey { }*)arg1;
- (void)setIDCertificate:(id)arg1;
- (void)setPushPublicKey:(struct __SecKey { }*)arg1;
- (void)setPushPrivateKey:(struct __SecKey { }*)arg1;
- (void)setPushCertificate:(id)arg1;
- (void)setPushToken:(id)arg1;
- (void)setSelfURI:(id)arg1;
- (long long)responseCommand;
- (bool)wantsBagKey;
- (id)additionalMessageHeadersForOutgoingPush;
- (bool)wantsCompressedBody;
- (bool)wantsHTTPHeaders;
- (bool)wantsBodySignature;
- (bool)wantsSignature;
- (id)additionalMessageHeaders;
- (id)selfURI;
- (id)privateKeyArray;
- (id)publicKeyArray;
- (id)userIDArray;
- (id)certDataArray;
- (struct __SecKey { }*)identityPrivateKey;
- (struct __SecKey { }*)identityPublicKey;
- (id)IDCertificate;
- (struct __SecKey { }*)pushPrivateKey;
- (struct __SecKey { }*)pushPublicKey;
- (id)pushCertificate;
- (long long)command;
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
