/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/CommonUtilities.framework/CommonUtilities
 */

@class NSMutableSet, NSRecursiveLock;

@interface CUTTelephonyManager : NSObject  {
    bool_registered;
    NSRecursiveLock *_lock;
    NSMutableSet *_disableFastDormancyTokens;
    void *__suspendDormancyAssertion;
}

@property bool registered;
@property void* _suspendDormancyAssertion;
@property(retain) NSRecursiveLock * lock;
@property(retain) NSMutableSet * disableFastDormancyTokens;

+ (id)sharedInstance;

- (void)set_suspendDormancyAssertion:(void*)arg1;
- (void*)_suspendDormancyAssertion;
- (void)setRegistered:(bool)arg1;
- (bool)registered;
- (void)setDisableFastDormancyTokens:(id)arg1;
- (id)disableFastDormancyTokens;
- (void)setLock:(id)arg1;
- (void)removeFastDormancyDisableToken:(id)arg1;
- (void)addFastDormancyDisableToken:(id)arg1;
- (bool)disableFastDormancy;
- (void)_setFastDormancySuspended:(bool)arg1;
- (void)__adjustFastDormancyTokens;
- (void)_adjustFastDormancyTokens;
- (id)init;
- (id)lock;
- (void)dealloc;

@end
