/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
 */

@interface BKSCFBundle : NSObject  {
    struct __CFBundle { } *_cfBundle;
}


- (struct __CFBundle { }*)cfBundle;
- (id)initWithCFBundle:(struct __CFBundle { }*)arg1;
- (void)dealloc;
- (id)executablePath;
- (id)bundleIdentifier;
- (id)localizedStringForKey:(id)arg1 value:(id)arg2 table:(id)arg3;
- (id)pathForResource:(id)arg1 ofType:(id)arg2;
- (id)localizedInfoDictionary;
- (id)infoDictionary;
- (id)initWithPath:(id)arg1;
- (id)bundlePath;

@end
