/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
 */

@interface BKSHIDEventDescriptor : NSObject <NSSecureCoding> {
    unsigned int _hidEventType;
}

@property(readonly) unsigned int hidEventType;

+ (id)reusableKeyboardDescriptorWithPage:(unsigned int)arg1 usage:(unsigned int)arg2;
+ (id)reusableVendorDefinedDescriptorWithPage:(unsigned int)arg1 usage:(unsigned int)arg2;
+ (id)reusableDescriptorWithEventType:(unsigned int)arg1;
+ (id)descriptorWithEventType:(unsigned int)arg1;
+ (bool)supportsSecureCoding;

- (id)initWithEventType:(unsigned int)arg1;
- (bool)describes:(id)arg1;
- (unsigned int)hidEventType;
- (bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;

@end
