/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/HomeSharing.framework/HomeSharing
 */

@class NSArray;

@interface HSControlInterfaceResponse : HSResponse  {
    NSArray *_interfaces;
}

@property(copy) NSArray * interfaces;


- (id)interfaces;
- (void)setInterfaces:(id)arg1;
- (void).cxx_destruct;

@end
