/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FitnessFriends.framework/FitnessFriends
 */

@interface FFDemoData : NSObject

+ (id)_appleWatchSourceRevision;
+ (id)_createAllenBuchinski;
+ (id)_createEmilyParker;
+ (id)_createJaneDaniels;
+ (id)_fakeAchievementDuringDayStartingAtDate:(id)arg1 personUUID:(id)arg2;
+ (id)_fakeWorkoutDuringDayStartingAtDate:(id)arg1 personUUID:(id)arg2;
+ (id)_fakeWorkoutsForIndex:(long long)arg1 personUUID:(id)arg2;
+ (id)_fakeWorkoutsForLastWeekWithPersonUUID:(id)arg1 dailySnapshotProbability:(double)arg2;
+ (id)createMeWithModel:(id)arg1;
+ (id)fakeFriendListForMarketing;

@end
