/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
 */

@class NSString, CAMediaTimingFunction;

@interface BSAnimationSettings : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, BSXPCCoding> {
    double _duration;
    double _delay;
    double _frameInterval;
    CAMediaTimingFunction *_timingFunction;
}

@property(readonly) double duration;
@property(readonly) double delay;
@property(readonly) double frameInterval;
@property(retain,readonly) CAMediaTimingFunction * timingFunction;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;

+ (id)settingsWithDuration:(double)arg1 delay:(double)arg2 timingFunction:(id)arg3;
+ (id)settingsWithDuration:(double)arg1 delay:(double)arg2;
+ (id)settingsWithDuration:(double)arg1 timingFunction:(id)arg2;
+ (id)settingsWithDuration:(double)arg1;
+ (bool)supportsSecureCoding;

- (void)_setFrameInterval:(double)arg1;
- (void)_setTimingFunction:(id)arg1;
- (void)_setDelay:(double)arg1;
- (void)_setDuration:(double)arg1;
- (bool)isSpringAnimation;
- (id)timingFunction;
- (double)frameInterval;
- (double)delay;
- (id)_initWithDuration:(double)arg1 delay:(double)arg2 frameInterval:(double)arg3 timingFunction:(id)arg4;
- (id)initWithXPCDictionary:(id)arg1;
- (void)encodeWithXPCDictionary:(id)arg1;
- (id)init;
- (bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (double)duration;

@end
