/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
 */

@class NSObject<OS_dispatch_queue>, NSMutableDictionary, NSLock;

@interface BSXPCConnectionListenerManager : NSObject  {
    NSObject<OS_dispatch_queue> *_listeningQueue;
    NSMutableDictionary *_services;
    NSLock *_servicesLock;
    NSObject<OS_dispatch_queue> *_defaultHandlerQueue;
}

+ (void)stopListeningForService:(id)arg1;
+ (void)listenForService:(id)arg1 onQueue:(id)arg2 withHandler:(id)arg3;
+ (id)defaultHandlerQueue;
+ (id)sharedInstance;

- (void)_removeService:(id)arg1;
- (void)_addService:(id)arg1 withHandler:(id)arg2 onQueue:(id)arg3;
- (id)_defaultHandlerQueue;
- (id)init;
- (void)dealloc;
- (id)_init;

@end
