/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
 */

@class NSString;

@interface BSZeroingWeakReference : NSObject  {
    id _object;
    NSString *_debug;
    unsigned long long _objectAddress;
}

+ (id)referenceWithObject:(id)arg1;

- (id)init;
- (id)initWithObject:(id)arg1;
- (id)object;
- (bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)dealloc;
- (id)description;

@end
