/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/GameKit.framework/Frameworks/GameCenterUI.framework/GameCenterUI
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class UIAlertView, NSError;

@interface GKHostedAuthenticateViewController : GKHostedViewController <GKAuthenticateViewController> {
    BOOL _disablesSignIn;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _completionHandler;

    UIAlertView *_alert;
    NSError *_error;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _dismissCompletionHandler;

}

@property(retain) UIAlertView * alert;
@property(retain) NSError * error;
@property(copy) id dismissCompletionHandler;
@property(copy) id completionHandler;
@property BOOL disablesSignIn;

+ (BOOL)_preventsAppearanceProxyCustomization;

- (void)setAlert:(id)arg1;
- (id)alert;
- (BOOL)disablesSignIn;
- (void)setDisablesSignIn:(BOOL)arg1;
- (void)finishAuthenticationWithError:(id)arg1;
- (id)hostSideViewControllerClassName;
- (id)serviceSideViewControllerClassName;
- (id)init;
- (void)dealloc;
- (void)setError:(id)arg1;
- (id)error;
- (void)setDismissCompletionHandler:(id)arg1;
- (id)dismissCompletionHandler;
- (void)setCompletionHandler:(id)arg1;
- (BOOL)shouldAutomaticallyForwardAppearanceMethods;
- (BOOL)automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers;
- (BOOL)shouldAutomaticallyForwardRotationMethods;
- (void)dismissViewControllerAnimated:(BOOL)arg1 completion:(id)arg2;
- (id)completionHandler;

@end
