/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/GameKit.framework/Frameworks/GameCenterUI.framework/GameCenterUI
 */

@class NSMutableArray;

@interface GKTextStyle : NSObject <NSCoding, GKTextStyle> {
    NSMutableArray *_invocations;
}

@property(retain) NSMutableArray * invocations;

+ (id)textStyle;

- (void)setInvocations:(id)arg1;
- (id)invocations;
- (id)initEmpty;
- (id)replayOnBaseStyle:(id)arg1;
- (id)styleWithName:(id)arg1 fallback:(id)arg2;
- (id)methodSignatureForProtocol:(id)arg1 selector:(SEL)arg2;
- (id)init;
- (id)methodSignatureForSelector:(SEL)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (void)forwardInvocation:(id)arg1;
- (id)copy;
- (void)dealloc;
- (id)description;
- (id)attributes;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end
