/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@interface AFAggregator : NSObject  {
    int _type;
    double _startTime;
    BOOL _hasActiveRequest;
    BOOL _sessionIsRetrying;
    BOOL _retryPrefersWWAN;
}

@property int connectionType;
@property BOOL hasActiveRequest;

+ (void)logTimeToBeepWithDuration:(double)arg1;
+ (void)logRequestCancelAfterSeconds:(double)arg1;
+ (void)missedAlertContextForRequest;
+ (void)missedAppContextForRequest;
+ (void)logRequestCompletedWithDuration:(double)arg1;
+ (id)_fullAggDKeyWithPrefix:(id)arg1 error:(id)arg2;
+ (void)logDictationSucceeded;
+ (void)logDictationFailedWithError:(id)arg1;
+ (void)logDictationCancelled;
+ (void)logDictationStarted;
+ (void)logSiriRequestSucceeded;
+ (void)logSiriRequestFailedWithError:(id)arg1;
+ (void)logSiriRequestCancelled;
+ (void)logSiriOtherRequestStarted;
+ (void)logSiriSpeechRequestStarted;

- (void)setHasActiveRequest:(BOOL)arg1;
- (BOOL)hasActiveRequest;
- (void)speechResponseFailure;
- (void)speechResponseReceived;
- (void)startWaitingForSpeechResponse;
- (void)beginSessionRetryPreferringWWAN:(BOOL)arg1;
- (void)connectionDidDrop;
- (void)connectionDidFail;
- (void)recordSessionRetrySuccess;
- (void)recordSuccessForConnectionType:(int)arg1 isWarm:(BOOL)arg2 forTimeInterval:(double)arg3;
- (void)recordFailure:(int)arg1 forConnectionType:(int)arg2;
- (void)setConnectionType:(int)arg1;
- (int)connectionType;

@end
