/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@class NSUUID;

@interface AFSiriRequest : NSObject <NSSecureCoding> {
    NSUUID *_identifier;
}

+ (bool)supportsSecureCoding;

- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void).cxx_destruct;
- (id)_identifier;
- (id)_initWithIdentifier:(id)arg1;

@end
