/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@class NSArray;

@interface AFSpeechPhrase : NSObject <NSSecureCoding> {
    bool_isLowConfidence;
    NSArray *_interpretations;
}

@property(copy) NSArray * interpretations;
@property bool isLowConfidence;

+ (bool)supportsSecureCoding;

- (void)setIsLowConfidence:(bool)arg1;
- (bool)isLowConfidence;
- (void)setInterpretations:(id)arg1;
- (id)bestInterpretation;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void).cxx_destruct;
- (id)description;
- (id)interpretations;

@end
