/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/SpringBoardUIServices.framework/SpringBoardUIServices
 */

@interface SBEmptyButtonView : UIView <TPNumberPadButtonProtocol> {
    unsigned int _char;
}

@property unsigned int character;


- (id)initForCharacter:(unsigned int)arg1;
- (void)setCharacter:(unsigned int)arg1;
- (unsigned int)character;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;

@end
