/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/SpringBoardUIServices.framework/SpringBoardUIServices
 */

@interface SBPasscodeNumberPadButton : TPNumberPadDarkStyleButton <SBUIPasscodeNumberPadButton> {
}

+ (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })paddingOutsideRing;
+ (float)_numberPadButtonPaddingHeight;
+ (float)_numberPadButtonPaddingWidth;
+ (float)_numberPadButtonOuterCircleDiameter;
+ (struct CGSize { float x1; float x2; })defaultSize;

- (id)initForCharacter:(unsigned int)arg1;
- (id)stringCharacter;
- (int)characterType;

@end
