/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/SpringBoardUIServices.framework/SpringBoardUIServices
 */

@interface SBUIPasscodeLockViewLongNumericKeypad : SBUIPasscodeLockViewWithKeypad  {
}


- (id)_longNumericEntryField;
- (bool)_showsPromptLabelOnEntryField;
- (double)_entryFieldBottomYDistanceFromNumberPadTopButton;
- (void)_setHasInput:(bool)arg1;
- (id)_newEntryField;
- (bool)_includesStatusView;
- (id)initWithLightStyle:(bool)arg1;
- (void)updateStatusText:(id)arg1 subtitle:(id)arg2 animated:(bool)arg3;

@end
