/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
 */

@interface ISProtocolDataProvider : ISDataProvider <NSCopying> {
    BOOL _shouldPostFooterSectionChanged;
    BOOL _shouldProcessAccount;
    BOOL _shouldProcessAuthenticationDialogs;
    BOOL _shouldProcessDialogs;
    BOOL _shouldProcessProtocol;
    BOOL _shouldTriggerDownloads;
}

@property BOOL shouldPostFooterSectionChanged;
@property BOOL shouldProcessAccount;
@property BOOL shouldProcessAuthenticationDialogs;
@property BOOL shouldProcessDialogs;
@property BOOL shouldProcessProtocol;
@property BOOL shouldTriggerDownloads;


- (void)setShouldProcessAuthenticationDialogs:(BOOL)arg1;
- (void)setShouldPostFooterSectionChanged:(BOOL)arg1;
- (void)setShouldTriggerDownloads:(BOOL)arg1;
- (BOOL)shouldPostFooterSectionChanged;
- (void)_checkInAppPurchaseQueueForAction:(id)arg1;
- (BOOL)shouldProcessAccount;
- (void)_selectFooterSection:(id)arg1;
- (void)_checkDownloadQueues;
- (BOOL)shouldTriggerDownloads;
- (BOOL)_processFailureTypeFromDictionary:(id)arg1 error:(id*)arg2;
- (void)_performActionsForResponse:(id)arg1;
- (BOOL)shouldProcessProtocol;
- (BOOL)_shouldFailWithTokenErrorForDialog:(id)arg1 dictionary:(id)arg2 error:(id*)arg3;
- (BOOL)shouldProcessDialogs;
- (BOOL)shouldProcessAuthenticationDialogs;
- (void)setShouldProcessDialogs:(BOOL)arg1;
- (void)setShouldProcessAccount:(BOOL)arg1;
- (BOOL)processDictionary:(id)arg1 error:(id*)arg2;
- (BOOL)processDialogFromDictionary:(id)arg1 error:(id*)arg2;
- (void)setShouldProcessProtocol:(BOOL)arg1;
- (BOOL)parseData:(id)arg1 returningError:(id*)arg2;
- (id)init;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
