/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/RemoteUI.framework/RemoteUI
 */

@interface RUISetupAssistantModalStyle : RUISetupAssistantStyle  {
}


- (void)applyToObjectModel:(id)arg1;

@end
