/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/CloudDocsDaemon.framework/CloudDocsDaemon
 */

@class NSString;

@interface BRCItemID : NSObject <NSCopying, NSSecureCoding, PQLBindable, PQLResultSetInitializer> {
    unsigned char _uuid[16];
    unsigned char _kind;
}

@property(readonly) bool isRoot;
@property(readonly) bool isDocuments;
@property(readonly) unsigned char kind;
@property(readonly) NSString * itemIDString;
@property(readonly) NSString * shortItemIDString;
@property(readonly) const char * UTF8String;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;

+ (id)documentsItemID;
+ (id)rootItemID;
+ (void)initialize;
+ (bool)supportsSecureCoding;

- (id)initWithItemID:(id)arg1;
- (id)initWithKind:(unsigned char)arg1 bytes:(const void*)arg2 length:(unsigned long long)arg3;
- (id)initFromPQLResultSet:(id)arg1 error:(id*)arg2;
- (void)sqliteBind:(struct sqlite3_stmt { }*)arg1 index:(int)arg2;
- (id)shortItemIDString;
- (bool)isDocuments;
- (id)itemIDString;
- (bool)isEqualToItemID:(id)arg1;
- (id)initWithSqlite3Value:(struct Mem { }*)arg1;
- (bool)isRoot;
- (unsigned char)kind;
- (id)init;
- (id)initWithString:(id)arg1;
- (const char *)UTF8String;
- (bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
