/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CloudDocsDaemon.framework/CloudDocsDaemon
 */

@interface BRCTrackingDescriptor : NSObject {
    id /* block */  _handler;
    bool  _updateAccessTime;
}

@property (nonatomic, readonly, copy) id /* block */ handler;
@property (nonatomic, readonly) bool updateAccessTime;

- (void).cxx_destruct;
- (id /* block */)handler;
- (id)initWithHandler:(id /* block */)arg1 updateAccessTime:(bool)arg2;
- (bool)updateAccessTime;

@end
