/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class DOMCSSStyleDeclaration, NSString;

@interface DOMCSSPageRule : DOMCSSRule  {
}

@property(copy) NSString * selectorText;
@property(readonly) DOMCSSStyleDeclaration * style;


- (void)setSelectorText:(id)arg1;
- (id)selectorText;
- (id)style;

@end
