/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class NSString;

@interface DOMCounter : DOMObject  {
}

@property(copy,readonly) NSString * identifier;
@property(copy,readonly) NSString * listStyle;
@property(copy,readonly) NSString * separator;


- (id)identifier;
- (id)separator;
- (id)listStyle;
- (void)finalize;
- (void)dealloc;

@end
