/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMDOMTokenList : DOMObject  {
}

@property(readonly) unsigned int length;


- (bool)toggle:(id)arg1 force:(bool)arg2;
- (void)add:(id)arg1;
- (bool)contains:(id)arg1;
- (unsigned int)length;
- (void)finalize;
- (void)dealloc;
- (void)remove:(id)arg1;
- (id)item:(unsigned int)arg1;

@end
