/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class NSString;

@interface DOMHTMLOListElement : DOMHTMLElement  {
}

@property BOOL compact;
@property int start;
@property(copy) NSString * type;


- (void)setStart:(int)arg1;
- (void)setReversed:(BOOL)arg1;
- (BOOL)reversed;
- (void)setCompact:(BOOL)arg1;
- (void)setType:(id)arg1;
- (id)type;
- (int)start;
- (BOOL)compact;

@end
