/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMProgressEvent : DOMEvent  {
}

@property(readonly) bool lengthComputable;
@property(readonly) unsigned long long loaded;
@property(readonly) unsigned long long total;


- (unsigned long long)loaded;
- (bool)lengthComputable;
- (unsigned long long)total;

@end
