/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface LegacyTileCacheTombstone : NSObject  {
    booldead;
}

@property(getter=isDead) bool dead;


- (void)setDead:(bool)arg1;
- (bool)isDead;

@end
