/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@class NSString;

@interface WebResourceLoaderQuickLookDelegate : NSObject <NSURLConnectionDelegate> {
    struct RefPtr<WebCore::ResourceLoader> { 
        struct ResourceLoader {} *m_ptr; 
    } _resourceLoader;
}

@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (id)initWithResourceLoader:(struct PassRefPtr<WebCore::ResourceLoader> { struct ResourceLoader {} *x1; })arg1;
- (void)clearHandle;
- (void)connection:(id)arg1 didReceiveDataArray:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2 lengthReceived:(long long)arg3;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void).cxx_destruct;
- (id).cxx_construct;

@end
