/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/MapKit.framework/MapKit
 */

@class _MKMapLayerHostingView;

@interface _MKMapLayerHostingLayer : CALayer  {
    _MKMapLayerHostingView *_hostView;
}

@property _MKMapLayerHostingView * hostView;


- (void)setHostView:(id)arg1;
- (id)hostView;

@end
