/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/MapKit.framework/MapKit
 */

@class NSString, NSArray, <GEOCompletionItem>, MKMapItem;

@interface MKSearchCompletion : NSObject  {
    <GEOCompletionItem> *_item;
    NSString *_sourceID;
    NSString *_localizedSectionHeader;
}

@property(readonly) <GEOCompletionItem> * geoCompletionItem;
@property(readonly) NSArray * displayLines;
@property(readonly) MKMapItem * mapItem;
@property(copy) NSString * sourceID;
@property(copy) NSString * localizedSectionHeader;


- (void)applyToLegacySearch:(id)arg1;
- (id)geoCompletionItem;
- (id)iconWithScale:(double)arg1;
- (id)initWithGeoCompletionItem:(id)arg1;
- (void)sendFeedback;
- (bool)getCoordinate:(struct { double x1; double x2; }*)arg1;
- (id)highlightsForLine:(unsigned long long)arg1;
- (void)setLocalizedSectionHeader:(id)arg1;
- (id)queryLine;
- (id)calloutTitle;
- (id)displayLines;
- (id)localizedSectionHeader;
- (id)mapItem;
- (void)setSourceID:(id)arg1;
- (id)sourceID;
- (bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void).cxx_destruct;
- (id)description;

@end
