/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKTransitLoadingTableViewCell : MKCustomSeparatorTableViewCell {
    UIActivityIndicatorView * _loadingIndicator;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)startAnimating;
- (void)stopAnimating;

@end
