/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface CHBChart : NSObject  {
}

+ (void)readWithState:(id)arg1;
+ (int)emptyCellsPlottedEnumsFrom:(int)arg1;
+ (int)readCHDDisplayBlanksAsEnumFrom:(int)arg1;


@end
