/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface CHDLine2DType : CHDLineType  {
    boolmShowMarker;
    boolmStockType;
}


- (void)setStockType:(bool)arg1;
- (bool)isStockType;
- (void)setShowMarker:(bool)arg1;
- (bool)showMarker;
- (id)initWithChart:(id)arg1;

@end
