/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface CMDiagramPointPyramidLayerMapper : CMDiagramPointMapper  {
    double mPyramidAspectRatio;
}


- (void)setPyramidAspectRatio:(double)arg1;
- (void)mapAt:(id)arg1 withState:(id)arg2;

@end
