/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface CMToggleProperty : CMProperty  {
    int wdValue;
}


- (id)mapStrikeTrough;
- (id)mapItalic;
- (id)mapBold;
- (int)compareValue:(id)arg1;
- (void)resolveWithBaseProperty:(id)arg1;
- (id)cssStringForName:(id)arg1;
- (id)initWithCMTogglePropertyValue:(int)arg1;
- (int)value;

@end
