/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface CPMessagePlaceholderInfo : NSObject  {
    id mKey;
    BOOL mInUse;
}


- (BOOL)isInUse;
- (void)setInUse:(BOOL)arg1;
- (id)init;
- (void)dealloc;
- (id)key;

@end
