/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class TSUColor;

@interface MFPhoneHatchBrush : MFPhoneBrush  {
    TSUColor *m_colour;
    int m_style;
}

+ (id)patternNameForHatchStyle:(int)arg1;
+ (id)hatchBrushWithColour:(id)arg1 :(int)arg2;

- (id)initWithColour:(id)arg1 :(int)arg2;
- (void)fillPath:(id)arg1 :(id)arg2;
- (void)dealloc;

@end
