/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface MFPLevelsEffect : MFPEffect  {
    int mHighlight;
    int mMidtone;
    int mShadow;
}

+ (id)GUID;

- (id)initWithHighlight:(int)arg1 midtone:(int)arg2 shadow:(int)arg3;

@end
