/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface MFPSharpenEffect : MFPEffect  {
    float mAmount;
    float mRadius;
}

+ (id)GUID;

- (id)initWithAmount:(float)arg1 radius:(float)arg2;

@end
