/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class OADColor;

@interface OADColorChangeEffect : OADBlipEffect  {
    OADColor *mFromColor;
    OADColor *mToColor;
}


- (void)setStyleColor:(id)arg1;
- (id)toColor;
- (id)fromColor;
- (void)setToColor:(id)arg1;
- (void)setFromColor:(id)arg1;
- (id)init;
- (bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
