/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSURL, NSString;

@interface OADHyperlink : NSObject  {
    NSURL *mTargetLocation;
    int mTargetMode;
    NSString *mTargetFrame;
    NSString *mAction;
    NSString *mTooltip;
    NSString *mInvalidUrl;
    BOOL mDoEndSound;
    BOOL mIsVisited;
    BOOL mDoAddToHistory;
}

@property BOOL doEndSound;
@property BOOL isVisited;
@property BOOL doAddToHistory;


- (id)targetFrame;
- (void)setDoAddToHistory:(BOOL)arg1;
- (BOOL)doAddToHistory;
- (void)setIsVisited:(BOOL)arg1;
- (void)setDoEndSound:(BOOL)arg1;
- (BOOL)doEndSound;
- (void)setInvalidUrl:(id)arg1;
- (id)invalidUrl;
- (void)setTooltip:(id)arg1;
- (void)setTargetFrame:(id)arg1;
- (void)setTargetMode:(int)arg1;
- (void)setTargetLocation:(id)arg1;
- (id)tooltip;
- (int)targetMode;
- (id)targetLocation;
- (BOOL)isVisited;
- (id)init;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (void)dealloc;
- (void)setAction:(id)arg1;
- (id)action;

@end
