/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSDictionary;

@interface OADImageRecolorInfo : NSObject  {
    NSDictionary *mColors;
    NSDictionary *mFills;
}


- (id)fills;
- (id)initWithColors:(id)arg1 fills:(id)arg2;
- (id)colors;
- (bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)dealloc;

@end
