/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface OADTableColumn : NSObject  {
    float mWidth;
}


- (void)setWidth:(float)arg1;
- (float)width;
- (id)description;

@end
