/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSString;

@interface PBFontEntity : NSObject  {
    NSString *mFaceName;
    int mCharSet;
    int mType;
    int mFamily;
}


- (id)initWithName:(id)arg1 charSet:(int)arg2 type:(int)arg3 family:(int)arg4;
- (id)faceName;
- (int)family;
- (int)charSet;
- (void)dealloc;
- (int)type;

@end
