/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class PDAnimateMotionBehavior, NSString, PDBuild, PDAnimationTarget;

@interface PDAnimationCache : NSObject  {
    int mNodeType;
    int mPresetId;
    int mPresetSubType;
    int mPresetClass;
    PDAnimationTarget *mTarget;
    boolmHasDelay;
    double mDelay;
    boolmHasDuration;
    double mDuration;
    boolmHasDirection;
    double mDirection;
    boolmHasPartCount;
    int mPartCount;
    PDAnimateMotionBehavior *mMotionPath;
    boolmHasValue;
    double mValue;
    PDBuild *mBuild;
    int mIterateType;
    boolmIsHead;
    int mLevel;
    NSString *mGroupId;
}

@property(retain) PDAnimationTarget * target;
@property int nodeType;
@property int presetId;
@property int presetSubType;
@property int presetClass;
@property int iterateType;
@property bool hasDelay;
@property double delay;
@property bool hasDuration;
@property double duration;
@property bool hasDirection;
@property double direction;
@property bool hasPartCount;
@property int partCount;
@property(retain) PDAnimateMotionBehavior * motionPath;
@property bool hasValue;
@property double value;
@property(retain) NSString * groupId;
@property bool isHead;
@property int level;
@property(retain) PDBuild * build;

+ (void)mapAnimationInfo:(id)arg1 cacheData:(id)arg2 state:(id)arg3;
+ (void)mapCommonData:(id)arg1 cacheData:(id)arg2 state:(id)arg3;
+ (id)createAnimationInfoDataForCacheItem:(id)arg1 order:(unsigned int)arg2;
+ (void)loadAnimationCache:(id)arg1 pdAnimation:(id)arg2 state:(id)arg3;

- (void)setIsHead:(bool)arg1;
- (void)setHasPartCount:(bool)arg1;
- (void)setHasDirection:(bool)arg1;
- (void)setHasDelay:(bool)arg1;
- (void)setIterateType:(int)arg1;
- (void)setPresetClass:(int)arg1;
- (void)setNodeType:(int)arg1;
- (id)initWithAnimationInfo:(id)arg1;
- (bool)isHead;
- (void)setPartCount:(int)arg1;
- (int)partCount;
- (bool)hasPartCount;
- (int)iterateType;
- (void)setBuild:(id)arg1;
- (void)setMotionPath:(id)arg1;
- (id)motionPath;
- (int)presetClass;
- (void)setPresetId:(int)arg1;
- (void)setPresetSubType:(int)arg1;
- (int)presetSubType;
- (int)presetId;
- (bool)hasDelay;
- (bool)hasDirection;
- (bool)hasDuration;
- (void)setGroupId:(id)arg1;
- (id)groupId;
- (void)setHasValue:(bool)arg1;
- (void)setHasDuration:(bool)arg1;
- (bool)hasValue;
- (void)setDirection:(double)arg1;
- (double)direction;
- (double)value;
- (void)setValue:(double)arg1;
- (void)setDuration:(double)arg1;
- (double)delay;
- (id)build;
- (void)setLevel:(int)arg1;
- (int)level;
- (int)nodeType;
- (void)setTarget:(id)arg1;
- (void)dealloc;
- (double)duration;
- (id)target;
- (void)setDelay:(double)arg1;

@end
