/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSString, NSDate;

@interface PDComment : NSObject  {
    struct CGPoint { 
        double x; 
        double y; 
    } mPosition;
    NSString *mText;
    unsigned int mAuthorId;
    NSDate *mDate;
    unsigned int mIndex;
}


- (unsigned int)authorId;
- (void)setAuthorId:(unsigned int)arg1;
- (void)setIndex:(unsigned int)arg1;
- (unsigned int)index;
- (id)text;
- (void)setPosition:(struct CGPoint { double x1; double x2; })arg1;
- (id)init;
- (id)date;
- (void)dealloc;
- (id).cxx_construct;
- (struct CGPoint { double x1; double x2; })position;
- (void)setDate:(id)arg1;
- (void)setText:(id)arg1;

@end
