/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSData;

@interface SFUMemoryInputStream : NSObject <SFUBufferedInputStream> {
    NSData *mData;
    const char *mStart;
    const char *mCurrent;
    const char *mEnd;
}


- (id)initWithData:(id)arg1 offset:(unsigned long)arg2 length:(unsigned long)arg3;
- (id)closeLocalStream;
- (BOOL)seekWithinBufferToOffset:(long long)arg1;
- (void)enableSystemCaching;
- (void)disableSystemCaching;
- (BOOL)canSeek;
- (unsigned long)readToOwnBuffer:(const char **)arg1 size:(unsigned long)arg2;
- (unsigned long)readToBuffer:(char *)arg1 size:(unsigned long)arg2;
- (void)seekToOffset:(long long)arg1;
- (long long)offset;
- (void)close;
- (void)dealloc;
- (id)initWithData:(id)arg1;

@end
