/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class WDATextBox, NSString, WDAAnchor, OADDrawable;

@interface WDAContent : NSObject <OADClient, OADTextClient> {
    WDAAnchor *mAnchor;
    WDATextBox *mTextBox;
    OADDrawable *mDrawable;
    int mTextType;
}

@property(readonly) WDAAnchor * anchor;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;

+ (Class)classForType:(unsigned short)arg1;

- (bool)isTopLevelObject;
- (bool)isLine;
- (void)setTextBox:(id)arg1 document:(id)arg2;
- (id)createTextBoxWithDocument:(id)arg1 textType:(int)arg2;
- (void)clearAnchor;
- (id)createAnchor;
- (void)setTextType:(int)arg1;
- (void)setDrawable:(id)arg1;
- (int)textType;
- (bool)hasBounds;
- (id)textBox;
- (bool)isShape;
- (id)drawable;
- (void)setBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })bounds;
- (id)init;
- (void)dealloc;
- (id)description;
- (bool)floating;
- (id)anchor;
- (bool)hasText;

@end
