/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class WDText;

@interface WDBlock : NSObject  {
    WDText *mText;
}


- (void)clearProperties;
- (id)newRunIterator;
- (id)runIterator;
- (int)textType;
- (int)blockType;
- (id)document;
- (id)text;
- (id)initWithText:(id)arg1;
- (id)init;
- (BOOL)isEmpty;

@end
