/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@class NSString;

@interface WMBookmarkMapper : CMMapper  {
    NSString *mName;
    int mBookmarkType;
}


- (void)mapAt:(id)arg1 withState:(id)arg2;
- (id)initWithWDBookmark:(id)arg1 parent:(id)arg2;

@end
