/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/OfficeImport.framework/OfficeImport
 */

@interface WMEnumProperty : CMProperty  {
    unsigned long long wdValue;
}


- (id)cssStringForName:(id)arg1;
- (id)initWithEnum:(unsigned long long)arg1;
- (id)mapCellTextVAlign;
- (id)mapUnderline;
- (id)mapVerticalAlign;
- (id)mapJustification;
- (unsigned long long)value;
- (id)description;

@end
