/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/PhotosUI.framework/PhotosUI
 */

@class NSMutableString, NSString, PLAvalanche;

@interface PUAvalancheReporter : NSObject <UIAlertViewDelegate> {
    NSString *_uuid;
    PLAvalanche *_avalanche;
    NSMutableString *_reporterLog;
}

@property(retain) NSString * uuid;
@property(retain) PLAvalanche * avalanche;
@property(retain) NSMutableString * reporterLog;

+ (id)createAlertViewForReport;

- (void)setReporterLog:(id)arg1;
- (id)reporterLog;
- (id)avalanche;
- (void)showRadarReporterInViewController:(id)arg1;
- (id)initWithAvalanche:(id)arg1;
- (void)attachReporterLogToRadar:(id)arg1;
- (void)attachThumbsToRadar:(id)arg1;
- (id)descriptionForCurrentAvalanche;
- (void)setAvalanche:(id)arg1;
- (id)uuid;
- (void)setUuid:(id)arg1;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;

@end
