/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/NotificationsUI.framework/NotificationsUI
 */

@class NSDictionary;

@interface NCInteractiveNotificationViewController : UIViewController <NCInteractiveNotificationServiceInterface> {
    bool_modal;
    NSDictionary *_context;
    double _maximumHeight;
}

@property(copy) NSDictionary * context;
@property(getter=isModal) bool modal;
@property double maximumHeight;

+ (id)_remoteViewControllerInterface;
+ (id)_exportedInterface;

- (double)maximumHeight;
- (void)requestProximityMonitoringEnabled:(bool)arg1;
- (void)setActionEnabled:(bool)arg1 atIndex:(unsigned long long)arg2;
- (void)requestPreferredContentHeight:(double)arg1;
- (void)dismissWithContext:(id)arg1;
- (void)_handleActionIdentifier:(id)arg1;
- (void)_handleActionAtIndex:(unsigned long long)arg1;
- (void)_getActionTitlesWithCompletion:(id)arg1;
- (void)_getActionContextWithCompletion:(id)arg1;
- (void)_willPresentFromActionIdentifier:(id)arg1;
- (void)_didChangeRevealPercent:(double)arg1;
- (void)_proximityStateDidChange:(bool)arg1;
- (void)_interactiveNotificationDidAppear;
- (void)_setModal:(bool)arg1;
- (void)_setMaximumHeight:(double)arg1;
- (void)_getInitialStateWithCompletion:(id)arg1;
- (void)willPresentFromActionIdentifier:(id)arg1;
- (void)handleActionIdentifier:(id)arg1;
- (void)proximityStateDidChange:(bool)arg1;
- (void)handleActionAtIndex:(unsigned long long)arg1;
- (id)actionTitles;
- (id)actionContext;
- (void)didChangeRevealPercent:(double)arg1;
- (void)interactiveNotificationDidAppear;
- (void)setMaximumHeight:(double)arg1;
- (void)setModal:(bool)arg1;
- (id)accessoryViewService;
- (id)inlayViewService;
- (double)bottomOverhangHeight;
- (double)preferredContentHeight;
- (bool)isModal;
- (id)context;
- (void)setContext:(id)arg1;
- (void)_setContext:(id)arg1;
- (void)dealloc;
- (bool)showsKeyboard;
- (void)viewDidLoad;

@end
