/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/CameraKit.framework/CameraKit
 */

@class UICollectionView;

@interface CAMEffectSelectionViewControllerView : UIView  {
    UICollectionView *_collectionView;
}

@property(retain) UICollectionView * collectionView;


- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void).cxx_destruct;
- (void)setCollectionView:(id)arg1;
- (id)collectionView;
- (void)layoutSubviews;

@end
