/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
 */

@class NSString;

@interface NSTextList : NSObject <NSCoding, NSCopying> {
    NSString *_markerFormat;
    unsigned long long _listFlags;
    long long _startIndex;
    void *_listSecondary;
}

+ (id)_standardMarkerAttributesForAttributes:(id)arg1;
+ (void)initialize;

- (bool)_isOrdered;
- (id)_markerSuffix;
- (id)_unaffixedMarkerTitle;
- (id)_unaffixedMarkerFormat;
- (id)_markerSpecifier;
- (id)_markerPrefix;
- (id)_markerTitle;
- (id)_markerAtIndex:(unsigned long long)arg1 inText:(id)arg2;
- (id)_unaffixedMarkerForItemNumber:(long long)arg1;
- (id)markerForItemNumber:(long long)arg1;
- (id)_markerForMarkerFormat:(id)arg1 itemNumber:(long long)arg2 isNumbered:(bool*)arg3 substitutionStart:(unsigned long long*)arg4 end:(unsigned long long*)arg5 specifierStart:(unsigned long long*)arg6 end:(unsigned long long*)arg7;
- (long long)startingItemNumber;
- (id)markerFormat;
- (void)setStartingItemNumber:(long long)arg1;
- (id)initWithMarkerFormat:(id)arg1 options:(unsigned long long)arg2;
- (unsigned long long)listOptions;
- (unsigned long long)options;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
