/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
 */

@interface UICTFont : UIFont  {
}


- (unsigned long long)_cfTypeID;
- (bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (bool)allowsWeakReference;
- (bool)retainWeakReference;
- (void)finalize;
- (unsigned long long)retainCount;
- (oneway void)release;
- (id)retain;

@end
