/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/StoreKit.framework/StoreKit
 */

@class NSDictionary, NSString, NSData;

@interface SKPayment : NSObject <NSCopying, NSMutableCopying> {
    id _internal;
}

@property(readonly) NSString * productIdentifier;
@property(readonly) NSData * requestData;
@property(readonly) int quantity;
@property(readonly) NSString * applicationUsername;
@property(readonly) NSDictionary * requestParameters;

+ (id)paymentWithProductIdentifier:(id)arg1;
+ (id)paymentWithProduct:(id)arg1;

- (id)requestData;
- (int)quantity;
- (id)applicationUsername;
- (id)productIdentifier;
- (id)requestParameters;
- (id)init;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (void)dealloc;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
