/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/ScreenReaderCore.framework/ScreenReaderCore
 */

@class NSLock;

@interface SCRCTargetSelectorTimer : SCRCTargetSelector  {
    struct __CFRunLoopTimer { } *_timer;
    id _key;
    BOOL _isCancelled;
    BOOL _isPending;
    id _object;
    NSLock *_lock;
    BOOL _createdTimer;
}

+ (void)_runThread;
+ (void)initialize;

- (void)_dispatchSCRCThread;
- (void)_dispatchMainThread;
- (void)_dispatch;
- (id)threadKey;
- (BOOL)isPending;
- (void)dispatchAfterDelay:(double)arg1 withObject:(id)arg2;
- (void)dispatchAfterDelay:(double)arg1;
- (BOOL)_createdTimer;
- (id)initWithTarget:(id)arg1 selector:(SEL)arg2 threadKey:(id)arg3;
- (id)initWithTarget:(id)arg1 selector:(SEL)arg2;
- (void)invalidate;
- (void)dealloc;
- (oneway void)release;
- (void)cancel;
- (BOOL)isCancelled;

@end
