/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Social.framework/Social
 */

@class NSString;

@interface SLFacebookAlbumTableViewCell : UITableViewCell  {
    NSString *_albumIdentifier;
}

@property(retain) NSString * albumIdentifier;


- (void)setAlbumIdentifier:(id)arg1;
- (id)albumIdentifier;
- (void).cxx_destruct;

@end
