/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/Social.framework/Social
 */

@interface SLFlickrService : SLService  {
}


- (BOOL)isFirstClassService;
- (int)authenticationStyle;
- (id)accountTypeIdentifier;
- (id)serviceType;
- (id)activityImage;
- (id)activityTitle;

@end
