/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/Social.framework/Social
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSObject, NSString, NSXPCConnection, NSLock, NSXPCInterface, NSMutableArray;

@interface SLRemoteSessionProxy : NSObject  {
    NSString *_serviceName;
    NSXPCInterface *_remoteInterface;
    id _remoteProxy;
    NSXPCConnection *_connection;
    NSMutableArray *_guaranteedRemoteCalls;
    NSLock *_guaranteedRemoteCallsLock;
    NSObject *_exportedObject;
    NSXPCInterface *_exportedInterface;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _connectionResetBlock;

}

@property NSObject * exportedObject;
@property(retain) NSXPCInterface * exportedInterface;
@property(copy) id connectionResetBlock;


- (void)_remoteSessionConnectionWasInterrupted;
- (id)connectionResetBlock;
- (void)registerGuaranteedRemoteCall:(id)arg1;
- (void)dropGuaraneteedRemoteCall:(id)arg1;
- (id)initForRemoteServiceName:(id)arg1 remoteInterface:(id)arg2;
- (void)setConnectionResetBlock:(id)arg1;
- (void)_setupConnection;
- (void)disconnect;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (void)dealloc;
- (void).cxx_destruct;
- (void)setExportedInterface:(id)arg1;
- (id)exportedInterface;
- (id)exportedObject;
- (void)setExportedObject:(id)arg1;

@end
