/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WelcomeKitUI.framework/WelcomeKitUI
 */

@interface WLPairingCodeTableViewController : WLBuddyPaneViewController <UITableViewDataSource, UITableViewDelegate, WLDeviceAuthenticationDelegate, WLSourceDevicesDelegate> {
    WLDeviceAuthentication * _auth;
    WLDeviceAuthenticationController * _authController;
    NSString * _pairingCode;
    UITableViewCell * _pairingCodeCell;
    WLSourceDevice * _sourceDevice;
    WLSourceDevicesController * _sourceDevicesController;
    UIActivityIndicatorView * _spinner;
    NSString * _ssid;
    UIButton * _wifiInfoButton;
    NSString * _wifiPSK;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned int hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_authenticateWithMigrationFromSourceDevice:(id)arg1;
- (id)_pairingCodeCell;
- (id)_spinner;
- (void)authenticator:(id)arg1 didCalculateSecurityCode:(id)arg2;
- (void)authenticator:(id)arg1 didFailWithError:(id)arg2;
- (void)authenticator:(id)arg1 didFinishWithAuthentication:(id)arg2;
- (float)heightForFooterInTableView:(id)arg1;
- (id)init;
- (void)loadView;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)showDirectConnectionUI;
- (void)sourceDevices:(id)arg1 didChangeWithDevices:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (id)viewForFooterInTableView:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)wifiInfoTapped:(id)arg1;

@end
