/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@class FCRFaceDetector, NSArray, NSMutableArray, NSMutableDictionary;

@interface CIBurstImageFaceAnalysisContext : NSObject  {
    NSMutableDictionary *curConfig;
    NSMutableDictionary *faceIdMapping;
    NSMutableDictionary *renameMapping;
    int faceIdCounter;
    FCRFaceDetector *faceDetector;
    NSArray *faces;
    double timeOfLastAnalyzedFrame;
    double timeBlinkDetectionDone;
    double timeFaceDetectionDone;
    BOOL forceFaceDetectionEnable;
    NSMutableArray *faceTimestampArray;
    double latestFaceTimestamp;
    double latestImageTimestamp;
    int lastFaceIndex;
}

@property double timeFaceDetectionDone;
@property double timeBlinkDetectionDone;
@property BOOL forceFaceDetectionEnable;
@property double latestFaceTimestamp;


- (void)setLatestFaceTimestamp:(double)arg1;
- (double)latestFaceTimestamp;
- (void)setForceFaceDetectionEnable:(BOOL)arg1;
- (BOOL)forceFaceDetectionEnable;
- (void)setTimeFaceDetectionDone:(double)arg1;
- (double)timeFaceDetectionDone;
- (void)setTimeBlinkDetectionDone:(double)arg1;
- (double)timeBlinkDetectionDone;
- (void)addFacesToImageStat:(id)arg1 imageSize:(struct CGSize { float x1; float x2; })arg2;
- (void)extractFacesFromMetadata:(id)arg1;
- (void)adjustFaceIdsForImageStat:(id)arg1;
- (void)calcFaceScores:(id)arg1;
- (void)calculateFaceFocusInImage:(id)arg1 imageStat:(id)arg2;
- (int)findFacesInImage:(id)arg1 imageStat:(id)arg2;
- (void)addFaceToArray:(id)arg1;
- (void)setupFaceDetector;
- (id)init;
- (void)dealloc;

@end
