/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CITwelvefoldReflectedTile : CITileFilter  {
}

+ (id)customAttributes;

- (id)_kernel_source;
- (id)_kernel_name;
- (id)outputImage;

@end
