/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PlugInKit.framework/PlugInKit
 */

@class NSString;

@interface PKSandboxExtension : NSObject  {
    NSString *_token;
    long long _handle;
}

@property(retain) NSString * token;
@property long long handle;


- (void)setHandle:(long long)arg1;
- (id)token;
- (long long)handle;
- (void)setToken:(id)arg1;
- (void)expel;
- (void)consume;
- (id)initWithExtension:(id)arg1;
- (void)dealloc;
- (void).cxx_destruct;

@end
