/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/introspection/libdispatch.dylib
 */

@interface OS_dispatch_queue_attr : OS_dispatch_object <OS_dispatch_queue_attr> {
}

+ (void)load;


@end
