/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/DataAccessExpress.framework/DataAccessExpress
 */

@class NSString;

@interface DAContactsSearchQuery : DASearchQuery  {
    NSString *_searchBase;
    NSString *_searchScope;
    BOOL _includePhotos;
}

@property(retain) NSString * searchBase;
@property(retain) NSString * searchScope;
@property BOOL includePhotos;

+ (id)contactsSearchQueryWithSearchString:(id)arg1 searchBase:(id)arg2 searchScope:(id)arg3 consumer:(id)arg4;

- (BOOL)includePhotos;
- (id)searchScope;
- (id)searchBase;
- (void)setIncludePhotos:(BOOL)arg1;
- (void)setSearchScope:(id)arg1;
- (void)setSearchBase:(id)arg1;
- (id)initWithSearchString:(id)arg1 searchBase:(id)arg2 searchScope:(id)arg3 consumer:(id)arg4;
- (id)initWithDictionaryRepresentation:(id)arg1 consumer:(id)arg2;
- (void)dealloc;
- (id)dictionaryRepresentation;

@end
