/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/DataAccessExpress.framework/DataAccessExpress
 */

@class NSString, <DAFolderChangeConsumer>;

@interface DAFolderChange : NSObject <NSSecureCoding> {
    bool_renameOnCollision;
    unsigned int _taskId;
    long long _changeType;
    NSString *_folderId;
    NSString *_parentFolderId;
    NSString *_displayName;
    long long _dataclass;
    <DAFolderChangeConsumer> *_consumer;
}

@property long long changeType;
@property(retain) NSString * folderId;
@property(retain) NSString * parentFolderId;
@property(retain) NSString * displayName;
@property long long dataclass;
@property unsigned int taskId;
@property bool renameOnCollision;
@property <DAFolderChangeConsumer> * consumer;

+ (bool)supportsSecureCoding;

- (void)setTaskId:(unsigned int)arg1;
- (unsigned int)taskId;
- (id)initFolderChangeWithChangeType:(long long)arg1 folderId:(id)arg2 parentFolderId:(id)arg3 displayName:(id)arg4 dataclass:(long long)arg5 consumer:(id)arg6;
- (bool)renameOnCollision;
- (void)setRenameOnCollision:(bool)arg1;
- (id)parentFolderId;
- (id)folderId;
- (void)setDataclass:(long long)arg1;
- (void)setParentFolderId:(id)arg1;
- (void)setConsumer:(id)arg1;
- (void)setDisplayName:(id)arg1;
- (void)setFolderId:(id)arg1;
- (id)consumer;
- (long long)dataclass;
- (void)setChangeType:(long long)arg1;
- (long long)changeType;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void).cxx_destruct;
- (id)description;
- (id)displayName;
- (id)mf_deferredOperation;

@end
