/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/PhotosUI.framework/PhotosUI
 */

@interface PUAudioSessionCategoryToken : NSObject {
    PUAudioSessionController * _audioSessionController;
    NSString * _category;
    unsigned int  _categoryOptions;
    BOOL  _valid;
}

@property (nonatomic, readonly, copy) NSString *category;
@property (nonatomic, readonly) unsigned int categoryOptions;
@property (getter=isValid, nonatomic) BOOL valid;

- (void).cxx_destruct;
- (id)_initWithCategory:(id)arg1 options:(unsigned int)arg2 audioSessionController:(id)arg3;
- (void)_setValid:(BOOL)arg1;
- (id)category;
- (unsigned int)categoryOptions;
- (id)description;
- (void)invalidate;
- (BOOL)isValid;
- (void)setCategory:(id)arg1 withOptions:(unsigned int)arg2;

@end
