/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ABLE.framework/ABLE
 */

@interface ABLECDNotificationResponse : NSManagedObject

@property (nonatomic, retain) NSNumber *batteryLevel;
@property (nonatomic, retain) NSDate *chargeDate;
@property (nonatomic, retain) NSDate *currentDate;
@property (nonatomic, retain) NSNumber *isTraveling;
@property (nonatomic, retain) NSNumber *userResponse;
@property (nonatomic, retain) NSDate *zeroDate;

@end
