/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/GameKitServices.framework/Frameworks/AVConference.framework/AVConference
 */

@class NSString;

@interface AVPingTest : NSObject  {
    NSString *ipAsString;
    BOOL usingWifi;
    NSString *interfaceNameToTest;
    float min;
    float max;
    float avg;
    float stddev;
    float packetLossRate;
    int lastReturnedError;
}

@property(readonly) BOOL usingWifi;
@property(readonly) float min;
@property(readonly) float max;
@property(readonly) float avg;
@property(readonly) float stddev;
@property(readonly) float packetLossRate;


- (BOOL)parsePingLineForLatencyStats:(char *)arg1;
- (BOOL)parsePingLineForPLR:(char *)arg1;
- (BOOL)parsePingLineForBadCommand:(char *)arg1;
- (BOOL)parsePingLineForBadInterface:(char *)arg1;
- (float)stddev;
- (float)avg;
- (BOOL)usingWifi;
- (id)initWithIPAsString:(id)arg1 usingWifi:(BOOL)arg2;
- (int)parseResults:(char *)arg1 secondLastLine:(char *)arg2;
- (void)calculateInterfaceName;
- (float)packetLossRate;
- (float)min;
- (void)dealloc;
- (id)description;
- (float)max;
- (int)start;

@end
