/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/GameKitServices.framework/Frameworks/AVConference.framework/AVConference
 */

@interface FFTMeter : NSObject  {
    struct vDSP_DFT_SetupStruct { } *fftSetup;
    struct DSPSplitComplex { 
        float *realp; 
        float *imagp; 
    } dspSplitComplex;
    float sampleHistory[3840];
    float magnitudeBuffer[1920];
    float fftBuffer[3840];
    float windowBuffer[3840];
    float windowHistory[3840];
    float octaveDbOld[54];
    float octaveDb[54];
    float octaveDbFilt[55];
    float lerpIdxs[66];
    float fftNormFactor;
    float adjust0DB;
}


- (id)computeWithSampleBuffer:(char *)arg1 numSamples:(unsigned long long)arg2 voiceActive:(bool)arg3;
- (id)init;
- (void)dealloc;

@end
