/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/GameKitServices.framework/Frameworks/AVConference.framework/AVConference
 */

@class NSMutableDictionary;

@interface SIPClientDataDictionary : NSObject  {
    NSMutableDictionary *allCalls;
}


- (void)setObject:(id)arg1 forKey:(id)arg2 forP2PID:(unsigned int)arg3;
- (id)objectForKey:(id)arg1 p2pID:(unsigned int)arg2;
- (id)init;
- (void)dealloc;

@end
