/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/ITMLKit.framework/ITMLKit
 */

@interface IKDOMEventDispatcher : NSObject  {
}

+ (id)sharedInstance;

- (bool)_runPhase:(long long)arg1 event:(id)arg2 nodeEn:(id)arg3;
- (bool)dispatchEvent:(id)arg1;

@end
