/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/Message.framework/Message
 */

@interface MFAttachmentLibraryManager : MFAttachmentComposeManager  {
}


- (id)initWithPrimaryLibrary:(id)arg1;
- (void)removeProviderForBaseURL:(id)arg1;
- (id)_dataProviderForAttachmentURL:(id)arg1 error:(id*)arg2;

@end
