/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AddressBook.framework/AddressBook
 */

@interface ABVCardActivityAlertSerialization : NSObject  {
}

+ (id)infoFromDictionary:(id)arg1;
+ (id)typeFromDictionary:(id)arg1;
+ (id)activityAlertWithString:(id)arg1;
+ (id)dictionaryWithType:(id)arg1 info:(id)arg2;
+ (void)parseString:(id)arg1 intoTypeAndInfo:(id)arg2;
+ (id)stringWithType:(id)arg1 info:(id)arg2;


@end
