/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/MultipeerConnectivity.framework/MultipeerConnectivity
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class NSString, NSProgress;

@interface MCResourceProgressObserver : NSObject  {
    NSString *_name;
    NSProgress *_progress;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _cancelHandler;

}

@property(copy) NSString * name;
@property(retain) NSProgress * progress;
@property(copy) id cancelHandler;


- (id)initWithName:(id)arg1 progress:(id)arg2 cancelHandler:(id)arg3;
- (void)setName:(id)arg1;
- (id)cancelHandler;
- (void)setCancelHandler:(id)arg1;
- (id)name;
- (void)invalidate;
- (void)dealloc;
- (void)setProgress:(id)arg1;
- (id)progress;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;

@end
