/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface NSAttributeStoreMapping : NSPropertyStoreMapping  {
    int _externalType;
    unsigned int _externalPrecision;
    int _externalScale;
}


- (id)columnDefinition;
- (int)externalScale;
- (unsigned int)externalPrecision;
- (int)externalType;
- (void)setExternalScale:(int)arg1;
- (void)setExternalPrecision:(unsigned int)arg1;
- (void)setExternalType:(int)arg1;
- (id)initWithProperty:(id)arg1;
- (id)sqlType;
- (bool)isEqual:(id)arg1;
- (id)attribute;

@end
