/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface NSSQLAttribute : NSSQLColumn  {
}


- (BOOL)shouldIndex;
- (id)initForReadOnlyFetchWithExpression:(id)arg1;
- (unsigned int)_sqlTypeForAttributeType:(unsigned int)arg1 flags:(unsigned int)arg2;
- (id)initWithEntity:(id)arg1 propertyDescription:(id)arg2;
- (id)attributeDescription;

@end
