/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class SKUICountdown, SKUIItem, NSString, NSURL, NSDictionary, NSNumber;

@interface SKUILink : NSObject <SSMetricsEventFieldProvider> {
    SKUICountdown *_countdown;
    SKUIItem *_item;
    NSNumber *_itemIdentifier;
    NSString *_target;
    NSString *_title;
    NSURL *_url;
}

@property(getter=isActionable,readonly) bool actionable;
@property(readonly) SKUIItem * item;
@property(readonly) NSNumber * itemIdentifier;
@property(readonly) NSDictionary * linkDictionary;
@property(readonly) NSString * targetString;
@property(readonly) NSString * title;
@property(readonly) NSURL * URL;


- (id)initWithLinkDictionary:(id)arg1;
- (id)initWithURL:(id)arg1 title:(id)arg2 targetString:(id)arg3;
- (id)initWithComponentContext:(id)arg1;
- (void)_setItem:(id)arg1;
- (id)linkDictionary;
- (id)targetString;
- (bool)isActionable;
- (id)valueForMetricsField:(id)arg1;
- (id)itemIdentifier;
- (id)title;
- (id)initWithURL:(id)arg1;
- (id)URL;
- (void).cxx_destruct;
- (id)item;

@end
