/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class UIView;

@interface SKUIGiftTermsAndConditionsSection : SKUIGiftTableViewSection  {
    UIView *_headerView;
}


- (void)_termsAction:(id)arg1;
- (id)headerViewForTableView:(id)arg1;
- (id)_headerView;
- (void).cxx_destruct;

@end
