/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class NSArray, NSMutableIndexSet, UICollectionView, NSString, SKUISwooshView;

@interface SKUIBrickSwooshViewController : SKUISwooshViewController <UICollectionViewDataSource, UICollectionViewDelegate> {
    NSArray *_bricks;
    UICollectionView *_collectionView;
    bool_delegateWantsWillDisplay;
    NSMutableIndexSet *_hiddenImageIndexSet;
    struct { 
        double cellHeight; 
        double cellWidth; 
        double interItemSpacing; 
    } _metrics;
    bool_showBrickTitles;
    NSString *_swooshTitle;
    SKUISwooshView *_swooshView;
}

@property(copy) NSArray * bricks;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (void)unhideImages;
- (id)popImageViewForItemAtIndex:(long long)arg1;
- (struct { double x1; double x2; double x3; })_brickSwooshMetrics;
- (id)initWithSwoosh:(id)arg1;
- (void)deselectAllItems;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })frameForItemAtIndex:(long long)arg1;
- (void)setBricks:(id)arg1;
- (void)setImage:(id)arg1 forItemAtIndex:(long long)arg2;
- (id)bricks;
- (void)setColorScheme:(id)arg1;
- (void)setClientContext:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (void).cxx_destruct;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (id)indexPathsForVisibleItems;
- (void)viewWillAppear:(bool)arg1;
- (struct CGSize { double x1; double x2; })collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)loadView;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;

@end
