/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class SKUIMetricsController, SKUIResourceLoader, NSMutableArray, UIScrollView, NSString, SSVPlatformRequestOperation, NSOperationQueue, NSArray, SKUIClientContext, SKUIColorScheme, <SKUIProductPageChildViewControllerDelegate>, SKUIProductPageHeaderViewController;

@interface SKUISwooshArrayViewController : UIViewController <SKUIMetricsViewController, SKUIResourceLoaderDelegate, SKUISwooshViewControllerDelegate, UIScrollViewDelegate, SKUIProductPageChildViewController> {
    bool_askPermission;
    SKUIResourceLoader *_artworkLoader;
    SKUIClientContext *_clientContext;
    SKUIColorScheme *_colorScheme;
    <SKUIProductPageChildViewControllerDelegate> *_delegate;
    SKUIProductPageHeaderViewController *_headerViewController;
    SKUIMetricsController *_metricsController;
    NSOperationQueue *_operationQueue;
    SSVPlatformRequestOperation *_platformOperation;
    UIScrollView *_scrollView;
    NSMutableArray *_swooshArtworkLoaders;
    NSArray *_swooshComponents;
    NSMutableArray *_viewControllers;
}

@property(copy) NSArray * swooshComponents;
@property(retain) SKUIClientContext * clientContext;
@property(retain) SKUIMetricsController * metricsController;
@property(retain) SKUIColorScheme * colorScheme;
@property <SKUIProductPageChildViewControllerDelegate> * delegate;
@property(retain) NSOperationQueue * operationQueue;
@property bool askPermission;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;
@property(readonly) UIScrollView * scrollView;
@property(retain) SKUIProductPageHeaderViewController * headerViewController;


- (id)swooshComponents;
- (bool)askPermission;
- (void)setSwooshComponents:(id)arg1;
- (void)loadMissingItemData;
- (id)initWithSwooshComponents:(id)arg1;
- (void)setHeaderViewController:(id)arg1;
- (id)headerViewController;
- (void)_addMissingItemsWithResponse:(id)arg1 error:(id)arg2;
- (void)_layoutSwooshViews;
- (id)_clickEventForSeeAllForViewController:(id)arg1;
- (id)_clickEventWithItem:(id)arg1;
- (void)_addHeaderView;
- (void)_reloadChildViewControllers;
- (void)_loadMissingItemsIfNecessary;
- (void)swooshDidSelectSeeAll:(id)arg1;
- (void)swoosh:(id)arg1 didSelectCellAtIndex:(long long)arg2;
- (id)swoosh:(id)arg1 imageForCellAtIndex:(long long)arg2;
- (id)_artworkLoader;
- (id)activeMetricsController;
- (void)artworkLoaderDidIdle:(id)arg1;
- (void)setMetricsController:(id)arg1;
- (id)metricsController;
- (void)setAskPermission:(bool)arg1;
- (void)setColorScheme:(id)arg1;
- (id)colorScheme;
- (void)setClientContext:(id)arg1;
- (id)clientContext;
- (id)_scrollView;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)dealloc;
- (void).cxx_destruct;
- (id)operationQueue;
- (bool)isLoaded;
- (id)scrollView;
- (void)viewWillAppear:(bool)arg1;
- (void)setOperationQueue:(id)arg1;
- (void)loadView;
- (void)scrollViewDidScroll:(id)arg1;

@end
