/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class SKUILabelViewElement, NSString, SKUIURLViewElement, NSURL, SKUIImageViewElement;

@interface SKUIShareSheetActivityViewElement : SKUIViewElement  {
    NSString *_activityType;
    NSURL *_contentSourceURL;
}

@property(readonly) NSString * activityType;
@property(readonly) NSURL * contentSourceURL;
@property(readonly) SKUIImageViewElement * image;
@property(readonly) SKUILabelViewElement * message;
@property(readonly) SKUILabelViewElement * title;
@property(readonly) SKUIURLViewElement * URL;


- (id)initWithDOMElement:(id)arg1 parent:(id)arg2 elementFactory:(id)arg3;
- (id)applyUpdatesWithElement:(id)arg1;
- (id)contentSourceURL;
- (id)message;
- (id)title;
- (id)activityType;
- (id)image;
- (id)URL;
- (void).cxx_destruct;

@end
