/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class SKUISegmentedTableHeaderView, NSArray, SKUIResourceLoader, UISegmentedControl, NSMutableDictionary, SKUIClientContext, NSOperationQueue, <SKUIChartsViewControllerDelegate>;

@interface SKUIIPhoneChartsViewController : UIViewController <SKUIItemListTableDelegate> {
    SKUIResourceLoader *_artworkLoader;
    NSArray *_charts;
    NSMutableDictionary *_chartViewControllers;
    SKUIClientContext *_clientContext;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    } _contentInset;
    <SKUIChartsViewControllerDelegate> *_delegate;
    bool_delegateWantsWillDisplay;
    SKUISegmentedTableHeaderView *_headerView;
    NSOperationQueue *_operationQueue;
    long long _selectedChartIndex;
    UISegmentedControl *_segmentedControl;
}

@property(retain) SKUIResourceLoader * artworkLoader;
@property(copy) NSArray * charts;
@property(retain) SKUIClientContext * clientContext;
@property struct UIEdgeInsets { double x1; double x2; double x3; double x4; } contentInset;
@property <SKUIChartsViewControllerDelegate> * delegate;


- (id)_selectedViewController;
- (id)_viewControllerWithIndex:(long long)arg1;
- (long long)_chartIndexForChartViewController:(id)arg1;
- (void)_showSelectedViewController;
- (id)_artworkContextForChart:(id)arg1;
- (id)_itemListWithChart:(id)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })frameForItemIndex:(long long)arg1 chartIndex:(long long)arg2;
- (void)setCharts:(id)arg1;
- (void)enumerateVisibleItemsUsingBlock:(id)arg1;
- (void)itemList:(id)arg1 didSelectItem:(id)arg2 atIndexPath:(id)arg3;
- (id)itemList:(id)arg1 didConfirmItemOfferForItem:(id)arg2 atIndexPath:(id)arg3;
- (void)itemList:(id)arg1 willDisplayCellForItem:(id)arg2 atIndexPath:(id)arg3;
- (void)setArtworkLoader:(id)arg1;
- (void)loadNextPageOfArtworkWithReason:(long long)arg1;
- (void)_segmentedControlAction:(id)arg1;
- (id)charts;
- (id)artworkLoader;
- (void)setClientContext:(id)arg1;
- (id)clientContext;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)dealloc;
- (void).cxx_destruct;
- (void)_reloadData;
- (void)viewWillAppear:(bool)arg1;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)setContentInset:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })contentInset;
- (void)viewDidLayoutSubviews;

@end
