/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class NSOperationQueue;

@interface SKUIStarRatingQueue : NSObject  {
    NSOperationQueue *_queue;
}


- (void)_setRating:(int)arg1 forItem:(id)arg2 account:(id)arg3 completionBlock:(id)arg4;
- (void)setRating:(int)arg1 forItem:(id)arg2 completionBlock:(id)arg3;
- (id)init;
- (void).cxx_destruct;

@end
