/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class NSString, SKUIDividerViewElement, NSArray;

@interface SKUISegmentedControlViewElement : SKUIViewElement  {
    long long _maximumNumberOfVisibleItems;
    NSString *_moreListTitle;
}

@property(readonly) SKUIDividerViewElement * bottomDivider;
@property(readonly) long long initialSelectedItemIndex;
@property(readonly) long long maximumNumberOfVisibleItems;
@property(readonly) NSString * moreListTitle;
@property(readonly) NSArray * segmentItemTitles;


- (id)moreListTitle;
- (id)initWithDOMElement:(id)arg1 parent:(id)arg2 elementFactory:(id)arg3;
- (id)applyUpdatesWithElement:(id)arg1;
- (void)_enumerateItemElementsUsingBlock:(id)arg1;
- (long long)maximumNumberOfVisibleItems;
- (long long)initialSelectedItemIndex;
- (id)segmentItemTitles;
- (void)dispatchEventOfType:(unsigned long long)arg1 forItemAtIndex:(long long)arg2;
- (id)bottomDivider;
- (long long)pageComponentType;
- (void).cxx_destruct;

@end
