/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class SKUIItemState, SSLookupItemOffer, UIImage, UILabel, UIControl, SKUIClientContext, UIButton, UIView, NSArray, NSString, UIImageView, NSMutableArray;

@interface SKUIBannerView : UIView  {
    UILabel *_artistNameLabel;
    UIView *_bottomBorderView;
    SKUIClientContext *_clientContext;
    UIButton *_closeButton;
    UIImageView *_iconImageView;
    SSLookupItemOffer *_itemOffer;
    UIButton *_itemOfferButton;
    SKUIItemState *_itemState;
    UILabel *_itemStateLabel;
    NSMutableArray *_screenshotImageViews;
    UIView *_separatorView;
    UILabel *_titleLabel;
    float _userRating;
    UIImageView *_userRatingStarImageView;
}

@property(retain) SKUIClientContext * clientContext;
@property(retain) UIImage * iconImage;
@property(copy) NSArray * screenshotImages;
@property(copy) NSString * artistName;
@property(copy) NSString * title;
@property float userRating;
@property(retain) SSLookupItemOffer * itemOffer;
@property(retain) SKUIItemState * itemState;
@property(readonly) UIControl * closeButton;
@property(readonly) UIControl * itemOfferButton;


- (id)itemOfferButton;
- (id)itemState;
- (id)itemOffer;
- (id)screenshotImages;
- (void)_reloadItemState;
- (void)setItemOffer:(id)arg1;
- (void)setScreenshotImages:(id)arg1;
- (void)setItemState:(id)arg1;
- (id)closeButton;
- (id)_newDefaultLabel;
- (void)setUserRating:(float)arg1;
- (float)userRating;
- (void)setClientContext:(id)arg1;
- (id)clientContext;
- (void)setIconImage:(id)arg1;
- (void)setArtistName:(id)arg1;
- (id)artistName;
- (void)setTitle:(id)arg1;
- (id)title;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void).cxx_destruct;
- (id)iconImage;
- (struct CGSize { float x1; float x2; })sizeThatFits:(struct CGSize { float x1; float x2; })arg1;
- (void)layoutSubviews;
- (id)hitTest:(struct CGPoint { float x1; float x2; })arg1 withEvent:(id)arg2;

@end
