/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class NSArray, SKUIViewReusePool;

@interface SKUIViewReuseView : UIView  {
    SKUIViewReusePool *_viewReusePool;
    NSArray *_views;
}

@property(readonly) NSArray * allExistingViews;


- (void)enumerateExistingViewsForReuseIdentifier:(id)arg1 usingBlock:(id)arg2;
- (void)registerClass:(Class)arg1 forViewWithReuseIdentifier:(id)arg2;
- (id)allExistingViews;
- (void)modifyUsingBlock:(id)arg1;
- (void)setBackgroundColor:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void).cxx_destruct;

@end
