/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class SKUIImageViewElement, NSArray;

@interface SKUIBrowseItemViewElement : SKUIItemViewElement  {
    bool_expands;
}

@property(readonly) SKUIImageViewElement * decorationImage;
@property(readonly) bool expands;
@property(readonly) NSArray * metadata;


- (id)initWithDOMElement:(id)arg1 parent:(id)arg2 elementFactory:(id)arg3;
- (id)applyUpdatesWithElement:(id)arg1;
- (bool)expands;
- (long long)pageComponentType;
- (id)decorationImage;
- (id)metadata;

@end
