/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
 */

@class NSString, NSArray, SKUIItemOffer, NSURL, NSMutableDictionary, SKUIArtworkList;

@interface SKUIItem : NSObject <SKUICacheCoding, SSMetricsEventFieldProvider> {
    struct _NSRange { 
        unsigned long long location; 
        unsigned long long length; 
    } _ageBandRange;
    NSString *_artistName;
    SKUIArtworkList *_artworks;
    NSString *_bundleID;
    NSString *_categoryName;
    NSString *_collectionName;
    unsigned long long _deviceFamilies;
    NSString *_editorialBage;
    long long _itemIdentifier;
    long long _itemKind;
    NSString *_itemKindString;
    SKUIItemOffer *_itemOffer;
    bool_newsstandApp;
    bool_hasInAppPurchases;
    long long _newsstandBindingEdge;
    long long _newsstandBindingType;
    SKUIArtworkList *_newsstandArtworks;
    long long _numberOfChildItems;
    long long _numberOfUserRatings;
    long long _parentalControlsRank;
    bool_prerenderedArtwork;
    NSString *_productPageURLString;
    NSArray *_requiredCapabilities;
    NSString *_title;
    float _userRating;
    long long _versionIdentifier;
    NSString *_versionString;
    NSArray *_videos;
    NSString *_editorialBadge;
}

@property(readonly) struct _NSRange { unsigned long long x1; unsigned long long x2; } ageBandRange;
@property(readonly) NSString * artistName;
@property(readonly) NSString * bundleIdentifier;
@property(readonly) NSURL * largestArtworkURL;
@property(readonly) SKUIArtworkList * artworks;
@property(readonly) NSArray * childItemIdentifiers;
@property(readonly) NSArray * loadedChildItems;
@property(readonly) long long numberOfChildItems;
@property(readonly) unsigned long long deviceFamilies;
@property(getter=hasPrerenderedArtwork,readonly) bool prerenderedArtwork;
@property(readonly) NSString * categoryName;
@property(readonly) NSString * collectionName;
@property(readonly) NSString * editorialBadge;
@property(readonly) long long itemIdentifier;
@property(readonly) long long itemKind;
@property(readonly) NSString * itemKindString;
@property(readonly) long long numberOfUserRatings;
@property(readonly) long long parentalControlsRank;
@property(readonly) SKUIItemOffer * primaryItemOffer;
@property(readonly) NSString * productPageURLString;
@property(readonly) NSArray * requiredCapabilities;
@property(readonly) float userRating;
@property(readonly) NSString * title;
@property(readonly) long long versionIdentifier;
@property(readonly) NSString * versionString;
@property(readonly) NSArray * videos;
@property(readonly) bool hasInAppPurchases;
@property(getter=isNewsstandApp,readonly) bool newsstandApp;
@property(readonly) long long newsstandBindingEdge;
@property(readonly) long long newsstandBindingType;
@property(readonly) SKUIArtworkList * newsstandArtworks;
@property(readonly) NSString * _downloadKind;
@property(readonly) NSMutableDictionary * cacheRepresentation;


- (id)productPageURLString;
- (long long)numberOfUserRatings;
- (id)videos;
- (long long)newsstandBindingType;
- (long long)newsstandBindingEdge;
- (id)editorialBadge;
- (void)_setHasInAppPurchases:(bool)arg1;
- (void)addItemOfferParameterWithName:(id)arg1 value:(id)arg2;
- (id)largestArtworkURL;
- (id)childItemForIdentifier:(id)arg1;
- (id)initContainerItemWithItem:(id)arg1;
- (id)newsstandArtworks;
- (unsigned long long)deviceFamilies;
- (long long)numberOfChildItems;
- (id)itemKindString;
- (bool)hasInAppPurchases;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })ageBandRange;
- (id)categoryName;
- (id)artworks;
- (id)loadedChildItems;
- (id)childItemIdentifiers;
- (id)artworkURLForSize:(long long)arg1;
- (bool)hasPrerenderedArtwork;
- (id)_downloadKind;
- (id)primaryItemOffer;
- (long long)parentalControlsRank;
- (id)cacheRepresentation;
- (id)initWithCacheRepresentation:(id)arg1;
- (id)lookupDictionary;
- (id)initWithLookupDictionary:(id)arg1;
- (id)valueForMetricsField:(id)arg1;
- (long long)itemKind;
- (id)artistName;
- (id)collectionName;
- (long long)itemIdentifier;
- (float)userRating;
- (id)requiredCapabilities;
- (long long)versionIdentifier;
- (id)bundleIdentifier;
- (bool)isNewsstandApp;
- (id)title;
- (id)versionString;
- (bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void).cxx_destruct;

@end
