/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/EventKit.framework/EventKit
 */

@class NSDate;

@interface EKDateRangePredicate : NSPredicate  {
    NSDate *_startDate;
    NSDate *_endDate;
}

@property(readonly) NSDate * startDate;
@property(readonly) NSDate * endDate;

+ (id)predicateWithStartDate:(id)arg1 endDate:(id)arg2;

- (id)initWithStartDate:(id)arg1 endDate:(id)arg2;
- (id)endDate;
- (id)startDate;
- (BOOL)isEqual:(id)arg1;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end
