/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/EventKit.framework/EventKit
 */

@class NSArray;

@interface EKPredicate : NSPredicate  {
    NSArray *_calendars;
}

@property(readonly) NSArray * calendars;


- (id)initWithCalendars:(id)arg1;
- (id)calendars;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end
