/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/SpringBoardFoundation.framework/SpringBoardFoundation
 */

@class NSMutableSet;

@interface SBFPasscodeLockAssertionTracker : NSObject  {
    void *_mkbAssertion;
    NSMutableSet *_assertions;
}


- (void)removeAssertion:(id)arg1;
- (bool)hasActiveAssertions;
- (id)mkbAssertionOptions;
- (void)addAssertion:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)description;

@end
