/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/PassKit.framework/PassKit
 */

@class PKVerificationRequestRecord, PKPassView, UILabel, UIView, UIButton;

@interface PKPassPaymentVerificationView : PKPassPaymentFooterContentView  {
    PKPassView *_passView;
    UILabel *_titleLabel;
    UILabel *_bodyLabel;
    UIButton *_button;
    UIButton *_alternateButton;
    UIView *_bottomRule;
    PKVerificationRequestRecord *_requestRecord;
}


- (id)_bodyLabel;
- (id)initWithPass:(id)arg1 passView:(id)arg2;
- (void)_completeVerificationButtonPressed:(id)arg1;
- (void)_enterCodeButtonPressed:(id)arg1;
- (id)_bodyStringForChannel:(id)arg1;
- (void)_bodyLabelTapped:(id)arg1;
- (id)_alternateButton;
- (void)sharedPaymentServiceChanged:(id)arg1;
- (id)_bottomRule;
- (void)reloadView;
- (void)dealloc;
- (id)_titleLabel;
- (id)_button;
- (void)layoutSubviews;

@end
