/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

@class CAStateControllerUndo, NSTimer, CALayer, NSMutableArray, CAState;

@interface CAStateControllerLayer : NSObject  {
    CALayer *_layer;
    CAState *_currentState;
    CAStateControllerUndo *_undoStack;
    NSMutableArray *_transitions;
    NSTimer *_nextTimer;
    CAState *_nextState;
    float _nextSpeed;
}

@property(readonly) CALayer * layer;
@property(retain) CAState * currentState;
@property(readonly) CAStateControllerUndo * undoStack;


- (id)undoStack;
- (id)layer;
- (void)removeTransition:(id)arg1;
- (void)addTransition:(id)arg1;
- (void)setCurrentState:(id)arg1;
- (id)initWithLayer:(id)arg1;
- (id)currentState;
- (void)invalidate;
- (void)dealloc;

@end
