/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/CoreThemeDefinition.framework/CoreThemeDefinition
 */

@class NSSet, TDRenditionType, TDThemeConstant, TDRenditionKeySpec, TDSchemaPartDefinition, NSString, TDNamedElement, NSDate, NSNumber;

@interface TDElementProduction : NSManagedObject  {
}

@property(retain) TDRenditionKeySpec * baseKeySpec;
@property(retain) TDRenditionType * renditionType;
@property(retain) TDThemeConstant * renditionSubtype;
@property(retain) TDThemeConstant * zeroCodeArtworkInfo;
@property(retain) NSString * comment;
@property(retain) NSDate * dateOfLastChange;
@property(retain) NSNumber * isExcludedFromFilter;
@property(retain) TDThemeConstant * artworkDraftType;
@property(retain) NSSet * renditions;
@property(retain) TDNamedElement * name;
@property(retain) TDSchemaPartDefinition * partDefinition;


- (void)deleteRenditionsInDocument:(id)arg1 shouldDeleteAssetFiles:(BOOL)arg2;
- (id)associatedFileURLWithDocument:(id)arg1;
- (id)associatedFileModificationDateWithDocument:(id)arg1;
- (id)relativePath;

@end
