/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class NSArray, NSString, NSNumber, NSURL;

@interface SAAlarmSearch : SADomainCommand  {
}

@property(copy) NSNumber * enabled;
@property(copy) NSArray * frequency;
@property(copy) NSNumber * hour;
@property(copy) NSURL * identifier;
@property(copy) NSString * label;
@property(copy) NSNumber * minute;

+ (id)searchWithDictionary:(id)arg1 context:(id)arg2;
+ (id)search;

- (BOOL)requiresResponse;
- (id)encodedClassName;
- (void)setFrequency:(id)arg1;
- (id)frequency;
- (id)label;
- (void)setEnabled:(id)arg1;
- (id)enabled;
- (id)minute;
- (id)hour;
- (void)setMinute:(id)arg1;
- (void)setHour:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (id)identifier;
- (void)setLabel:(id)arg1;
- (id)groupIdentifier;

@end
