/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class NSString, NSArray;

@interface SAAnswerSocialStructuredAnswer : AceObject <SAAnswerStructuredAnswer> {
}

@property(copy) NSString * category;
@property(copy) NSArray * socialQuestions;

+ (id)socialStructuredAnswerWithDictionary:(id)arg1 context:(id)arg2;
+ (id)socialStructuredAnswer;

- (void)setSocialQuestions:(id)arg1;
- (id)socialQuestions;
- (id)encodedClassName;
- (id)category;
- (void)setCategory:(id)arg1;
- (id)groupIdentifier;

@end
