/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class NSString, SAPerson, NSNumber, SALocation;

@interface SAFmfGeoFenceSet : SADomainCommand  {
}

@property(copy) NSNumber * enable;
@property(copy) NSString * fenceType;
@property(retain) SAPerson * friend;
@property(copy) NSString * geoFenceTrigger;
@property(copy) NSNumber * oneTimeOnly;
@property(retain) SALocation * requestedLocation;

+ (id)geoFenceSetWithDictionary:(id)arg1 context:(id)arg2;
+ (id)geoFenceSet;

- (void)setOneTimeOnly:(id)arg1;
- (id)oneTimeOnly;
- (void)setFenceType:(id)arg1;
- (id)fenceType;
- (void)setGeoFenceTrigger:(id)arg1;
- (id)geoFenceTrigger;
- (void)setRequestedLocation:(id)arg1;
- (id)requestedLocation;
- (void)setFriend:(id)arg1;
- (id)friend;
- (bool)requiresResponse;
- (id)encodedClassName;
- (void)setEnable:(id)arg1;
- (id)groupIdentifier;
- (id)enable;

@end
