/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class NSURL;

@interface SAFmfVisibilityView : SAUISnippet  {
}

@property(copy) NSURL * searchContext;
@property bool visible;

+ (id)visibilityViewWithDictionary:(id)arg1 context:(id)arg2;
+ (id)visibilityView;

- (id)encodedClassName;
- (id)searchContext;
- (void)setSearchContext:(id)arg1;
- (bool)visible;
- (void)setVisible:(bool)arg1;
- (id)groupIdentifier;

@end
