/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class NSArray, NSString, SADistance, NSNumber;

@interface SALocation : SADomainObject  {
}

@property(copy) NSNumber * accuracy;
@property(copy) NSString * city;
@property(copy) NSString * countryCode;
@property(copy) NSArray * entryPoints;
@property(copy) NSString * label;
@property(copy) NSNumber * latitude;
@property(copy) NSNumber * longitude;
@property(copy) NSString * postalCode;
@property(copy) NSString * regionType;
@property(retain) SADistance * relativeDistance;
@property(copy) NSString * stateCode;
@property(copy) NSString * street;
@property(copy) NSString * subThoroughfare;
@property(copy) NSString * thoroughfare;
@property(copy) NSString * timezoneId;

+ (id)locationWithDictionary:(id)arg1 context:(id)arg2;
+ (id)location;

- (void)setAccuracy:(id)arg1;
- (void)setStateCode:(id)arg1;
- (id)stateCode;
- (void)setRegionType:(id)arg1;
- (id)regionType;
- (void)setRelativeDistance:(id)arg1;
- (id)relativeDistance;
- (void)setTimezoneId:(id)arg1;
- (id)timezoneId;
- (void)updateUsingSet:(id)arg1 add:(id)arg2 remove:(id)arg3;
- (id)encodedClassName;
- (void)setPostalCode:(id)arg1;
- (id)postalCode;
- (void)setEntryPoints:(id)arg1;
- (id)entryPoints;
- (id)subThoroughfare;
- (id)thoroughfare;
- (void)setSubThoroughfare:(id)arg1;
- (void)setThoroughfare:(id)arg1;
- (id)accuracy;
- (void)setCity:(id)arg1;
- (void)setStreet:(id)arg1;
- (id)city;
- (id)street;
- (id)countryCode;
- (void)setCountryCode:(id)arg1;
- (id)label;
- (void)setLatitude:(id)arg1;
- (void)setLongitude:(id)arg1;
- (id)longitude;
- (id)latitude;
- (void)setLabel:(id)arg1;
- (id)groupIdentifier;

@end
