/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class NSString;

@interface SAMicroblogSocialCredential : AceObject <SABackgroundContextObject> {
}

@property(copy) NSString * accessToken;
@property(copy) NSString * socialNetwork;
@property(copy) NSString * tokenSecret;

+ (id)socialCredentialWithDictionary:(id)arg1 context:(id)arg2;
+ (id)socialCredential;

- (void)setAccessToken:(id)arg1;
- (void)setTokenSecret:(id)arg1;
- (id)tokenSecret;
- (void)setSocialNetwork:(id)arg1;
- (id)socialNetwork;
- (id)accessToken;
- (id)encodedClassName;
- (id)groupIdentifier;

@end
