/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@interface SAMPAudiobook : SAMPMediaItem  {
}

+ (id)audiobookWithDictionary:(id)arg1 context:(id)arg2;
+ (id)audiobook;

- (id)encodedClassName;
- (id)groupIdentifier;

@end
