/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class SASettingEntity;

@interface SASettingSetFloatResponse : SASettingSetNumberResponse  {
}

@property(retain) SASettingEntity * setting;

+ (id)setFloatResponseWithSetting:(id)arg1;
+ (id)setFloatResponseWithDictionary:(id)arg1 context:(id)arg2;
+ (id)setFloatResponse;

- (id)setting;
- (void)setSetting:(id)arg1;
- (id)initWithSetting:(id)arg1;
- (id)encodedClassName;
- (id)groupIdentifier;

@end
