/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class NSArray;

@interface SASmsSnippet : SAUISnippet  {
}

@property(copy) NSArray * smss;

+ (id)snippetWithDictionary:(id)arg1 context:(id)arg2;
+ (id)snippet;

- (void)setSmss:(id)arg1;
- (id)smss;
- (id)encodedClassName;
- (id)groupIdentifier;

@end
