/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class NSString;

@interface SASportsMatchupLineScore : AceObject <SAAceSerializable> {
}

@property(copy) NSString * period;
@property(copy) NSString * score;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;

+ (id)matchupLineScoreWithDictionary:(id)arg1 context:(id)arg2;
+ (id)matchupLineScore;

- (void)setPeriod:(id)arg1;
- (id)period;
- (id)encodedClassName;
- (void)setScore:(id)arg1;
- (id)score;
- (id)groupIdentifier;

@end
