/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class NSString;

@interface SAUIErrorSnippet : SAUISnippet  {
}

@property(copy) NSString * message;

+ (id)errorSnippetWithDictionary:(id)arg1 context:(id)arg2;
+ (id)errorSnippet;

- (id)encodedClassName;
- (void)setMessage:(id)arg1;
- (id)message;
- (id)groupIdentifier;

@end
