/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class SAUIConfirmationOptions;

@interface SAUISnippet : SAAceView  {
}

@property(retain) SAUIConfirmationOptions * confirmationOptions;

+ (id)snippetWithDictionary:(id)arg1 context:(id)arg2;
+ (id)snippet;

- (void)setConfirmationOptions:(id)arg1;
- (id)confirmationOptions;
- (id)encodedClassName;
- (id)groupIdentifier;

@end
