/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

@class NSNumber, SAWeatherCondition, NSString;

@interface SAWeatherForecast : AceObject <SAAceSerializable> {
}

@property(copy) NSNumber * chanceOfPrecipitation;
@property(retain) SAWeatherCondition * condition;
@property(copy) NSNumber * isUserRequested;
@property(copy) NSNumber * timeIndex;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;

+ (id)forecastWithDictionary:(id)arg1 context:(id)arg2;
+ (id)forecast;

- (void)setTimeIndex:(id)arg1;
- (id)timeIndex;
- (void)setChanceOfPrecipitation:(id)arg1;
- (id)chanceOfPrecipitation;
- (id)encodedClassName;
- (void)setIsUserRequested:(id)arg1;
- (id)isUserRequested;
- (id)condition;
- (id)groupIdentifier;
- (void)setCondition:(id)arg1;

@end
