/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@class PLAssetContainerListChangeNotification, NSIndexSet, PLFilteredAlbumList, PLIndexMapper;

@interface PLFilteredAlbumListChangeNotification : PLAssetContainerListChangeNotification <PLIndexMapperDataSource> {
    PLFilteredAlbumList *_albumList;
    NSIndexSet *_oldFilteredIndexes;
    NSIndexSet *_filteredIndexes;
    PLIndexMapper *_indexMapper;
    PLAssetContainerListChangeNotification *_backingNotification;
}

@property(readonly) NSIndexSet * updatedFilteredIndexes;
@property(copy) NSIndexSet * filteredIndexes;
@property(readonly) PLIndexMapper * indexMapper;

+ (id)notificationForDerivedObject:(id)arg1 priorChangeState:(id)arg2 forBackingObjectNotification:(id)arg3;

- (id)initWithFilteredAlbumList:(id)arg1 albumListChangeNotification:(id)arg2;
- (void)setFilteredIndexes:(id)arg1;
- (BOOL)countDidChange;
- (id)updatedFilteredIndexes;
- (id)_changedObjects;
- (BOOL)_getOldSet:(id*)arg1 newSet:(id*)arg2;
- (id)_diffDescription;
- (BOOL)shouldReload;
- (id)albumList;
- (id)indexMapper;
- (BOOL)shouldIncludeObjectAtIndex:(unsigned int)arg1;
- (id)filteredIndexes;
- (id)init;
- (id)object;
- (void)dealloc;
- (id)description;

@end
