/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@class NSNumber, NSMutableOrderedSet, PLManagedAsset, NSOrderedSet, NSURL, UIImage, NSString, NSDictionary, NSDate, NSArray;

@interface PLManagedAlbum : _PLManagedAlbum <PLUserEditableAlbumProtocol> {
    BOOL _resolvingConflicts;
    BOOL stackedImageNeedsUpdate;
    BOOL albumShouldBeAutomaticallyDeleted;
}

@property BOOL resolvingConflicts;
@property BOOL stackedImageNeedsUpdate;
@property BOOL albumShouldBeAutomaticallyDeleted;
@property(readonly) NSString * uuid;
@property(readonly) NSString * title;
@property(readonly) NSString * localizedTitle;
@property(readonly) NSOrderedSet * assets;
@property(readonly) unsigned int approximateCount;
@property(readonly) unsigned int assetsCount;
@property(readonly) unsigned int photosCount;
@property(readonly) unsigned int videosCount;
@property(readonly) BOOL isEmpty;
@property(retain) PLManagedAsset * keyAsset;
@property(readonly) BOOL canShowComments;
@property(readonly) NSArray * localizedLocationNames;
@property(readonly) NSDate * startDate;
@property(readonly) NSDate * endDate;
@property(readonly) NSNumber * kind;
@property(readonly) int kindValue;
@property(readonly) NSMutableOrderedSet * mutableAssets;
@property BOOL hasUnseenContentBoolValue;
@property(readonly) NSString * name;
@property(readonly) UIImage * posterImage;
@property(readonly) BOOL isLibrary;
@property(readonly) BOOL isCameraAlbum;
@property(readonly) BOOL isPanoramasAlbum;
@property(readonly) BOOL isWallpaperAlbum;
@property(readonly) BOOL isPhotoStreamAlbum;
@property(readonly) BOOL isCloudSharedAlbum;
@property(readonly) BOOL isPendingPhotoStreamAlbum;
@property(readonly) BOOL isStandInAlbum;
@property(readonly) BOOL isOwnedCloudSharedAlbum;
@property(readonly) BOOL isMultipleContributorCloudSharedAlbum;
@property(readonly) BOOL canContributeToCloudSharedAlbum;
@property(readonly) BOOL shouldDeleteWhenEmpty;
@property(retain) NSDictionary * slideshowSettings;
@property(retain) NSString * importSessionID;
@property(readonly) NSURL * groupURL;
@property(readonly) id sortingComparator;
@property(readonly) id sectioningComparator;
@property int pendingItemsCount;
@property int pendingItemsType;
@property(readonly) NSMutableOrderedSet * userEditableAssets;

+ (id)keyPathsForValuesAffectingVideosCount;
+ (id)keyPathsForValuesAffectingPhotosCount;
+ (id)keyPathsForValuesAffectingApproximateCount;
+ (id)assetOrderByAbumUUIDs;
+ (id)pathToAssetAlbumOrderStructure;
+ (BOOL)deviceSupportsStackedImages;
+ (void)clearAssetOrderByAbumUUIDs;

- (void)setResolvingConflicts:(BOOL)arg1;
- (BOOL)resolvingConflicts;
- (void)sortAssetsUsingiTunesAlbumOrder;
- (void)removePersistedFileSystemData;
- (void)replaceAssetsAtIndexes:(id)arg1 withAssets:(id)arg2;
- (void)removeAssetsAtIndexes:(id)arg1;
- (void)insertAssets:(id)arg1 atIndexes:(id)arg2;
- (unsigned int)_cachedCountForMigration;
- (void)removeInternalUserEditableAssetsAtIndexes:(id)arg1;
- (void)insertInternalUserEditableAssets:(id)arg1 atIndexes:(id)arg2;
- (id)internalUserEditableAssetsAtIndexes:(id)arg1;
- (void)getInternalUserEditableAssets:(id*)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2;
- (id)objectInInternalUserEditableAssetsAtIndex:(unsigned int)arg1;
- (unsigned int)indexInInternalUserEditableAssetsOfObject:(id)arg1;
- (unsigned int)countOfInternalUserEditableAssets;
- (id)userEditableAssets;
- (id)_orderComparisonValueForAsset:(id)arg1 iTunesLookupOrder:(id)arg2;
- (id)_assetOrderByAssetUUID;
- (void)_recalculateCachedCounts;
- (unsigned int)_albumStandInCount;
- (id)_keysToBeObserved;
- (id)_expectedKeyAsset;
- (BOOL)_shouldCopyAssetToCameraRollBeforeAdding:(id)arg1;
- (void)setAlbumShouldBeAutomaticallyDeleted:(BOOL)arg1;
- (BOOL)albumShouldBeAutomaticallyDeleted;
- (void)setStackedImageNeedsUpdate:(BOOL)arg1;
- (void)_handleStackedImageNeedsUpdate:(BOOL)arg1;
- (BOOL)stackedImageNeedsUpdate;
- (void)_updateKeyAssetIfNeeded;
- (void)persistMetadataToFileSystem;
- (void)refreshAssets;
- (void)addAssetUsingiTunesAlbumOrder:(id)arg1;
- (void)registerForChanges;
- (void)unregisterForChanges;
- (unsigned int)videosCount;
- (unsigned int)assetsCount;
- (unsigned int)approximateCount;
- (BOOL)canPerformEditOperation:(int)arg1;
- (id)mutableAssets;
- (id)filteredIndexesForPredicate:(id)arg1;
- (void)updateStackedImageShouldNotifyImmediately:(BOOL)arg1;
- (unsigned int)photosCount;
- (void)didSave;
- (void)awakeFromSnapshotEvents:(unsigned int)arg1;
- (BOOL)isEmpty;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;

@end
