/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@class NSString;

@interface PLQuotaRequest : AARequest  {
    NSString *_authToken;
    NSString *_personID;
}


- (id)initWithURLString:(id)arg1 authToken:(id)arg2 personID:(id)arg3;
- (id)urlRequest;
- (void)dealloc;

@end
