/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@class NSString;

@interface PLThumbFileManager : NSObject <PLThumbPersistenceManager> {
    int _format;
    struct CGSize { 
        double width; 
        double height; 
    } _thumbnailSize;
    NSString *_path;
    NSString *_filename;
    bool_readOnly;
    int _imageRowBytes;
    int _imageLength;
    int _entryLength;
}

@property(readonly) NSString * path;
@property(readonly) int imageFormat;
@property(readonly) int imageWidth;
@property(readonly) int imageHeight;
@property(readonly) int imageRowBytes;
@property(readonly) int imageLength;
@property(readonly) bool isReadOnly;
@property(readonly) struct CGSize { double x1; double x2; } imageSize;

+ (void)deleteAllEntriesWithIdentifier:(id)arg1 basePath:(id)arg2;

- (id)preheatItemForAsset:(id)arg1 format:(int)arg2 optimalSourcePixelSize:(struct CGSize { double x1; double x2; })arg3 options:(unsigned int)arg4;
- (void)_writeData:(id)arg1 forThumbIdentifier:(id)arg2;
- (void)_writeImage:(id)arg1 forThumbIdentifier:(id)arg2;
- (id)thumbnailForImage:(id)arg1 videoDuration:(id)arg2;
- (id)initWithPath:(id)arg1 imageFormat:(int)arg2;
- (id)thumbnailPathForThumbIdentifier:(id)arg1;
- (id)imageWithIdentifier:(id)arg1;
- (id)_debugDescription;
- (bool)usesThumbIdentifiers;
- (void)endThumbnailSafePropertyUpdatesOnAsset:(id)arg1 withToken:(id)arg2;
- (id)beginThumbnailSafePropertyUpdatesOnAsset:(id)arg1;
- (bool)copyEntryFromOriginalAsset:(id)arg1 toAsset:(id)arg2;
- (void)setImageDataForEntry:(const void*)arg1 withIdentifier:(id)arg2 orIndex:(unsigned long long)arg3 asset:(id)arg4;
- (void)setImageForEntry:(id)arg1 withIdentifier:(id)arg2 orIndex:(unsigned long long)arg3 videoDuration:(id)arg4 photoUUID:(id)arg5;
- (id)imageDataWithIdentifier:(id)arg1 orIndex:(unsigned long long)arg2 width:(int*)arg3 height:(int*)arg4 bytesPerRow:(int*)arg5 dataWidth:(int*)arg6 dataHeight:(int*)arg7 dataOffset:(int*)arg8;
- (int)imageRowBytes;
- (int)imageHeight;
- (int)imageWidth;
- (int)imageFormat;
- (int)imageLength;
- (id)initWithPath:(id)arg1 imageFormat:(int)arg2 readOnly:(bool)arg3;
- (bool)isReadOnly;
- (struct CGSize { double x1; double x2; })imageSize;
- (id)path;
- (void)dealloc;
- (id)description;

@end
