/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class _EditScriptRangedAtom, NSString;

@interface _EditScriptRanged : _EditScript  {
    long long _options;
    _EditScriptRangedAtom *_currentScriptAtom;
}

@property(readonly) NSString * stringA;
@property(readonly) NSString * stringB;

+ (id)editScriptForSmallestSingleEditFromString:(id)arg1 toString:(id)arg2;
+ (id)editScriptFromString:(id)arg1 toString:(id)arg2;
+ (id)editScriptFromString:(id)arg1 toString:(id)arg2 chunkSize:(long long)arg3 orderAtomsAscending:(bool)arg4 operationPrecedence:(long long)arg5 options:(long long)arg6;

- (void)dealloc;
- (id)applyToString:(id)arg1;
- (id)stringB;
- (id)stringA;
- (void)computeSmallestSingleEdit;
- (void)removeAnyOverlapBetweenIndexOfFirstDifference:(long long*)arg1 andReverseIndexOfLastDifference:(long long*)arg2 shouldShortenFirstDifference:(bool)arg3;
- (id)initWithOperationPrecedence:(long long)arg1 dataClass:(Class)arg2 chunkSize:(long long)arg3 stringA:(id)arg4 stringB:(id)arg5 orderAtomsAscending:(bool)arg6 options:(long long)arg7;
- (void)addToCurrentScriptAtomEditOperation:(long long)arg1 editIndex:(unsigned long long)arg2 newText:(id)arg3 indexInArrayB:(unsigned long long)arg4;
- (void)initializeCurrentScriptAtom;
- (void)finalizeCurrentScriptAtom;

@end
