/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIAttributeTraitStorage : _UITraitStorage  {
}


- (void)addRecordWithTraitCollection:(id)arg1 value:(id)arg2;
- (id)initWithObject:(id)arg1 keyPath:(id)arg2;
- (void)applyRecordsMatchingTraitCollection:(id)arg1;

@end
