/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@interface _UIDocumentPickerContainerModelUpdateHandler : NSObject  {
    id _weak_weakSelf;

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _handler;

}

@property id weakSelf;
@property(copy) id handler;


- (void)setHandler:(id)arg1;
- (id)handler;
- (void)dealloc;
- (id)weakSelf;
- (void)setWeakSelf:(id)arg1;

@end
