/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class <_UIDocumentPickerOverviewDelegate>, NSArray, NSString, _UIDocumentPickerViewServiceViewController;

@interface _UIDocumentPickerOverviewViewController : UITableViewController  {
    <_UIDocumentPickerOverviewDelegate> *_weak_delegate;
    NSArray *_allPickers;
    _UIDocumentPickerViewServiceViewController *_serviceViewController;
    NSString *_currentExtensionIdentifier;
    NSArray *_auxiliaryOptions;
}

@property <_UIDocumentPickerOverviewDelegate> * delegate;
@property(retain) NSArray * allPickers;
@property _UIDocumentPickerViewServiceViewController * serviceViewController;
@property(retain) NSString * currentExtensionIdentifier;
@property(retain) NSArray * auxiliaryOptions;


- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)dealloc;
- (id)currentExtensionIdentifier;
- (void)setCurrentExtensionIdentifier:(id)arg1;
- (void)setAllPickers:(id)arg1;
- (id)initWithFileTypes:(id)arg1 mode:(unsigned long long)arg2 auxiliaryOptions:(id)arg3 includeManagementItem:(bool)arg4;
- (id)allPickers;
- (id)auxiliaryOptions;
- (void)setAuxiliaryOptions:(id)arg1;
- (void)setServiceViewController:(id)arg1;
- (id)serviceViewController;
- (void)viewDidAppear:(bool)arg1;
- (void)viewWillAppear:(bool)arg1;
- (void)didMoveToParentViewController:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;

@end
