/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSMutableArray, _UIFlowLayoutSection;

@interface _UIFlowLayoutRow : NSObject  {
    NSMutableArray *_items;
    _UIFlowLayoutSection *_section;
    struct CGSize { 
        float width; 
        float height; 
    } _rowSize;
    struct CGRect { 
        struct CGPoint { 
            float x; 
            float y; 
        } origin; 
        struct CGSize { 
            float width; 
            float height; 
        } size; 
    } _rowFrame;
    int _index;
    BOOL _isValid;
    BOOL _complete;
    int _verticalAlignement;
    int _horizontalAlignement;
    BOOL _fixedItemSize;
}

@property _UIFlowLayoutSection * section;
@property struct CGSize { float x1; float x2; } rowSize;
@property struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; } rowFrame;
@property int index;
@property(readonly) NSMutableArray * items;
@property BOOL complete;
@property BOOL fixedItemSize;


- (void)setIndex:(int)arg1;
- (int)index;
- (id)items;
- (id)init;
- (void)invalidate;
- (void)dealloc;
- (BOOL)complete;
- (id)copyFromSection:(id)arg1;
- (void)setRowFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)layoutRow;
- (void)setComplete:(BOOL)arg1;
- (void)setSection:(id)arg1;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })rowFrame;
- (void)setFixedItemSize:(BOOL)arg1;
- (BOOL)fixedItemSize;
- (void)setRowSize:(struct CGSize { float x1; float x2; })arg1;
- (struct CGSize { float x1; float x2; })rowSize;
- (void)addItem:(id)arg1;
- (id)section;
- (id)snapshot;

@end
