/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString, UIFont;

@interface _UILegibilityLabel : _UILegibilityView  {
    bool_usesSecondaryColor;
    NSString *_string;
    UIFont *_font;
}

@property(copy) NSString * string;
@property(retain) UIFont * font;
@property(readonly) bool usesSecondaryColor;
@property(readonly) double baselineOffset;


- (id)font;
- (double)baselineOffset;
- (void)setString:(id)arg1;
- (id)string;
- (void)dealloc;
- (id)initWithSettings:(id)arg1 strength:(double)arg2 string:(id)arg3 font:(id)arg4;
- (id)initWithSettings:(id)arg1 strength:(double)arg2 string:(id)arg3 font:(id)arg4 options:(long long)arg5;
- (bool)usesSecondaryColor;
- (void)updateImage;
- (void)setFont:(id)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;

@end
