/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIMoreListController;

@interface _UIMoreListTableView : UITableView  {
    UIMoreListController *__listController;
}

@property UIMoreListController * _listController;


- (id)_listController;
- (void)set_listController:(id)arg1;
- (void)didMoveToWindow;

@end
