/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class _UIWebViewController;

@interface _UIRemoteWebViewController : _UIRemoteViewController  {
    _UIWebViewController *_webViewController;
}

@property _UIWebViewController * webViewController;

+ (id)exportedInterface;
+ (id)serviceViewControllerInterface;

- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (void)setWebViewController:(id)arg1;
- (id)webViewController;
- (void)viewServiceDidTerminateWithError:(id)arg1;
- (bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;

@end
