/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIPresentationController<_UISearchControllerPresenting>, _UISearchPresentationAssistant, UIView;

@interface _UISearchPopoverPresentationController : UIPopoverPresentationController <_UISearchControllerPresenting> {
    _UISearchPresentationAssistant *_assistant;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    } finalFrameForContainerView;
}

@property(retain,readonly) UIView * searchBarContainerView;
@property(readonly) bool shouldAccountForStatusBar;
@property(readonly) double statusBarAdjustment;
@property(readonly) bool searchBarToBecomeTopAttached;
@property(readonly) double resultsControllerContentOffset;
@property(readonly) UIPresentationController<_UISearchControllerPresenting> * adaptivePresentationController;
@property(readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } finalFrameForContainerView;


- (void)dealloc;
- (id)_popoverHostingWindow;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })finalFrameForContainerView;
- (id)adaptivePresentationController;
- (bool)shouldAccountForStatusBar;
- (double)resultsControllerContentOffset;
- (void)setContentVisible:(bool)arg1;
- (double)statusBarAdjustment;
- (bool)searchBarToBecomeTopAttached;
- (id)searchBarContainerView;
- (id)_presentedViewControllerForSizeClassPair:(struct { long long x1; long long x2; })arg1;
- (id)_presentationControllerForSizeClassPair:(struct { long long x1; long long x2; })arg1;
- (long long)adaptivePresentationStyle;
- (void)_transitionToWillBegin;
- (void)_transitionFromWillBegin;
- (void)presentationTransitionWillBegin;
- (void)_transitionFromDidEnd;
- (void)_transitionToDidEnd;
- (id)initWithPresentingViewController:(id)arg1 presentedViewController:(id)arg2;

@end
