/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSObject<OS_dispatch_queue>, _UIAsyncInvocation, NSObject<OS_xpc_object>;

@interface _UIViewServiceXPCListener : NSObject  {
    NSObject<OS_xpc_object> *_connection;
    NSObject<OS_dispatch_queue> *_incomingConnectionQueue;
    _UIAsyncInvocation *_invalidationInvocation;
    int __automatic_invalidation_retainCount;
    BOOL __automatic_invalidation_invalidated;
}


- (id)invalidate;
- (void)dealloc;
- (unsigned int)retainCount;
- (oneway void)release;
- (id)retain;
- (BOOL)_tryRetain;
- (BOOL)_isDeallocating;
- (id)endpoint;
- (id)initWithName:(id)arg1 connectionHandler:(id)arg2;
- (void)_invalidateUnconditionallyThen:(id)arg1;
- (int)__automatic_invalidation_logic;

@end
