/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UICellHighlightingSupport : NSObject  {
    struct __CFDictionary { } *_unhighlightedStates;
    id _cell;
}


- (void)dealloc;
- (id)initWithCell:(id)arg1;
- (void)cacheState:(unsigned long long)arg1 forView:(id)arg2;
- (void)applyState:(unsigned long long)arg1 toView:(id)arg2;
- (void)highlightView:(id)arg1;

@end
