/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIImageView, UIImage;

@interface UIClassicStatusBarView : _UIScrollsToTopInitiatorView  {
    UIImageView *_backgroundView;
    UIImage *_image;
}

@property(retain) UIImage * image;


- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setImage:(id)arg1;
- (id)image;
- (void)dealloc;

@end
