/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKBRenderFactoryiPad10Key_Portrait : UIKBRenderFactory10Key_Landscape  {
}


- (id)muttitapReverseKeyImageName;
- (id)multitapCompleteKeyImageName;
- (float)controlColumnWidthFactor;
- (id)_traitsForKey:(id)arg1 onKeyplane:(id)arg2;

@end
