/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKBRenderFactory50On_Portrait : UIKBRenderFactory10Key  {
}


- (double)deleteKeyFontSize;
- (double)returnKeyFontSize;
- (double)keyplaneSwitchKeyFontSize;
- (double)spaceKeyFontSize;
- (void)setupLayoutSegments;
- (double)controlColumnWidthFactor;
- (double)keyCornerRadius;
- (id)thinKeycapsFontName;
- (void)_customizeTraits:(id)arg1 forPopupForKey:(id)arg2 withRenderConfig:(id)arg3 keycapsFontName:(id)arg4;
- (id)lightKeycapsFontName;
- (id)_traitsForKey:(id)arg1 onKeyplane:(id)arg2;

@end
