/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKeyboardButton : UIButton  {
    long long _keyboardButtonStyle;
}

@property(readonly) long long keyboardButtonStyle;


- (long long)keyboardButtonStyle;
- (id)initWithKeyboardButtonStyle:(long long)arg1;

@end
