/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSString;

@interface UIMenuItem : NSObject  {
    NSString *_title;
    SEL _action;
    BOOL _dontDismiss;
}

@property(copy) NSString * title;
@property SEL action;
@property BOOL dontDismiss;


- (void)setTitle:(id)arg1;
- (id)title;
- (void)dealloc;
- (BOOL)dontDismiss;
- (void)setDontDismiss:(BOOL)arg1;
- (id)initWithTitle:(id)arg1 action:(SEL)arg2;
- (void)setAction:(SEL)arg1;
- (SEL)action;

@end
