/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIDelayedAction, UIResponder<UITextInput>;

@interface UIPhraseBoundaryGestureRecognizer : UILongPressGestureRecognizer  {
    UIResponder<UITextInput> *_textInput;
    UIDelayedAction *_secondDelayTimer;
    double _secondDelay;
    bool_secondDelayElapsed;
    id _userData;
}

@property UIResponder<UITextInput> * textInput;
@property double secondDelay;
@property(readonly) bool secondDelayElapsed;
@property id userData;


- (void)setState:(long long)arg1;
- (void)setUserData:(id)arg1;
- (id)userData;
- (bool)secondDelayElapsed;
- (void)setSecondDelay:(double)arg1;
- (void)setTextInput:(id)arg1;
- (id)textInput;
- (double)secondDelay;
- (void)secondDelayElapsed:(id)arg1;
- (void)startTimer;
- (void)clearTimer;
- (void)_resetGestureRecognizer;

@end
