/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class UIPrintInfo, UIPrintPaper, UIPrintPanelViewController, UIPrintingProgress, UIPrintPageRenderer, PKPrintSettings, PKPrinter;

@interface UIPrintInteractionControllerInternals : NSObject  {
    long long _pageCount;
    struct _NSRange { 
        unsigned long long location; 
        unsigned long long length; 
    } _pageRange;
    long long _currentPage;
    UIPrintPanelViewController *_printPanelViewController;
    UIPrintingProgress *_printingProgress;
    PKPrinter *_printer;
    UIPrintPaper *_paper;
    PKPrintSettings *_printSettings;
    UIPrintInfo *_activePrintInfo;
    int _printInfoState;
    bool_supressNotifyDismissed;
    UIPrintPageRenderer *_formatterRenderer;
    bool_manualPrintPageEnabled;
}


- (void)dealloc;

@end
