/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIRemoteControlEvent : UIInternalEvent  {
    int _subtype;
}


- (int)subtype;
- (void)dealloc;
- (void)_simpleRemoteActionNotification:(id)arg1;
- (void)_sendEventToResponder:(id)arg1;
- (id)_windows;
- (void)_setSubtype:(int)arg1;
- (int)type;
- (id)_init;

@end
