/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSLayoutConstraint, UIView;

@interface UISearchDisplayControllerContainerView : UIView  {
    BOOL _collapsedTopView;
    UIView *_topView;
    UIView *_bottomView;
    UIView *_behindView;
    NSLayoutConstraint *_topViewHeightConstraint;
    NSLayoutConstraint *_topViewAttributeTopConstraint;
}

@property(readonly) UIView * topView;
@property(readonly) UIView * bottomView;
@property(readonly) UIView * behindView;
@property(retain) NSLayoutConstraint * topViewHeightConstraint;
@property(retain) NSLayoutConstraint * topViewAttributeTopConstraint;


- (void)setFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (id)topViewAttributeTopConstraint;
- (id)topViewHeightConstraint;
- (void)setTopViewAttributeTopConstraint:(id)arg1;
- (void)setTopViewHeightConstraint:(id)arg1;
- (id)behindView;
- (id)bottomView;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1 topViewHeight:(float)arg2;
- (void)adjustTopAttributeConstantByDelta:(float)arg1;
- (void)configureInteractionForContainment:(BOOL)arg1;
- (void)updateTopViewHeight:(float)arg1 animateUpdate:(BOOL)arg2;
- (void)collapseTopView;
- (void)updateTopAttributeConstant:(float)arg1;
- (void)updateTopViewHeight:(float)arg1;
- (void)setBottomViewUserInteractionEnabled:(BOOL)arg1;
- (id)topView;
- (void)_didMoveFromWindow:(id)arg1 toWindow:(id)arg2;
- (id)hitTest:(struct CGPoint { float x1; float x2; })arg1 withEvent:(id)arg2;

@end
