/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarHomeItemView : UIStatusBarButtonActionItemView  {
}


- (BOOL)usesAdvancedActions;
- (id)contentsImage;
- (int)buttonType;

@end
