/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@class NSArray, NSString, UIView, UIBarButtonItem;

@interface UIStoryboardPopoverPresentationSegue : UIStoryboardSegue <UIPopoverPresentationControllerDelegate> {
    NSArray *_passthroughViews;
    unsigned long long _permittedArrowDirections;
    UIBarButtonItem *_anchorBarButtonItem;
    UIView *_anchorView;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    } _anchorRect;
}

@property(copy) NSArray * passthroughViews;
@property unsigned long long permittedArrowDirections;
@property(retain) UIBarButtonItem * anchorBarButtonItem;
@property(retain) UIView * anchorView;
@property struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } anchorRect;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;


- (void)dealloc;
- (void)setAnchorRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setAnchorView:(id)arg1;
- (void)setAnchorBarButtonItem:(id)arg1;
- (void)setPassthroughViews:(id)arg1;
- (id)passthroughViews;
- (void)perform;
- (void)setPermittedArrowDirections:(unsigned long long)arg1;
- (unsigned long long)permittedArrowDirections;
- (id)anchorBarButtonItem;
- (id)anchorView;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })anchorRect;
- (void)_prepare;

@end
