/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@class <ABResponderDelegate>, UIColor;

@interface ABHighlightingTextField : UITextField  {
    BOOL _isHighlighted;
    BOOL _isHighlightingEnabled;
    UIColor *_savedTextColor;
    UIColor *_highlightedTextColor;
    BOOL _showsClearButtonWhenEmpty;
    <ABResponderDelegate> *_responderDelegate;
}

@property(setter=abSetHighlighted:) BOOL abIsHighlighted;
@property(setter=abSetHighlightingEnabled:) BOOL abIsHighlightingEnabled;
@property(setter=abSetHighlightedTextColor:,retain) UIColor * abHighlightedTextColor;
@property BOOL showsClearButtonWhenEmpty;
@property <ABResponderDelegate> * responderDelegate;

+ (id)_initializeSafeCategoryFromValidationManager;
+ (void)_initializeSafeCategory;

- (BOOL)showsClearButtonWhenEmpty;
- (void)setResponderDelegate:(id)arg1;
- (id)responderDelegate;
- (void)abSetHighlightedTextColor:(id)arg1;
- (id)abHighlightedTextColor;
- (void)abSetHighlightingEnabled:(BOOL)arg1;
- (BOOL)abIsHighlightingEnabled;
- (BOOL)abIsHighlighted;
- (void)setShowsClearButtonWhenEmpty:(BOOL)arg1;
- (void)abSetHighlighted:(BOOL)arg1;
- (BOOL)becomeFirstResponder;
- (void)dealloc;
- (BOOL)_showsClearButtonWhenEmpty;
- (void)setTextColor:(id)arg1;
- (id)_previousKeyResponder;
- (id)_nextKeyResponder;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })accessibilityFrame;
- (unsigned long long)accessibilityTraits;
- (BOOL)accessibilityElementsHidden;
- (id)accessibilityLabel;

@end
