/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@class <ABMultipleSourceImagePickerDelegate>, NSMutableArray;

@interface ABMultipleImagePickerViewController : UITableViewController  {
    NSMutableArray *_imageCellData;
    unsigned long long _selectedImageIndex;
    <ABMultipleSourceImagePickerDelegate> *_delegate;
}

@property <ABMultipleSourceImagePickerDelegate> * delegate;


- (void)addImageData:(id)arg1 title:(id)arg2 isSelectedImage:(bool)arg3 person:(id)arg4;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)dealloc;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;

@end
