/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@class NSArray, NSMutableArray;

@interface ABMultiCellContentView_Address : ABMultiCellContentView_DisplayAlternate  {
    NSArray *_lineInfos;
    NSMutableArray *_lineSubviews;
    struct _NSRange { 
        unsigned long long location; 
        unsigned long long length; 
    } _streetRange;
    unsigned long long _entryFieldIndexOfFirstStreetField;
    NSMutableArray *_verticalDividers;
}

+ (unsigned long long)rowsForPropertyGroup:(id)arg1 info:(id)arg2;
+ (long long)calculateStreetRowsForText:(id)arg1;
+ (id)streetTextForPropertyGroup:(id)arg1 info:(id)arg2;
+ (id)lineInfosForPropertyGroup:(id)arg1 info:(id)arg2;
+ (struct CGSize { double x1; double x2; })layoutSubviewsForView:(id)arg1 usingSize:(struct CGSize { double x1; double x2; })arg2 propertyGroup:(id)arg3 info:(id)arg4 styleProvider:(id)arg5 whenEditing:(bool)arg6;

- (id)pickerView;
- (void)removeStreetFieldAtIndex:(unsigned long long)arg1 animated:(bool)arg2;
- (void)addStreetFieldAnimated:(bool)arg1;
- (id)streetFieldAtLineIndex:(unsigned long long)arg1;
- (unsigned long long)lineIndexOfStreetField:(id)arg1;
- (id)propertyKeyForTag:(long long)arg1;
- (void)removeTextFieldAnimationDidStop:(id)arg1 finished:(id)arg2 context:(void*)arg3;
- (void)textFieldTextDidChange:(id)arg1;
- (long long)tagForPropertyKey:(id)arg1;
- (void)setPropertyGroupInfo:(id)arg1;
- (void)reloadFromModel;
- (void)reload;
- (void)dealloc;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)setEditing:(bool)arg1 animated:(bool)arg2;

@end
