/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@class UITextField;

@interface ABPickerItemCell : UITableViewCell  {
    UITextField *_textField;
}

@property(retain) UITextField * textField;


- (void)endEditing;
- (void)beginEditing;
- (void)dealloc;
- (void)setTextField:(id)arg1;
- (id)textField;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;

@end
