/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@interface ABPropertyGroupURLAddressItem : ABPropertyGroupItem  {
}


- (id)_urlWithUserString:(id)arg1;
- (id)displayStringForValue:(id)arg1;
- (id)defaultActionURL;

@end
