/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AddressBookUI.framework/AddressBookUI
 */

@class NSString, UITextField, <ABPropertyEditingTableViewCellDelegate>;

@interface ABPropertyEditingTableViewCell : UITableViewCell <ABStyleProviding> {
    int _property;
    UITextField *_textField;
    NSString *_placeholder;
    <ABPropertyEditingTableViewCellDelegate> *_delegate;
}

@property int property;
@property bool usesLargeFont;
@property(copy) NSString * placeholder;
@property(copy) NSString * value;
@property <ABPropertyEditingTableViewCellDelegate> * delegate;


- (void)setUsesLargeFont:(bool)arg1;
- (bool)usesLargeFont;
- (void)_resizeAndCenterTextField;
- (id)initWithReuseIdentifier:(id)arg1 property:(int)arg2 delegate:(id)arg3;
- (id)styleProvider;
- (void)setProperty:(int)arg1;
- (int)property;
- (id)value;
- (void)setValue:(id)arg1;
- (bool)resignFirstResponder;
- (bool)becomeFirstResponder;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)dealloc;
- (id)placeholder;
- (bool)canResignFirstResponder;
- (void)setPlaceholder:(id)arg1;
- (void)textFieldValueDidChange:(id)arg1;
- (id)initWithReuseIdentifier:(id)arg1;
- (bool)canBecomeFirstResponder;
- (bool)isFirstResponder;
- (void)layoutSubviews;

@end
