/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@interface GEOGeocodeProvider : NSObject  {

  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _successHandler;


  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _batchSuccessHandler;


  /* Unexpected information at end of encoded ivar type: ? */
  /* Error parsing encoded ivar type info: @? */
    id _errorHandler;

}

@property(copy) id successHandler;
@property(copy) id batchSuccessHandler;
@property(copy) id errorHandler;

+ (id)providerName;

- (void)setBatchSuccessHandler:(id)arg1;
- (id)batchSuccessHandler;
- (void)setSuccessHandler:(id)arg1;
- (id)successHandler;
- (void)batchReverseGeocode:(id)arg1 success:(id)arg2 error:(id)arg3;
- (void)reverseGeocode:(id)arg1 success:(id)arg2 error:(id)arg3;
- (void)forwardGeocode:(id)arg1 success:(id)arg2 networkActivity:(id)arg3 error:(id)arg4;
- (void)cancel;
- (void)dealloc;
- (id)errorHandler;
- (void)setErrorHandler:(id)arg1;

@end
