/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class NSArray;

@interface GEOMapItemReviewsAttribution : GEOMapItemAttribution  {
}

@property(readonly) NSArray * addReviewURLs;


- (id)urlsForSelectedItemWithItems:(id)arg1;
- (id)urlsForReviewWithIdentifier:(id)arg1;
- (id)addReviewURLs;
- (id)initWithSearchAttributionInfo:(id)arg1 attributionURLs:(id)arg2 yelpID:(id)arg3;

@end
