/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class GEOPlaceSearchResponse, GEOPlaceSearchRequest, NSString;

@interface GEORPCorrectedSearch : PBCodable <NSCopying> {
    unsigned int _correctedSearchResultIndex;
    unsigned int _originalSearchResultIndex;
    GEOPlaceSearchRequest *_placeSearchRequest;
    GEOPlaceSearchResponse *_placeSearchResponse;
    NSString *_preferredSearchDisplayLocation;
    struct { 
        unsigned int correctedSearchResultIndex : 1; 
        unsigned int originalSearchResultIndex : 1; 
    } _has;
}

@property(readonly) bool hasPlaceSearchRequest;
@property(retain) GEOPlaceSearchRequest * placeSearchRequest;
@property(readonly) bool hasPlaceSearchResponse;
@property(retain) GEOPlaceSearchResponse * placeSearchResponse;
@property bool hasOriginalSearchResultIndex;
@property unsigned int originalSearchResultIndex;
@property bool hasCorrectedSearchResultIndex;
@property unsigned int correctedSearchResultIndex;
@property(readonly) bool hasPreferredSearchDisplayLocation;
@property(retain) NSString * preferredSearchDisplayLocation;


- (id)preferredSearchDisplayLocation;
- (unsigned int)correctedSearchResultIndex;
- (unsigned int)originalSearchResultIndex;
- (bool)hasPreferredSearchDisplayLocation;
- (bool)hasCorrectedSearchResultIndex;
- (void)setHasCorrectedSearchResultIndex:(bool)arg1;
- (void)setCorrectedSearchResultIndex:(unsigned int)arg1;
- (bool)hasOriginalSearchResultIndex;
- (void)setHasOriginalSearchResultIndex:(bool)arg1;
- (void)setOriginalSearchResultIndex:(unsigned int)arg1;
- (void)setPreferredSearchDisplayLocation:(id)arg1;
- (id)placeSearchResponse;
- (bool)hasPlaceSearchResponse;
- (void)setPlaceSearchResponse:(id)arg1;
- (id)placeSearchRequest;
- (bool)hasPlaceSearchRequest;
- (void)setPlaceSearchRequest:(id)arg1;
- (void)copyTo:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;
- (bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)dealloc;
- (id)description;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)dictionaryRepresentation;

@end
