/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class NSMutableArray;

@interface GEOVersionManifest : PBCodable <NSCopying> {
    NSMutableArray *_serviceVersions;
}

@property(retain) NSMutableArray * serviceVersions;


- (id)serviceVersions;
- (id)serviceVersionAtIndex:(unsigned long long)arg1;
- (void)clearServiceVersions;
- (unsigned long long)serviceVersionsCount;
- (void)addServiceVersion:(id)arg1;
- (void)setServiceVersions:(id)arg1;
- (void)copyTo:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)writeTo:(id)arg1;
- (bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)dealloc;
- (id)description;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)dictionaryRepresentation;

@end
