/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@class GEONetworkDataReader, GEOTileKeyList, <GEOVoltaireMultiTileDownloaderDelegate>, GEOTileKeyMap, NSURLConnection, NSMutableSet, NSString, NSData, NSURL;

@interface GEOVoltaireMultiTileDownloader : NSObject <NSURLConnectionDelegate> {
    GEOTileKeyList *_keyList;
    GEOTileKeyList *_requiresLocalization;
    GEOTileKeyList *_receivedKeys;
    NSURL *_requestURL;
    BOOL _useStatusCodes;
    NSMutableSet *_errorCodes;
    NSURLConnection *_connection;
    GEONetworkDataReader *_reader;
    NSString *_sharedPrefix;
    NSString *_userAgent;
    NSData *_auditToken;
    <GEOVoltaireMultiTileDownloaderDelegate> *_delegate;
    unsigned short _providerID;
    GEOTileKeyMap *_baseTilesWaitingForLocalized;
    GEOTileKeyMap *_localizedTilesWaitingForBase;
    NSString *_postString;
    BOOL _requireWiFi;
    int _attempts;
    double _startTime;
    double _timeout;
}

@property(retain) NSString * userAgent;
@property(retain) NSData * auditToken;
@property(readonly) NSURL * requestURL;
@property BOOL useStatusCodes;
@property BOOL requireWiFi;
@property <GEOVoltaireMultiTileDownloaderDelegate> * delegate;


- (void)_failWithError:(id)arg1;
- (void)_tryParseTiles;
- (void)logDownloadDetails;
- (id)_mergeBaseTile:(id)arg1 withLocalizationTile:(id)arg2;
- (struct _GEOTileKey { unsigned int x1 : 6; unsigned int x2 : 26; unsigned int x3 : 26; unsigned int x4 : 6; unsigned int x5 : 8; unsigned int x6 : 8; unsigned int x7 : 8; unsigned int x8 : 1; unsigned int x9 : 7; unsigned char x10[4]; })_tileKeyForURL:(id)arg1 edition:(unsigned int*)arg2 isLocalized:(BOOL*)arg3;
- (id)_localizationURLForTileKey:(struct _GEOTileKey { unsigned int x1 : 6; unsigned int x2 : 26; unsigned int x3 : 26; unsigned int x4 : 6; unsigned int x5 : 8; unsigned int x6 : 8; unsigned int x7 : 8; unsigned int x8 : 1; unsigned int x9 : 7; unsigned char x10[4]; }*)arg1;
- (void)_cleanupConnection;
- (id)_localizationURLIfNecessaryForTileKey:(struct _GEOTileKey { unsigned int x1 : 6; unsigned int x2 : 26; unsigned int x3 : 26; unsigned int x4 : 6; unsigned int x5 : 8; unsigned int x6 : 8; unsigned int x7 : 8; unsigned int x8 : 1; unsigned int x9 : 7; unsigned char x10[4]; }*)arg1;
- (id)_urlForTileKey:(struct _GEOTileKey { unsigned int x1 : 6; unsigned int x2 : 26; unsigned int x3 : 26; unsigned int x4 : 6; unsigned int x5 : 8; unsigned int x6 : 8; unsigned int x7 : 8; unsigned int x8 : 1; unsigned int x9 : 7; unsigned char x10[4]; }*)arg1;
- (id)requestURL;
- (void)setUseStatusCodes:(BOOL)arg1;
- (id)initWithURL:(id)arg1 keyList:(id)arg2;
- (BOOL)useStatusCodes;
- (BOOL)requireWiFi;
- (double)elapsed;
- (void)setAuditToken:(id)arg1;
- (void)setRequireWiFi:(BOOL)arg1;
- (id)userAgent;
- (void)setUserAgent:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (id)delegate;
- (void)cancel;
- (void)_cancelWithError:(id)arg1;
- (id)auditToken;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)start;

@end
