/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSEnumerator, NSString, NSArray;

@interface AVAssetTrackEnumerator : NSEnumerator  {
    NSString *_mediaType;
    NSArray *_mediaCharacteristics;
    NSEnumerator *_enumerator;
}

+ (id)trackEnumeratorWithAsset:(id)arg1;

- (void)setMediaCharacteristics:(id)arg1;
- (void)setMediaType:(id)arg1;
- (id)initWithAsset:(id)arg1 mediaCharacteristics:(id)arg2;
- (id)initWithAsset:(id)arg1 mediaType:(id)arg2;
- (id)nextObject;
- (void)dealloc;
- (id)initWithAsset:(id)arg1;

@end
