/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/libAVFAudio.dylib
 */

@class AVAudioEnvironmentDistanceAttenuationParameters, AVAudioEnvironmentReverbParameters, NSString;

@interface AVAudioEnvironmentNode : AVAudioNode <AVAudioMixing> {
}

@property float outputVolume;
@property(readonly) unsigned long long nextAvailableInputBus;
@property struct AVAudio3DPoint { float x1; float x2; float x3; } listenerPosition;
@property struct AVAudio3DVectorOrientation { struct AVAudio3DPoint { float x_1_1_1; float x_1_1_2; float x_1_1_3; } x1; struct AVAudio3DPoint { float x_2_1_1; float x_2_1_2; float x_2_1_3; } x2; } listenerVectorOrientation;
@property struct AVAudio3DAngularOrientation { float x1; float x2; float x3; } listenerAngularOrientation;
@property(readonly) AVAudioEnvironmentDistanceAttenuationParameters * distanceAttenuationParameters;
@property(readonly) AVAudioEnvironmentReverbParameters * reverbParameters;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy,readonly) NSString * description;
@property(copy,readonly) NSString * debugDescription;
@property float volume;


- (id)reverbParameters;
- (id)distanceAttenuationParameters;
- (struct AVAudio3DAngularOrientation { float x1; float x2; float x3; })listenerAngularOrientation;
- (void)setListenerAngularOrientation:(struct AVAudio3DAngularOrientation { float x1; float x2; float x3; })arg1;
- (struct AVAudio3DVectorOrientation { struct AVAudio3DPoint { float x_1_1_1; float x_1_1_2; float x_1_1_3; } x1; struct AVAudio3DPoint { float x_2_1_1; float x_2_1_2; float x_2_1_3; } x2; })listenerVectorOrientation;
- (void)setListenerVectorOrientation:(struct AVAudio3DVectorOrientation { struct AVAudio3DPoint { float x_1_1_1; float x_1_1_2; float x_1_1_3; } x1; struct AVAudio3DPoint { float x_2_1_1; float x_2_1_2; float x_2_1_3; } x2; })arg1;
- (struct AVAudio3DPoint { float x1; float x2; float x3; })listenerPosition;
- (void)setListenerPosition:(struct AVAudio3DPoint { float x1; float x2; float x3; })arg1;
- (id)applicableRenderingAlgorithms;
- (unsigned long long)nextAvailableInputBus;
- (float)outputVolume;
- (void)setOutputVolume:(float)arg1;
- (id)init;

@end
