/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class AVCaptureVideoDataOutputInternal, NSArray, NSObject<OS_dispatch_queue>, <AVCaptureVideoDataOutputSampleBufferDelegate>, NSDictionary;

@interface AVCaptureVideoDataOutput : AVCaptureOutput  {
    AVCaptureVideoDataOutputInternal *_internal;
}

@property(readonly) <AVCaptureVideoDataOutputSampleBufferDelegate> * sampleBufferDelegate;
@property(readonly) NSObject<OS_dispatch_queue> * sampleBufferCallbackQueue;
@property(copy) NSDictionary * videoSettings;
@property(readonly) NSArray * availableVideoCVPixelFormatTypes;
@property(readonly) NSArray * availableVideoCodecTypes;
@property struct { long long x1; int x2; unsigned int x3; long long x4; } minFrameDuration;
@property BOOL alwaysDiscardsLateVideoFrames;

+ (id)supportedVideoSettingsKeys;
+ (void)initialize;

- (void)_AVCaptureVideoDataOutput_VideoDataBecameReady;
- (void)setAlwaysDiscardsLateVideoFrames:(BOOL)arg1;
- (void)setMinFrameDuration:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg1;
- (void)setVideoSettings:(id)arg1;
- (void)_setMinFrameDuration:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg1;
- (id)availableVideoCodecTypes;
- (id)availableVideoCVPixelFormatTypes;
- (id)vettedVideoSettingsForSettingsDictionary:(id)arg1;
- (BOOL)alwaysDiscardsLateVideoFrames;
- (id)videoSettings;
- (id)addConnection:(id)arg1 error:(id*)arg2;
- (BOOL)appliesOrientationWithPhysicalRotationForConnection:(id)arg1;
- (BOOL)appliesMirroringWithPhysicalFlipForConnection:(id)arg1;
- (struct CGSize { float x1; float x2; })outputSizeForCaptureOptions:(id)arg1;
- (struct { long long x1; int x2; unsigned int x3; long long x4; })minFrameDuration;
- (void)didStartForSession:(id)arg1;
- (void)didStopForSession:(id)arg1 error:(id)arg2;
- (void)handleEnabledChangedForConnection:(id)arg1;
- (id)connectionMediaTypes;
- (id)sampleBufferCallbackQueue;
- (id)sampleBufferDelegate;
- (void)setSampleBufferDelegate:(id)arg1 queue:(id)arg2;
- (void)_applyOverridesToCaptureOptions:(id)arg1;
- (BOOL)isTheOnlyDataOutput;
- (id)init;
- (void)dealloc;
- (void)setSession:(id)arg1;

@end
