/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class <AVCaptureAudioDataOutputSampleBufferDelegate>, NSObject<OS_dispatch_queue>, AVCaptureAudioDataOutputInternal;

@interface AVCaptureAudioDataOutput : AVCaptureOutput  {
    AVCaptureAudioDataOutputInternal *_internal;
}

@property(readonly) <AVCaptureAudioDataOutputSampleBufferDelegate> * sampleBufferDelegate;
@property(readonly) NSObject<OS_dispatch_queue> * sampleBufferCallbackQueue;

+ (void)initialize;

- (void)_AVCaptureAudioDataOutput_AudioDataBecameReady;
- (void)didStartForSession:(id)arg1;
- (void)didStopForSession:(id)arg1 error:(id)arg2;
- (void)handleEnabledChangedForConnection:(id)arg1;
- (id)connectionMediaTypes;
- (id)sampleBufferCallbackQueue;
- (id)sampleBufferDelegate;
- (void)setSampleBufferDelegate:(id)arg1 queue:(id)arg2;
- (void)_applyOverridesToCaptureOptions:(id)arg1;
- (BOOL)isTheOnlyDataOutput;
- (id)init;
- (void)dealloc;
- (void)setSession:(id)arg1;

@end
