/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSArray, AVWeakReference, NSMutableArray;

@interface AVCaptureMovieFileOutputInternal : NSObject  {
    AVWeakReference *weakReference;
    NSMutableArray *recordingDelegatesArray;
    struct { 
        long long value; 
        int timescale; 
        unsigned int flags; 
        long long epoch; 
    } movieFragmentInterval;
    NSArray *metadata;
    boolsendLastVideoPreviewFrame;
    boolrecording;
    boolpaused;
}


- (id)init;
- (void)dealloc;

@end
