/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode5.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSError, AVRunLoopCondition, AVCaptureFigAudioDevice, NSMutableArray, AVWeakReference, AVCaptureFigVideoDevice, NSString, AVCaptureVideoPreviewLayer, NSMutableDictionary;

@interface AVCaptureSessionInternal : NSObject  {
    AVWeakReference *weakReference;
    NSString *sessionPreset;
    BOOL adjustingDeviceActiveFormat;
    int sessionPresetChangeSeed;
    int resolvedSessionPresetChangeSeed;
    int videoDeviceChangeSeed;
    int resolvedVideoDeviceChangeSeed;
    int beginConfigRefCount;
    NSMutableDictionary *captureOptions;
    NSMutableDictionary *figRecorderOptions;
    AVCaptureFigAudioDevice *audioDevice;
    AVCaptureFigVideoDevice *videoDevice;
    struct OpaqueCMBaseObject { } *recorder;
    NSMutableArray *inputs;
    NSMutableArray *outputs;
    NSMutableArray *connections;
    NSMutableArray *liveConnections;
    AVCaptureVideoPreviewLayer *videoPreviewLayer;
    NSError *stopError;
    BOOL running;
    BOOL interrupted;
    BOOL recording;
    BOOL usesApplicationAudioSession;
    BOOL automaticallyConfiguresApplicationAudioSession;
    AVRunLoopCondition *runLoopCondition;
    BOOL waitingForRecorderDidStartPreviewing;
    BOOL waitingForRecorderDidStartRecording;
    BOOL waitingForRecorderDidStopSource;
    BOOL waitingForRecorderDidStopPreviewing;
    BOOL waitingForRecorderDidStopRecording;
    struct OpaqueCMClock { } *masterClock;
}


- (id)init;
- (void)dealloc;

@end
