/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class NSArray, AVCompositionTrackInternal;

@interface AVCompositionTrack : AVAssetTrack  {
    AVCompositionTrackInternal *_priv;
}

@property(copy,readonly) NSArray * segments;


- (id)segments;
- (id)_initWithAsset:(id)arg1 trackID:(int)arg2 trackIndex:(long long)arg3;
- (struct OpaqueFigMutableComposition { }*)_mutableComposition;
- (void)finalize;
- (void)dealloc;
- (id)description;

@end
