/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.0.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@class AVCompositionInternal, NSArray;

@interface AVComposition : AVAsset <NSMutableCopying> {
    AVCompositionInternal *_priv;
}

@property(readonly) NSArray * tracks;
@property(readonly) struct CGSize { double x1; double x2; } naturalSize;

+ (void)initialize;

- (void)_setNaturalSize:(struct CGSize { double x1; double x2; })arg1;
- (int)_createEmptyMutableCompositionIfNeeded;
- (id)_mutableTracks;
- (id)_newTrackForIndex:(long long)arg1;
- (void)_loadAssetInspectorAndLoaderOnce;
- (id)_initWithComposition:(id)arg1;
- (struct OpaqueFigMutableComposition { }*)_mutableComposition;
- (id)_assetInspectorLoader;
- (Class)_classForTrackInspectors;
- (struct OpaqueFigFormatReader { }*)_formatReader;
- (id)_assetInspector;
- (id)tracks;
- (struct CGSize { double x1; double x2; })naturalSize;
- (id)init;
- (void)finalize;
- (void)dealloc;
- (id)description;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;

@end
